import type {FastifyInstance} from 'fastify';import {z} from 'zod';import type{Db}from'../db/index.js';import{one,transaction}from'../db/index.js';import{requirePermission}from'../core/http.js';import{audit,emitEvent}from'../core/audit.js';
export async function commercialRoutes(app:FastifyInstance,{db}:{db:Db}){
app.get('/v1/documents',async r=>{const a=requirePermission(r,'documents.read');return(await db.query('SELECT id,name,category,mime_type,status,version,created_at,updated_at FROM documents WHERE organisation_id=$1 ORDER BY updated_at DESC',[a.organisationId])).rows});
app.post('/v1/documents',async(r,p)=>{const a=requirePermission(r,'documents.manage'),b=z.object({name:z.string().min(2).max(240),category:z.string().max(100).default('general'),content:z.string().max(1000000).default('')}).parse(r.body);const x=await one<any>(db,'INSERT INTO documents(organisation_id,name,category,content,created_by) VALUES($1,$2,$3,$4,$5) RETURNING *',[a.organisationId,b.name,b.category,b.content,a.userId]);await audit(db,{organisationId:a.organisationId,actorUserId:a.userId,action:'document.created',resourceType:'document',resourceId:x.id,afterState:x});return p.code(201).send(x)});
app.get('/v1/documents/:id',async r=>{const a=requirePermission(r,'documents.read'),q=z.object({id:z.string().uuid()}).parse(r.params);return one(db,'SELECT * FROM documents WHERE id=$1 AND organisation_id=$2',[q.id,a.organisationId])});
app.patch('/v1/documents/:id',async r=>{const a=requirePermission(r,'documents.manage'),q=z.object({id:z.string().uuid()}).parse(r.params),b=z.object({name:z.string().min(2).optional(),content:z.string().max(1000000).optional(),status:z.enum(['active','archived']).optional()}).parse(r.body);return one(db,'UPDATE documents SET name=COALESCE($1,name),content=COALESCE($2,content),status=COALESCE($3,status),version=version+1,updated_at=now() WHERE id=$4 AND organisation_id=$5 RETURNING *',[b.name??null,b.content??null,b.status??null,q.id,a.organisationId])});
app.get('/v1/assets',async r=>{const a=requirePermission(r,'assets.read');return(await db.query('SELECT * FROM assets WHERE organisation_id=$1 ORDER BY created_at DESC',[a.organisationId])).rows});
app.post('/v1/assets',async(r,p)=>{const a=requirePermission(r,'assets.manage'),b=z.object({code:z.string().min(1).max(80),name:z.string().min(2).max(200),assetType:z.string().min(2).max(100),location:z.string().max(240).optional()}).parse(r.body);const x=await one(db,'INSERT INTO assets(organisation_id,code,name,asset_type,location) VALUES($1,$2,$3,$4,$5) RETURNING *',[a.organisationId,b.code.toUpperCase(),b.name,b.assetType,b.location??null]);return p.code(201).send(x)});
app.patch('/v1/assets/:id',async r=>{const a=requirePermission(r,'assets.manage'),q=z.object({id:z.string().uuid()}).parse(r.params),b=z.object({status:z.enum(['active','maintenance','retired','lost']),location:z.string().max(240).optional()}).parse(r.body);return one(db,'UPDATE assets SET status=$1,location=COALESCE($2,location),updated_at=now() WHERE id=$3 AND organisation_id=$4 RETURNING *',[b.status,b.location??null,q.id,a.organisationId])});
app.get('/v1/automations',async r=>{const a=requirePermission(r,'automation.read');return(await db.query('SELECT * FROM automations WHERE organisation_id=$1 ORDER BY created_at DESC',[a.organisationId])).rows});
app.post('/v1/automations',async(r,p)=>{const a=requirePermission(r,'automation.manage'),b=z.object({name:z.string().min(2),triggerEvent:z.string().min(2),actionType:z.enum(['create_operation','emit_event']),actionConfig:z.record(z.string(),z.unknown()).default({})}).parse(r.body);const x=await one<any>(db,'INSERT INTO automations(organisation_id,name,trigger_event,action_type,action_config,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[a.organisationId,b.name,b.triggerEvent,b.actionType,JSON.stringify(b.actionConfig),a.userId]);return p.code(201).send(x)});
app.post('/v1/automations/:id/run',async r=>{const a=requirePermission(r,'automation.manage'),q=z.object({id:z.string().uuid()}).parse(r.params);return transaction(db,async c=>{const x=await one<any>(c,'SELECT * FROM automations WHERE id=$1 AND organisation_id=$2 AND is_active=true',[q.id,a.organisationId]);if(x.action_type==='create_operation'){const title=String(x.action_config?.title||`Automation: ${x.name}`);await c.query(`INSERT INTO operation_items(organisation_id,title,priority,metadata,created_by,source_module,external_ref) VALUES($1,$2,'normal',$3,$4,'automation',$5) ON CONFLICT DO NOTHING`,[a.organisationId,title,JSON.stringify({automationId:x.id}),a.userId,`${x.id}-${Date.now()}`])}else await emitEvent(c,a.organisationId,x.trigger_event,'automation',x.id,x.action_config||{});return one(c,'UPDATE automations SET run_count=run_count+1,last_run_at=now() WHERE id=$1 RETURNING *',[x.id])})});
app.get('/v1/analytics/summary',async r=>{const a=requirePermission(r,'analytics.read');const q=await db.query(`SELECT (SELECT count(*) FROM organisation_memberships WHERE organisation_id=$1) users,(SELECT count(*) FROM operation_items WHERE organisation_id=$1) operations,(SELECT count(*) FROM operation_items WHERE organisation_id=$1 AND status='completed') completed_operations,(SELECT count(*) FROM documents WHERE organisation_id=$1) documents,(SELECT count(*) FROM assets WHERE organisation_id=$1) assets,(SELECT count(*) FROM workflow_instances WHERE organisation_id=$1) workflow_runs`,[a.organisationId]);return q.rows[0]});
app.get('/v1/integrations',async r=>{const a=requirePermission(r,'integrations.read');return(await db.query('SELECT id,name,integration_type,endpoint_url,status,config,created_at FROM integrations WHERE organisation_id=$1 ORDER BY created_at DESC',[a.organisationId])).rows});
app.post('/v1/integrations',async(r,p)=>{const a=requirePermission(r,'integrations.manage'),b=z.object({name:z.string().min(2),integrationType:z.string().min(2),endpointUrl:z.string().url().optional()}).parse(r.body);return p.code(201).send(await one(db,'INSERT INTO integrations(organisation_id,name,integration_type,endpoint_url,created_by) VALUES($1,$2,$3,$4,$5) RETURNING *',[a.organisationId,b.name,b.integrationType,b.endpointUrl??null,a.userId]))});
app.post('/v1/integrations/:id/test',async r=>{const a=requirePermission(r,'integrations.manage'),q=z.object({id:z.string().uuid()}).parse(r.params),x=await one<any>(db,'SELECT * FROM integrations WHERE id=$1 AND organisation_id=$2',[q.id,a.organisationId]);if(!x.endpoint_url)return{ok:true,message:'Integration configuration is stored and active; no endpoint configured.'};try{const res=await fetch(x.endpoint_url,{method:'HEAD',signal:AbortSignal.timeout(5000)});return{ok:res.ok,status:res.status}}catch{return{ok:false,message:'Endpoint could not be reached'}}});
app.get('/v1/developer/clients',async r=>{const a=requirePermission(r,'developer.read');return(await db.query('SELECT id,name,client_id,permissions,is_active,created_at,last_used_at FROM module_clients WHERE organisation_id=$1 ORDER BY created_at DESC',[a.organisationId])).rows});
app.get('/v1/security/overview',async r=>{const a=requirePermission(r,'security.read');const [s,l]=await Promise.all([db.query('SELECT count(*) active_sessions FROM sessions WHERE organisation_id=$1 AND revoked_at IS NULL AND expires_at>now()',[a.organisationId]),db.query('SELECT id,action,resource_type,outcome,created_at FROM audit_logs WHERE organisation_id=$1 ORDER BY created_at DESC LIMIT 20',[a.organisationId])]);return{activeSessions:s.rows[0]?.active_sessions??0,recentAudit:l.rows}});
app.get('/v1/search',async r=>{const a=requirePermission(r,'organisation.read'),q=z.object({q:z.string().min(2).max(100)}).parse(r.query),s=`%${q.q}%`;const [d,x,o,u]=await Promise.all([db.query(`SELECT id,name,'document' type FROM documents WHERE organisation_id=$1 AND name ILIKE $2 LIMIT 10`,[a.organisationId,s]),db.query(`SELECT id,name,'asset' type FROM assets WHERE organisation_id=$1 AND (name ILIKE $2 OR code ILIKE $2) LIMIT 10`,[a.organisationId,s]),db.query(`SELECT id,title name,'operation' type FROM operation_items WHERE organisation_id=$1 AND title ILIKE $2 LIMIT 10`,[a.organisationId,s]),db.query(`SELECT u.id,(u.first_name||' '||u.last_name) name,'user' type FROM users u JOIN organisation_memberships m ON m.user_id=u.id WHERE m.organisation_id=$1 AND (u.first_name||' '||u.last_name||' '||u.email) ILIKE $2 LIMIT 10`,[a.organisationId,s])]);return[...d.rows,...x.rows,...o.rows,...u.rows]});
}