import type { FastifyInstance } from 'fastify'; import { z } from 'zod';
import type { Db } from '../db/index.js'; import { one, transaction } from '../db/index.js'; import { audit, emitEvent } from '../core/audit.js'; import { conflict, notFound } from '../core/errors.js'; import { requirePermission } from '../core/http.js';

const createSchema=z.object({title:z.string().min(2).max(240),description:z.string().max(10000).optional(),priority:z.enum(['low','normal','high','critical']).default('normal'),ownerMembershipId:z.string().uuid().optional(),branchId:z.string().uuid().optional(),departmentId:z.string().uuid().optional(),teamId:z.string().uuid().optional(),dueAt:z.string().datetime().optional(),sourceModule:z.string().max(80).optional(),externalRef:z.string().max(160).optional(),metadata:z.record(z.string(),z.unknown()).default({})});
export async function operationRoutes(app:FastifyInstance,{db}:{db:Db}){
 app.get('/v1/operations',async request=>{const a=requirePermission(request,'operations.read');const q=z.object({status:z.enum(['open','in_progress','blocked','completed','cancelled']).optional(),priority:z.enum(['low','normal','high','critical']).optional(),limit:z.coerce.number().int().min(1).max(100).default(50),offset:z.coerce.number().int().min(0).default(0)}).parse(request.query);return (await db.query(`SELECT * FROM operation_items WHERE organisation_id=$1 AND ($2::text IS NULL OR status=$2) AND ($3::text IS NULL OR priority=$3) ORDER BY CASE priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'normal' THEN 3 ELSE 4 END,due_at NULLS LAST,created_at DESC LIMIT $4 OFFSET $5`,[a.organisationId,q.status??null,q.priority??null,q.limit,q.offset])).rows;});
 app.post('/v1/operations',async(request,reply)=>{const a=requirePermission(request,'operations.manage');const b=createSchema.parse(request.body);try{const row=await transaction(db,async c=>{const r=await one<any>(c,`INSERT INTO operation_items(organisation_id,title,description,priority,owner_membership_id,branch_id,department_id,team_id,due_at,source_module,external_ref,metadata,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[a.organisationId,b.title,b.description??null,b.priority,b.ownerMembershipId??null,b.branchId??null,b.departmentId??null,b.teamId??null,b.dueAt??null,b.sourceModule??null,b.externalRef??null,JSON.stringify(b.metadata),a.userId]);await audit(c,{organisationId:a.organisationId,actorUserId:a.userId,sessionId:a.sessionId,action:'operation.created',resourceType:'operation',resourceId:r.id,afterState:r});await emitEvent(c,a.organisationId,'core.operation.created.v1','operation',r.id,r);return r;});return reply.code(201).send(row);}catch(e:any){if(e.code==='23505')throw conflict('An operation already exists for this module reference');if(e.code==='23503')throw notFound('Assigned organisational entity');throw e;}});
 app.patch('/v1/operations/:id',async request=>{const a=requirePermission(request,'operations.manage');const {id}=z.object({id:z.string().uuid()}).parse(request.params);const b=z.object({status:z.enum(['open','in_progress','blocked','completed','cancelled']).optional(),priority:z.enum(['low','normal','high','critical']).optional(),ownerMembershipId:z.string().uuid().nullable().optional(),dueAt:z.string().datetime().nullable().optional(),version:z.number().int().positive()}).parse(request.body);return transaction(db,async c=>{const before=await one<any>(c,'SELECT * FROM operation_items WHERE id=$1 AND organisation_id=$2 FOR UPDATE',[id,a.organisationId]);const r=await c.query(`UPDATE operation_items SET status=COALESCE($1,status),priority=COALESCE($2,priority),owner_membership_id=CASE WHEN $3 THEN $4 ELSE owner_membership_id END,due_at=CASE WHEN $5 THEN $6 ELSE due_at END,version=version+1,updated_at=now() WHERE id=$7 AND organisation_id=$8 AND version=$9 RETURNING *`,[b.status??null,b.priority??null,Object.hasOwn(b,'ownerMembershipId'),b.ownerMembershipId??null,Object.hasOwn(b,'dueAt'),b.dueAt??null,id,a.organisationId,b.version]);if(!r.rowCount)throw conflict('Operation was updated by another request');const row=r.rows[0];await audit(c,{organisationId:a.organisationId,actorUserId:a.userId,sessionId:a.sessionId,action:'operation.updated',resourceType:'operation',resourceId:id,beforeState:before,afterState:row});await emitEvent(c,a.organisationId,'core.operation.updated.v1','operation',id,row);return row;});});
}
