import type { FastifyInstance } from 'fastify'; import { z } from 'zod'; import bcrypt from 'bcryptjs'; import { randomBytes } from 'node:crypto';
import type { Db } from '../db/index.js'; import { one, transaction } from '../db/index.js'; import { audit, emitEvent } from '../core/audit.js'; import { conflict, notFound } from '../core/errors.js'; import { requirePermission } from '../core/http.js';

export async function userRoutes(app: FastifyInstance,{db}:{db:Db}) {
  app.get('/v1/users',async request=>{const a=requirePermission(request,'users.read');return (await db.query(`SELECT u.id,u.email,u.first_name,u.last_name,u.status,m.id membership_id,m.job_title,m.employee_number,m.status membership_status,m.joined_at FROM organisation_memberships m JOIN users u ON u.id=m.user_id WHERE m.organisation_id=$1 ORDER BY u.first_name,u.last_name`,[a.organisationId])).rows;});
  app.post('/v1/users',async(request,reply)=>{const a=requirePermission(request,'users.manage');const b=z.object({email:z.string().email(),firstName:z.string().min(1).max(100),lastName:z.string().min(1).max(100),jobTitle:z.string().max(160).optional(),employeeNumber:z.string().max(80).optional(),roleKey:z.string().default('member')}).parse(request.body);try{const result=await transaction(db,async c=>{const generated=randomBytes(24).toString('base64url');const user=await one<{id:string}>(c,`INSERT INTO users(email,password_hash,first_name,last_name,status) VALUES($1,$2,$3,$4,'invited') ON CONFLICT(email) DO UPDATE SET email=EXCLUDED.email RETURNING id`,[b.email.toLowerCase(),await bcrypt.hash(generated,12),b.firstName,b.lastName]);const membership=await one<any>(c,`INSERT INTO organisation_memberships(organisation_id,user_id,job_title,employee_number,status) VALUES($1,$2,$3,$4,'invited') RETURNING *`,[a.organisationId,user.id,b.jobTitle??null,b.employeeNumber??null]);const assigned=await c.query(`INSERT INTO membership_roles(membership_id,role_id,scope_type,scope_id,granted_by) SELECT $1,id,'organisation',$2,$3 FROM roles WHERE key=$4 AND (organisation_id IS NULL OR organisation_id=$2) ORDER BY organisation_id NULLS LAST LIMIT 1`,[membership.id,a.organisationId,a.userId,b.roleKey]);if(!assigned.rowCount)throw notFound('Role');await audit(c,{organisationId:a.organisationId,actorUserId:a.userId,sessionId:a.sessionId,action:'user.invited',resourceType:'membership',resourceId:membership.id,afterState:{email:b.email,role:b.roleKey}});await emitEvent(c,a.organisationId,'core.user.invited.v1','membership',membership.id,{membershipId:membership.id,email:b.email});return membership;});return reply.code(201).send(result);}catch(e:any){if(e.code==='23505')throw conflict('User is already a member or employee number is in use');throw e;}});
  app.patch('/v1/users/:membershipId/status',async request=>{const a=requirePermission(request,'users.manage');const p=z.object({membershipId:z.string().uuid()}).parse(request.params);const b=z.object({status:z.enum(['active','suspended'])}).parse(request.body);return transaction(db,async c=>{const before=await one<any>(c,'SELECT * FROM organisation_memberships WHERE id=$1 AND organisation_id=$2 FOR UPDATE',[p.membershipId,a.organisationId]);const row=await one<any>(c,'UPDATE organisation_memberships SET status=$1 WHERE id=$2 RETURNING *',[b.status,p.membershipId]);await audit(c,{organisationId:a.organisationId,actorUserId:a.userId,sessionId:a.sessionId,action:'membership.status_changed',resourceType:'membership',resourceId:p.membershipId,beforeState:before,afterState:row});return row;});});
  app.get('/v1/roles',async request=>{const a=requirePermission(request,'roles.read');return (await db.query(`SELECT r.id,r.key,r.name,r.description,r.is_system,COALESCE(array_agg(p.key) FILTER(WHERE p.key IS NOT NULL),'{}') permissions FROM roles r LEFT JOIN role_permissions rp ON rp.role_id=r.id LEFT JOIN permissions p ON p.id=rp.permission_id WHERE r.organisation_id IS NULL OR r.organisation_id=$1 GROUP BY r.id ORDER BY r.name`,[a.organisationId])).rows;});
}
