CREATE TABLE documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organisation_id uuid NOT NULL REFERENCES organisations(id) ON DELETE CASCADE, name varchar(240) NOT NULL, category varchar(100) NOT NULL DEFAULT 'general', mime_type varchar(120) NOT NULL DEFAULT 'text/plain', content text NOT NULL DEFAULT '', status varchar(30) NOT NULL DEFAULT 'active' CHECK(status IN('active','archived')), version integer NOT NULL DEFAULT 1, created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX documents_org_idx ON documents(organisation_id,created_at DESC);
CREATE TABLE assets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organisation_id uuid NOT NULL REFERENCES organisations(id) ON DELETE CASCADE, code varchar(80) NOT NULL, name varchar(200) NOT NULL, asset_type varchar(100) NOT NULL, status varchar(30) NOT NULL DEFAULT 'active' CHECK(status IN('active','maintenance','retired','lost')), location varchar(240), owner_membership_id uuid REFERENCES organisation_memberships(id) ON DELETE SET NULL, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organisation_id,code));
CREATE TABLE automations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organisation_id uuid NOT NULL REFERENCES organisations(id) ON DELETE CASCADE, name varchar(200) NOT NULL, trigger_event varchar(160) NOT NULL, action_type varchar(80) NOT NULL CHECK(action_type IN('create_operation','emit_event')), action_config jsonb NOT NULL DEFAULT '{}', is_active boolean NOT NULL DEFAULT true, run_count integer NOT NULL DEFAULT 0, last_run_at timestamptz, created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE integrations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organisation_id uuid NOT NULL REFERENCES organisations(id) ON DELETE CASCADE, name varchar(160) NOT NULL, integration_type varchar(80) NOT NULL, endpoint_url text, status varchar(30) NOT NULL DEFAULT 'active' CHECK(status IN('active','disabled')), config jsonb NOT NULL DEFAULT '{}', created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organisation_id uuid NOT NULL REFERENCES organisations(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id) ON DELETE CASCADE, title varchar(200) NOT NULL, body text NOT NULL, is_read boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
INSERT INTO permissions(key,description) VALUES ('documents.read','View documents'),('documents.manage','Manage documents'),('assets.read','View assets'),('assets.manage','Manage assets'),('automation.read','View automations'),('automation.manage','Manage and run automations'),('analytics.read','View analytics'),('integrations.read','View integrations'),('integrations.manage','Manage integrations'),('developer.read','View developer resources'),('security.read','View security and audit information'),('notifications.read','View notifications') ON CONFLICT(key) DO NOTHING;
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.key='owner' AND r.organisation_id IS NULL ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.key IN('documents.read','documents.manage','assets.read','assets.manage','automation.read','automation.manage','analytics.read','integrations.read','integrations.manage','developer.read','security.read','notifications.read') WHERE r.key='admin' AND r.organisation_id IS NULL ON CONFLICT DO NOTHING;
