export function loginHtml(){
  return \`<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Revolt-X Shop</title>
<style>
*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;background:#07111f;color:#e8eef8;min-height:100vh;display:grid;place-items:center}
.shell{width:min(1050px,94vw);display:grid;grid-template-columns:1.15fr .85fr;background:#0c1728;border:1px solid #22324a;border-radius:26px;overflow:hidden;box-shadow:0 30px 80px #0008}
.hero{padding:56px;background:radial-gradient(circle at 15% 15%,#1d4ed855,transparent 40%),linear-gradient(145deg,#0b1d35,#07111f)}
.brand{font-weight:900;letter-spacing:.3px;font-size:22px}.brand span{color:#60a5fa}.hero h1{font-size:46px;line-height:1.05;margin:70px 0 18px}.hero p{color:#9fb0c6;font-size:17px;line-height:1.7;max-width:560px}.chips{display:flex;gap:10px;flex-wrap:wrap;margin-top:28px}.chip{padding:9px 12px;border:1px solid #2b4160;border-radius:999px;color:#c6d4e8;background:#0b1a2e}
.login{padding:52px 46px;display:flex;flex-direction:column;justify-content:center;background:#0b1524}.login h2{font-size:28px;margin:0 0 8px}.muted{color:#8da1ba}
label{font-size:13px;color:#a9bbd0;display:block;margin:16px 0 7px}input{width:100%;border:1px solid #31445f;background:#091321;color:#fff;border-radius:12px;padding:13px 14px;outline:none}input:focus{border-color:#60a5fa}
button{width:100%;margin-top:20px;border:0;border-radius:12px;padding:13px 16px;font-weight:800;background:linear-gradient(135deg,#2563eb,#38bdf8);color:#fff;cursor:pointer}.err{min-height:22px;color:#fca5a5;margin-top:14px;font-size:13px}
@media(max-width:800px){.shell{grid-template-columns:1fr}.hero{display:none}.login{padding:36px 24px}}
</style></head><body>
<div class="shell"><section class="hero"><div class="brand">REVOLT-X <span>SHOP</span></div><h1>Run every service business from one operating system.</h1><p>Multi-shop operations, customers, services, jobs, inventory, payments, finance and transaction monitoring powered by Revolt-X OS.</p><div class="chips"><span class="chip">Multi-shop</span><span class="chip">MoMo & Card</span><span class="chip">Finance</span><span class="chip">Customer Portal</span><span class="chip">Audit Trail</span></div></section>
<section class="login"><h2>Sign in</h2><div class="muted">Use your Revolt-X OS account.</div><form id="f"><label>Email</label><input id="email" type="email" required autocomplete="username"><label>Password</label><input id="password" type="password" required autocomplete="current-password"><button>Continue to workspace</button><div id="err" class="err"></div></form></section></div>
<script>
document.getElementById('f').addEventListener('submit',async(e)=>{e.preventDefault();const err=document.getElementById('err');err.textContent='Signing in...';const r=await fetch('/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:email.value,password:password.value})});const b=await r.json().catch(()=>({}));if(!r.ok){err.textContent=b?.error?.message||'Sign in failed';return}location.href='/'});
</script></body></html>\`;
}

export function appHtml(){
  return \`<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Revolt-X Shop</title>
<style>
:root{--bg:#f4f7fb;--panel:#fff;--ink:#132238;--muted:#718096;--line:#dfe7f1;--blue:#2563eb;--nav:#071425;--green:#0f9f6e;--orange:#d97706;--red:#dc2626}
*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;background:var(--bg);color:var(--ink)}
.layout{display:grid;grid-template-columns:250px 1fr;min-height:100vh}.side{background:linear-gradient(180deg,#071425,#0c2038);color:#dce8f6;padding:22px 14px;position:sticky;top:0;height:100vh;overflow:auto}
.brand{font-size:20px;font-weight:900;padding:8px 12px 20px}.brand b{color:#60a5fa}.nav button{display:flex;align-items:center;gap:10px;width:100%;padding:11px 12px;margin:3px 0;border:0;border-radius:10px;background:transparent;color:#b9cbe0;text-align:left;cursor:pointer;font-weight:700}.nav button:hover,.nav button.active{background:#183653;color:#fff}
.main{min-width:0}.top{height:68px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 26px;position:sticky;top:0;z-index:5}.switch{font-weight:800}.user{font-size:13px;color:var(--muted);display:flex;gap:12px;align-items:center}
.content{padding:24px}.panel{display:none}.panel.active{display:block}.title{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:18px}.title h1{margin:0;font-size:28px}.title p{margin:5px 0 0;color:var(--muted)}
.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:18px;box-shadow:0 8px 24px #1e3a5f0b}.kpi small{color:var(--muted);font-weight:700}.kpi strong{display:block;font-size:27px;margin-top:7px}.kpi em{font-style:normal;color:var(--green);font-size:12px}
.split{display:grid;grid-template-columns:1.1fr .9fr;gap:16px;margin-top:16px}.card h3{margin:0 0 14px}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:14px}.btn{border:0;border-radius:10px;padding:10px 13px;font-weight:800;cursor:pointer;background:#e8eef8;color:#20324c}.btn.primary{background:var(--blue);color:#fff}.btn.green{background:#dcfce7;color:#08764f}.btn.red{background:#fee2e2;color:#991b1b}.btn.sm{padding:7px 9px;font-size:12px}
table{width:100%;border-collapse:collapse;font-size:13px}th{text-align:left;color:#64748b;font-size:11px;text-transform:uppercase;letter-spacing:.05em;padding:10px;border-bottom:1px solid var(--line)}td{padding:11px 10px;border-bottom:1px solid #edf1f6;vertical-align:middle}.tag{padding:5px 8px;border-radius:999px;background:#eef2ff;color:#3730a3;font-size:11px;font-weight:800}.tag.ok{background:#dcfce7;color:#166534}.tag.warn{background:#fef3c7;color:#92400e}.tag.bad{background:#fee2e2;color:#991b1b}
.form{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.form .wide{grid-column:1/-1}.form input,.form select,.form textarea{width:100%;border:1px solid #d7e0eb;border-radius:10px;padding:10px;background:#fff;color:#18283f}.form textarea{min-height:70px;resize:vertical}.form label{font-size:12px;color:#607086;font-weight:700;display:block;margin-bottom:5px}.empty{color:var(--muted);padding:24px;text-align:center}.section-grid{display:grid;grid-template-columns:360px 1fr;gap:16px}.notice{padding:12px 14px;border-radius:10px;background:#eff6ff;color:#1e40af;font-size:13px;margin-bottom:12px}
.money{font-variant-numeric:tabular-nums;font-weight:800}.danger{color:var(--red)}.good{color:var(--green)}
@media(max-width:1100px){.grid{grid-template-columns:repeat(2,1fr)}.section-grid,.split{grid-template-columns:1fr}}
@media(max-width:760px){.layout{grid-template-columns:1fr}.side{height:auto;position:relative}.nav{display:flex;overflow:auto}.nav button{white-space:nowrap;width:auto}.top{position:relative}.content{padding:14px}.grid{grid-template-columns:1fr}.form{grid-template-columns:1fr}.form .wide{grid-column:auto}}
</style></head><body>
<div class="layout"><aside class="side"><div class="brand">REVOLT-X <b>SHOP</b></div><div class="nav" id="nav">
<button data-p="overview" class="active">Overview</button><button data-p="shops">Shops</button><button data-p="customers">Customers</button><button data-p="services">Services</button><button data-p="jobs">Jobs</button><button data-p="bookings">Bookings</button><button data-p="pos">Sales / POS</button><button data-p="inventory">Inventory</button><button data-p="payments">Payments</button><button data-p="finance">Finance</button><button data-p="reports">Reports</button><button data-p="settings">Settings</button>
</div></aside><main class="main"><header class="top"><div class="switch" id="orgName">Revolt-X Shop</div><div class="user"><span id="who"></span><button class="btn sm" id="logout">Sign out</button></div></header><div class="content">
<section id="overview" class="panel active"><div class="title"><div><h1>Business overview</h1><p>Live position across all shops and branches.</p></div><button class="btn primary" onclick="reload()">Refresh</button></div><div class="grid" id="kpis"></div><div class="split"><div class="card"><h3>Recent orders</h3><div id="recentOrders"></div></div><div class="card"><h3>Payment health</h3><div id="payHealth"></div></div></div></section>
<section id="shops" class="panel"><div class="title"><div><h1>Shops & branches</h1><p>Create and manage multiple businesses under one organisation.</p></div></div><div class="section-grid"><div class="card"><h3>Create shop</h3><form class="form" id="shopForm"><div class="wide"><label>Shop name</label><input name="name" required></div><div><label>Slug</label><input name="slug" placeholder="accra-salon" required></div><div><label>Business type</label><input name="businessType" value="general_service"></div><div><label>Phone</label><input name="phone"></div><div><label>Email</label><input name="email" type="email"></div><div class="wide"><label>Address</label><input name="address"></div><div class="wide"><button class="btn primary">Create shop</button></div></form></div><div class="card"><h3>All shops</h3><div id="shopTable"></div></div></div></section>
<section id="customers" class="panel"><div class="title"><div><h1>Customers</h1><p>Customer records, contact details and service relationship.</p></div></div><div class="section-grid"><div class="card"><h3>Add customer</h3><form class="form" id="customerForm"><div class="wide"><label>Shop</label><select name="shopId" class="shopSelect" required></select></div><div class="wide"><label>Name</label><input name="name" required></div><div><label>Phone</label><input name="phone"></div><div><label>Email</label><input name="email" type="email"></div><div class="wide"><label>Address</label><input name="address"></div><div><label>Type</label><select name="customerType"><option>retail</option><option>corporate</option><option>credit</option></select></div><div><label>Credit limit</label><input name="creditLimit" type="number" min="0" value="0"></div><div class="wide"><button class="btn primary">Save customer</button></div></form></div><div class="card"><h3>Customer directory</h3><div id="customerTable"></div></div></div></section>
<section id="services" class="panel"><div class="title"><div><h1>Services</h1><p>Configure the services each shop renders.</p></div></div><div class="section-grid"><div class="card"><h3>Create service</h3><form class="form" id="serviceForm"><div class="wide"><label>Shop</label><select name="shopId" class="shopSelect" required></select></div><div class="wide"><label>Service name</label><input name="name" required></div><div><label>Category</label><input name="category"></div><div><label>Price (GHS)</label><input name="price" type="number" step="0.01" required></div><div><label>Duration (minutes)</label><input name="durationMinutes" type="number" value="30"></div><div><label>Deposit %</label><input name="depositPercent" type="number" min="0" max="100" value="0"></div><div class="wide"><button class="btn primary">Create service</button></div></form></div><div class="card"><h3>Service catalogue</h3><div id="serviceTable"></div></div></div></section>
<section id="jobs" class="panel"><div class="title"><div><h1>Jobs & work orders</h1><p>Track service fulfilment from receipt to delivery.</p></div></div><div class="section-grid"><div class="card"><h3>New job</h3><form class="form" id="jobForm"><div class="wide"><label>Shop</label><select name="shopId" class="shopSelect" required></select></div><div class="wide"><label>Title</label><input name="title" required></div><div class="wide"><label>Customer</label><select name="customerId" class="customerSelect"><option value="">Walk-in / none</option></select></div><div><label>Labour cost</label><input name="labourCost" type="number" value="0"></div><div><label>Material cost</label><input name="materialCost" type="number" value="0"></div><div class="wide"><label>Notes</label><textarea name="notes"></textarea></div><div class="wide"><button class="btn primary">Create job</button></div></form></div><div class="card"><h3>Work queue</h3><div id="jobTable"></div></div></div></section>
<section id="bookings" class="panel"><div class="title"><div><h1>Bookings</h1><p>Appointments and scheduled services.</p></div></div><div class="section-grid"><div class="card"><h3>New booking</h3><form class="form" id="bookingForm"><div class="wide"><label>Shop</label><select name="shopId" class="shopSelect" required></select></div><div class="wide"><label>Customer name</label><input name="customerName" required></div><div><label>Phone</label><input name="phone"></div><div><label>Email</label><input name="email" type="email"></div><div class="wide"><label>Date & time</label><input name="bookedFor" type="datetime-local" required></div><div class="wide"><button class="btn primary">Create booking</button></div></form></div><div class="card"><h3>Booking schedule</h3><div id="bookingTable"></div></div></div></section>
<section id="pos" class="panel"><div class="title"><div><h1>Sales / POS</h1><p>Create invoices and accept payment.</p></div></div><div class="section-grid"><div class="card"><h3>Quick sale</h3><form class="form" id="orderForm"><div class="wide"><label>Shop</label><select name="shopId" class="shopSelect" required></select></div><div class="wide"><label>Customer</label><select name="customerId" class="customerSelect"><option value="">Walk-in</option></select></div><div><label>Item type</label><select name="itemType"><option value="service">Service</option><option value="product">Product</option><option value="other">Other</option></select></div><div><label>Description</label><input name="description" required></div><div><label>Quantity</label><input name="quantity" type="number" step="0.001" value="1"></div><div><label>Unit price</label><input name="unitPrice" type="number" step="0.01" required></div><div><label>Discount</label><input name="discount" type="number" step="0.01" value="0"></div><div><label>Tax</label><input name="tax" type="number" step="0.01" value="0"></div><div class="wide"><button class="btn primary">Create invoice</button></div></form></div><div class="card"><h3>Recent invoices</h3><div id="orderTable"></div></div></div></section>
<section id="inventory" class="panel"><div class="title"><div><h1>Inventory</h1><p>Products, stock levels and reorder monitoring.</p></div></div><div class="section-grid"><div class="card"><h3>Add product</h3><form class="form" id="productForm"><div class="wide"><label>Shop</label><select name="shopId" class="shopSelect" required></select></div><div><label>SKU</label><input name="sku"></div><div><label>Product name</label><input name="name" required></div><div><label>Cost price</label><input name="costPrice" type="number" value="0"></div><div><label>Selling price</label><input name="sellingPrice" type="number" required></div><div><label>Opening stock</label><input name="stockQuantity" type="number" value="0"></div><div><label>Reorder level</label><input name="reorderLevel" type="number" value="0"></div><div class="wide"><button class="btn primary">Add product</button></div></form></div><div class="card"><h3>Stock position</h3><div id="productTable"></div></div></div></section>
<section id="payments" class="panel"><div class="title"><div><h1>Payments</h1><p>Monitor cash, MoMo, card, bank and pending transactions.</p></div></div><div class="card"><div id="paymentTable"></div></div></section>
<section id="finance" class="panel"><div class="title"><div><h1>Finance</h1><p>Expenses, receipts and operating position.</p></div></div><div class="section-grid"><div class="card"><h3>Record expense</h3><form class="form" id="expenseForm"><div class="wide"><label>Shop</label><select name="shopId" class="shopSelect" required></select></div><div><label>Category</label><input name="category" required></div><div><label>Amount</label><input name="amount" type="number" step="0.01" required></div><div class="wide"><label>Description</label><input name="description" required></div><div><label>Method</label><select name="paymentMethod"><option>cash</option><option>bank_transfer</option><option>mobile_money</option><option>card</option></select></div><div><label>Reference</label><input name="reference"></div><div class="wide"><button class="btn primary">Record expense</button></div></form></div><div class="card"><h3>Recent expenses</h3><div id="expenseTable"></div></div></div></section>
<section id="reports" class="panel"><div class="title"><div><h1>Reports</h1><p>Management and finance summary.</p></div><button class="btn primary" onclick="loadReport()">Refresh report</button></div><div class="card" id="reportBox"><div class="empty">Open this page to load the finance report.</div></div></section>
<section id="settings" class="panel"><div class="title"><div><h1>Settings</h1><p>Workspace and customer storefront controls.</p></div></div><div class="card"><h3>Customer storefronts</h3><div class="notice">Every shop has a public service storefront at <b>/store/&lt;shop-slug&gt;</b>. Customers can view services and create bookings.</div><div id="storeLinks"></div></div></section>
</div></main></div>
<script>
let state={};
const money=n=>'GHS '+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{'content-type':'application/json',...(opt.headers||{})}});if(r.status===401){location.href='/login';throw new Error('Session expired')}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error?.message||'Request failed');return b}
function table(headers,rows){if(!rows.length)return '<div class="empty">No records yet.</div>';return '<table><thead><tr>'+headers.map(h=>'<th>'+h[0]+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+headers.map(h=>'<td>'+h[1](r)+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
function tag(v){const x=String(v||'');const c=/paid|successful|completed|active|delivered/i.test(x)?'ok':/pending|open|part|progress|booked|received/i.test(x)?'warn':/failed|cancel/i.test(x)?'bad':'';return '<span class="tag '+c+'">'+esc(x.replaceAll('_',' '))+'</span>'}
function fillSelects(){const opts=(state.shops||[]).map(s=>'<option value="'+s.id+'">'+esc(s.name)+'</option>').join('');document.querySelectorAll('.shopSelect').forEach(e=>e.innerHTML=opts||'<option value="">Create a shop first</option>');const cust='<option value="">Walk-in / none</option>'+(state.customers||[]).map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join('');document.querySelectorAll('.customerSelect').forEach(e=>e.innerHTML=cust)}
function render(){
  orgName.textContent=state.me?.organisation_name||'Revolt-X Shop';who.textContent=(state.me?.first_name||'')+' '+(state.me?.last_name||'')+' · '+(state.role||'');
  const s=state.stats||{};kpis.innerHTML=[
    ['Sales today',money(s.sales_today),'Across all shops'],['Payments today',money(s.payments_today),'Received'],['Open jobs',s.open_jobs||0,'Work in progress'],['Pending payments',s.pending_payments||0,'Needs monitoring']
  ].map(x=>'<div class="card kpi"><small>'+x[0]+'</small><strong>'+x[1]+'</strong><em>'+x[2]+'</em></div>').join('');
  recentOrders.innerHTML=table([['Invoice',r=>esc(r.order_no)],['Total',r=>'<span class="money">'+money(r.total)+'</span>'],['Status',r=>tag(r.status)]],(state.orders||[]).slice(0,8));
  const ok=(state.payments||[]).filter(p=>p.status==='successful').length,pen=(state.payments||[]).filter(p=>p.status==='pending').length,fail=(state.payments||[]).filter(p=>!['successful','pending'].includes(p.status)).length;
  payHealth.innerHTML='<div class="grid" style="grid-template-columns:repeat(3,1fr)"><div><b class="good">'+ok+'</b><br><small>Successful</small></div><div><b>'+pen+'</b><br><small>Pending</small></div><div><b class="danger">'+fail+'</b><br><small>Other</small></div></div>';
  shopTable.innerHTML=table([['Shop',r=>'<b>'+esc(r.name)+'</b><br><small>'+esc(r.business_type)+'</small>'],['Slug',r=>esc(r.slug)],['Status',r=>tag(r.status)],['Storefront',r=>'<a href="/store/'+encodeURIComponent(r.slug)+'" target="_blank">Open</a>']],state.shops||[]);
  customerTable.innerHTML=table([['Customer',r=>'<b>'+esc(r.name)+'</b>'],['Phone',r=>esc(r.phone)],['Email',r=>esc(r.email)],['Type',r=>tag(r.customer_type)]],state.customers||[]);
  serviceTable.innerHTML=table([['Service',r=>'<b>'+esc(r.name)+'</b>'],['Category',r=>esc(r.category)],['Price',r=>money(r.price)],['Duration',r=>esc(r.duration_minutes)+' min']],state.services||[]);
  jobTable.innerHTML=table([['Job',r=>'<b>'+esc(r.job_no)+'</b><br>'+esc(r.title)],['Status',r=>tag(r.status)],['Created',r=>new Date(r.created_at).toLocaleDateString()],['Action',r=>r.status!=='completed'?'<button class="btn sm green" onclick="completeJob(\\''+r.id+'\\')">Complete</button>':'']],state.jobs||[]);
  bookingTable.innerHTML=table([['Customer',r=>'<b>'+esc(r.customer_name)+'</b>'],['Date',r=>new Date(r.booked_for).toLocaleString()],['Phone',r=>esc(r.phone)],['Status',r=>tag(r.status)]],state.bookings||[]);
  orderTable.innerHTML=table([['Invoice',r=>'<b>'+esc(r.order_no)+'</b>'],['Total',r=>money(r.total)],['Paid',r=>money(r.amount_paid)],['Status',r=>tag(r.status)],['Action',r=>r.status!=='paid'?'<button class="btn sm green" onclick="manualPay(\\''+r.id+'\\','+Number(r.balance||r.total)+')">Pay</button>':'']],state.orders||[]);
  productTable.innerHTML=table([['Product',r=>'<b>'+esc(r.name)+'</b><br><small>'+esc(r.sku)+'</small>'],['Sell',r=>money(r.selling_price)],['Stock',r=>Number(r.stock_quantity)],['Level',r=>Number(r.stock_quantity)<=Number(r.reorder_level)?'<span class="tag bad">Reorder</span>':'<span class="tag ok">Healthy</span>']],state.products||[]);
  paymentTable.innerHTML=table([['Reference',r=>'<b>'+esc(r.reference)+'</b><br><small>'+esc(r.provider)+'</small>'],['Method',r=>esc(r.method).replaceAll('_',' ')],['Amount',r=>money(r.amount)],['Status',r=>tag(r.status)],['Created',r=>new Date(r.created_at).toLocaleString()],['Action',r=>r.provider==='paystack'&&r.status==='pending'?'<button class="btn sm" onclick="verifyPay(\\''+esc(r.reference)+'\\')">Verify</button>':'']],state.payments||[]);
  expenseTable.innerHTML=table([['Category',r=>'<b>'+esc(r.category)+'</b>'],['Description',r=>esc(r.description)],['Amount',r=>money(r.amount)],['Date',r=>esc(r.expense_date)]],state.expenses||[]);
  storeLinks.innerHTML=(state.shops||[]).map(s=>'<div style="padding:10px 0;border-bottom:1px solid #edf1f6"><b>'+esc(s.name)+'</b><br><a href="/store/'+encodeURIComponent(s.slug)+'" target="_blank">'+location.origin+'/store/'+esc(s.slug)+'</a></div>').join('')||'<div class="empty">Create a shop to generate a storefront.</div>';
  fillSelects()
}
async function reload(){state=await api('/api/bootstrap');render()}
function bindForm(id,url,map){document.getElementById(id).addEventListener('submit',async e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.target));try{await api(url,{method:'POST',body:JSON.stringify(map(fd))});e.target.reset();await reload()}catch(x){alert(x.message)}})}
bindForm('shopForm','/api/shops',x=>x);
bindForm('customerForm','/api/customers',x=>({...x,creditLimit:Number(x.creditLimit||0)}));
bindForm('serviceForm','/api/services',x=>({...x,price:Number(x.price),durationMinutes:Number(x.durationMinutes||30),depositPercent:Number(x.depositPercent||0)}));
bindForm('jobForm','/api/jobs',x=>({...x,customerId:x.customerId||undefined,labourCost:Number(x.labourCost||0),materialCost:Number(x.materialCost||0)}));
bindForm('bookingForm','/api/bookings',x=>({...x,bookedFor:new Date(x.bookedFor).toISOString()}));
bindForm('productForm','/api/products',x=>({...x,costPrice:Number(x.costPrice||0),sellingPrice:Number(x.sellingPrice),stockQuantity:Number(x.stockQuantity||0),reorderLevel:Number(x.reorderLevel||0)}));
bindForm('expenseForm','/api/expenses',x=>({...x,amount:Number(x.amount)}));
bindForm('orderForm','/api/orders',x=>({shopId:x.shopId,customerId:x.customerId||undefined,discount:Number(x.discount||0),tax:Number(x.tax||0),lines:[{itemType:x.itemType,description:x.description,quantity:Number(x.quantity||1),unitPrice:Number(x.unitPrice)}]}));
async function completeJob(id){try{await api('/api/jobs/'+id+'/status',{method:'PATCH',body:JSON.stringify({status:'completed'})});await reload()}catch(e){alert(e.message)}}
async function manualPay(id,balance){const amount=Number(prompt('Payment amount',String(balance)));if(!amount)return;const method=prompt('Method: cash, bank_transfer, credit or other','cash')||'cash';try{await api('/api/orders/'+id+'/payments/manual',{method:'POST',body:JSON.stringify({amount,method})});await reload()}catch(e){alert(e.message)}}
async function verifyPay(ref){try{await api('/api/payments/'+encodeURIComponent(ref)+'/verify');await reload()}catch(e){alert(e.message)}}
async function loadReport(){try{const r=await api('/api/reports/finance');reportBox.innerHTML='<h3>Payment position</h3>'+table([['Method',x=>esc(x.method)],['Status',x=>tag(x.status)],['Transactions',x=>x.transactions],['Amount',x=>money(x.amount)]],r.payments||[])+'<h3 style="margin-top:24px">Expense categories</h3>'+table([['Category',x=>esc(x.category)],['Amount',x=>money(x.amount)]],r.expenses||[])+'<h3 style="margin-top:24px">Ledger summary</h3>'+table([['Account',x=>esc(x.account_code)+' '+esc(x.account_name)],['Debit',x=>money(x.debit)],['Credit',x=>money(x.credit)]],r.ledger||[])}catch(e){alert(e.message)}}
nav.addEventListener('click',e=>{const b=e.target.closest('button[data-p]');if(!b)return;document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));document.getElementById(b.dataset.p).classList.add('active');if(b.dataset.p==='reports')loadReport()});
logout.onclick=async()=>{await fetch('/auth/logout',{method:'POST'});location.href='/login'};
reload().catch(e=>{if(!String(e.message).includes('Session'))alert(e.message)});
</script></body></html>\`;
}

export function storefrontHtml(slug:string){
  const safe=JSON.stringify(slug);
  return \`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Shop</title>
<style>*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui;background:#f6f8fb;color:#17243a}.hero{background:linear-gradient(135deg,#071425,#123b67);color:#fff;padding:50px 7vw}.hero h1{font-size:42px;margin:8px 0}.wrap{max-width:1100px;margin:0 auto;padding:28px 20px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card{background:#fff;border:1px solid #e0e7ef;border-radius:16px;padding:18px}.price{font-size:22px;font-weight:900;color:#2563eb}.book{display:grid;grid-template-columns:1fr 1fr;gap:12px}.book input,.book select,.book textarea{width:100%;padding:11px;border:1px solid #d5deea;border-radius:10px}.wide{grid-column:1/-1}button{background:#2563eb;color:white;border:0;padding:12px 16px;border-radius:10px;font-weight:800;cursor:pointer}@media(max-width:760px){.grid{grid-template-columns:1fr}.book{grid-template-columns:1fr}.wide{grid-column:auto}}</style></head><body>
<div class="hero"><div>Powered by Revolt-X Shop</div><h1 id="name">Loading shop...</h1><div id="contact"></div></div><div class="wrap"><h2>Services</h2><div class="grid" id="services"></div><h2 style="margin-top:34px">Book a service</h2><div class="card"><form id="book" class="book"><div><label>Name</label><input name="customerName" required></div><div><label>Phone</label><input name="phone" required></div><div><label>Email</label><input name="email" type="email"></div><div><label>Service</label><select name="serviceId" id="svc"></select></div><div class="wide"><label>Date & time</label><input name="bookedFor" type="datetime-local" required></div><div class="wide"><label>Notes</label><textarea name="notes"></textarea></div><div class="wide"><button>Confirm booking</button></div></form><div id="msg"></div></div></div>
<script>const slug=\${safe};let data;fetch('/api/public/store/'+encodeURIComponent(slug)).then(r=>r.json()).then(x=>{data=x;name.textContent=x.shop.name;contact.textContent=[x.shop.phone,x.shop.email,x.shop.address].filter(Boolean).join(' · ');services.innerHTML=x.services.map(s=>'<div class="card"><b>'+s.name+'</b><p>'+(s.description||'')+'</p><div class="price">GHS '+Number(s.price).toFixed(2)+'</div><small>'+s.duration_minutes+' minutes</small></div>').join('')||'<p>No services published yet.</p>';svc.innerHTML='<option value="">Select service</option>'+x.services.map(s=>'<option value="'+s.id+'">'+s.name+'</option>').join('')});book.onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(book));f.bookedFor=new Date(f.bookedFor).toISOString();if(!f.serviceId)delete f.serviceId;const r=await fetch('/api/public/store/'+encodeURIComponent(slug)+'/bookings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(f)});const b=await r.json();msg.textContent=r.ok?'Booking confirmed. Reference: '+b.id:(b?.error?.message||'Booking failed');if(r.ok)book.reset()}</script></body></html>\`;
}
