export const admissionsFrontend=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Revolt-X School Admissions</title>
<style>
:root{--bg:#071018;--panel:#0e1e29;--line:#203844;--text:#f4f8fa;--muted:#90a8b5;--green:#45ddb2;--blue:#48a9ff}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px Arial,sans-serif}.wrap{max-width:980px;margin:auto;padding:24px}.hero{padding:30px 0}.brand{font-size:22px;font-weight:900}.brand span{color:var(--green)}.panel{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:20px;margin-bottom:14px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.muted{color:var(--muted)}input,select,textarea{width:100%;padding:11px;margin:6px 0 12px;background:#07141d;border:1px solid var(--line);border-radius:8px;color:white}.primary,.ghost{padding:10px 14px;border-radius:9px;cursor:pointer}.primary{border:0;background:linear-gradient(90deg,var(--green),var(--blue));font-weight:800;color:#041018}.ghost{border:1px solid var(--line);background:transparent;color:white}.hide{display:none}.success{padding:14px;border-left:3px solid var(--green);background:#0d251f;border-radius:8px}.error{color:#ffb0bb}@media(max-width:700px){.grid{grid-template-columns:1fr}}
</style></head><body><div class="wrap">
<div class="hero"><div class="brand"><span>RX</span> REVOLT-X SCHOOL</div><h1 id="schoolName">Admissions</h1><p id="schoolInfo" class="muted"></p></div>
<div class="grid"><section class="panel"><h2>Apply for Admission</h2><p class="muted">Submit an application for Primary or JHS admission.</p>
<label>First name</label><input id="firstName"><label>Middle name</label><input id="middleName"><label>Last name</label><input id="lastName">
<label>Sex</label><select id="sex"><option value="">Not specified</option><option value="male">Male</option><option value="female">Female</option></select>
<label>Date of birth</label><input id="dob" type="date"><label>Requested grade</label><select id="grade"></select><label>Previous school</label><input id="previousSchool">
<h3>Parent / Guardian</h3><label>First name</label><input id="gFirst"><label>Last name</label><input id="gLast"><label>Phone</label><input id="gPhone"><label>Email</label><input id="gEmail" type="email"><label>Relationship</label><input id="gRelationship" placeholder="Mother, Father, Guardian"><label>Address</label><textarea id="address"></textarea><label>Notes</label><textarea id="notes"></textarea>
<button id="submit" class="primary" style="width:100%">Submit application</button><p id="applyError" class="error"></p><div id="success" class="success hide"></div>
</section>
<section><div class="panel"><h2>Check Application Status</h2><label>Application number</label><input id="applicationNo"><label>Guardian phone</label><input id="statusPhone"><button id="check" class="ghost" style="width:100%">Check status</button><div id="statusOut"></div></div><div class="panel"><h3>What happens next?</h3><p class="muted">The school reviews the application, may contact the guardian, and then marks it approved, waitlisted or declined. Approved applications can be converted into student records by the school administrator.</p></div></section>
</div></div>
<script>
(function(){
function E(i){return document.getElementById(i)}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
async function raw(path,opt){opt=opt||{};opt.headers=Object.assign({'content-type':'application/json'},opt.headers||{});var r=await fetch(path,opt),j=null;try{j=await r.json()}catch(e){}if(!r.ok)throw Error(j&&j.error&&j.error.message?j.error.message:'Request failed');return j}
async function boot(){var x=await raw('/api/public/school');E('schoolName').textContent=x.school.school_name+' Admissions';E('schoolInfo').textContent=[x.school.motto,x.school.phone,x.school.email,x.school.address].filter(Boolean).join(' • ');E('grade').innerHTML=x.grades.map(function(g){return'<option value="'+g.code+'">'+esc(g.name)+'</option>'}).join('')}
E('submit').onclick=async function(){E('applyError').textContent='';E('success').classList.add('hide');try{var b={firstName:E('firstName').value,middleName:E('middleName').value||undefined,lastName:E('lastName').value,sex:E('sex').value||undefined,dateOfBirth:E('dob').value||undefined,requestedGradeCode:E('grade').value,previousSchool:E('previousSchool').value||undefined,guardianFirstName:E('gFirst').value,guardianLastName:E('gLast').value,guardianPhone:E('gPhone').value,guardianEmail:E('gEmail').value||undefined,guardianRelationship:E('gRelationship').value,address:E('address').value||undefined,notes:E('notes').value||undefined};var x=await raw('/api/public/admissions',{method:'POST',body:JSON.stringify(b)});E('success').innerHTML='<b>Application submitted.</b><br>Application number: <b>'+esc(x.applicationNo)+'</b><br>Keep this number to check the status.';E('success').classList.remove('hide');E('applicationNo').value=x.applicationNo;E('statusPhone').value=b.guardianPhone}catch(e){E('applyError').textContent=e.message}}
E('check').onclick=async function(){try{var x=await raw('/api/public/admissions/status?applicationNo='+encodeURIComponent(E('applicationNo').value)+'&phone='+encodeURIComponent(E('statusPhone').value));E('statusOut').innerHTML='<div class="success" style="margin-top:12px"><b>'+esc(x.applicationNo)+'</b><br>Status: <b>'+esc(x.status)+'</b><br>'+esc(x.reviewNote||'')+'</div>'}catch(e){E('statusOut').innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
boot().catch(function(e){E('schoolInfo').textContent=e.message});
})();
</script></body></html>`;
