import { applySchoolDesign } from './school-design.js';

export const admissionsFrontend=applySchoolDesign(`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Revolt-X School Admissions</title>
<style>
:root{--bg:#071018;--panel:#0e1e29;--line:#203844;--text:#f4f8fa;--muted:#90a8b5;--green:#45ddb2;--blue:#48a9ff}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px Arial,sans-serif}.wrap{max-width:980px;margin:auto;padding:24px}.hero{padding:30px 0}.brand{font-size:22px;font-weight:900}.brand span{color:var(--green)}.panel{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:20px;margin-bottom:14px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.muted{color:var(--muted)}input,select,textarea{width:100%;padding:11px;margin:6px 0 12px;background:#f7f9fb;border:1px solid var(--line);border-radius:8px;color:var(--text)}.primary,.ghost{padding:10px 14px;border-radius:9px;cursor:pointer}.primary{border:0;background:linear-gradient(90deg,var(--green),var(--blue));font-weight:800;color:#041018}.ghost{border:1px solid var(--line);background:transparent;color:var(--text)}.hide{display:none}.success{padding:14px;border-left:3px solid var(--green);background:#edf4ef;border-radius:8px}.error{color:#a63b4e}@media(max-width:700px){.grid{grid-template-columns:1fr}}
</style></head><body><div class="wrap">
<div class="hero"><div class="rx-admission-intro"><div class="brand"><span>RX</span><div class="rx-brand-copy">Revolt-X School<small>Admissions</small></div></div><div class="rx-public-links"><a href="/login">Staff sign in</a><a href="/parent">Parent portal</a></div></div><div class="rx-kicker">A new chapter starts here</div><h1 id="schoolName">Admissions</h1><p id="schoolInfo" class="muted"></p></div>
<div class="grid"><section class="panel"><div class="rx-kicker">Student application</div><h2>Apply for Admission</h2><p class="muted">Submit an application for Primary or JHS admission.</p>
<label>First name</label><input id="firstName"><label>Middle name</label><input id="middleName"><label>Last name</label><input id="lastName">
<label>Sex</label><select id="sex"><option value="">Not specified</option><option value="male">Male</option><option value="female">Female</option></select>
<label>Date of birth</label><input id="dob" type="date"><label>Requested grade</label><select id="grade"></select><label>Previous school</label><input id="previousSchool">
<h3>Parent / Guardian</h3><label>First name</label><input id="gFirst"><label>Last name</label><input id="gLast"><label>Primary phone</label><input id="gPhone"><label>Alternate phone</label><input id="gAltPhone"><label>Email <span class="muted">(optional)</span></label><input id="gEmail" type="email" placeholder="Used for report cards, fee notices and school alerts"><label>Relationship</label><input id="gRelationship" placeholder="Mother, Father, Guardian"><label>Address</label><textarea id="address"></textarea><h3>Emergency Contact</h3><label>Name</label><input id="emergencyName"><label>Phone</label><input id="emergencyPhone"><label>Notes</label><textarea id="notes"></textarea>
<button id="submit" class="primary" style="width:100%">Submit application</button><p id="applyError" class="error"></p><div id="success" class="success hide"></div>
</section>
<section><div class="panel"><div class="rx-kicker">Already applied?</div><h2>Track Admission Application</h2><p class="muted">Enter the application reference you received after submitting. This is not a Student ID. A Student ID is generated only after approval and enrolment.</p><label>Application reference</label><input id="applicationNo" placeholder="ADM-2026-XXXXXX"><button id="check" class="ghost" style="width:100%">Track application</button><div id="statusOut"></div></div><div class="panel"><h3>What happens next?</h3><p class="muted">The school reviews the application, may contact the guardian, and then marks it approved, waitlisted or declined. Approved applications can be converted into student records by the school administrator.</p></div></section>
</div></div>
<script>
(function(){
function E(i){return document.getElementById(i)}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
async function raw(path,opt){opt=opt||{};var baseHeaders=opt.body==null?{}:{'content-type':'application/json'};opt.headers=Object.assign(baseHeaders,opt.headers||{});var r=await fetch(path,opt),j=null;try{j=await r.json()}catch(e){}if(!r.ok)throw Error(j&&j.error&&j.error.message?j.error.message:'Request failed');return j}
async function boot(){var x=await raw('/api/public/school');E('schoolName').textContent=x.school.school_name+' Admissions';E('schoolInfo').textContent=[x.school.motto,x.school.phone,x.school.email,x.school.address].filter(Boolean).join(' • ');E('grade').innerHTML=x.grades.map(function(g){return'<option value="'+g.code+'">'+esc(g.name)+'</option>'}).join('')}
E('submit').onclick=async function(){E('applyError').textContent='';E('success').classList.add('hide');try{var b={firstName:E('firstName').value,middleName:E('middleName').value||undefined,lastName:E('lastName').value,sex:E('sex').value||undefined,dateOfBirth:E('dob').value||undefined,requestedGradeCode:E('grade').value,previousSchool:E('previousSchool').value||undefined,guardianFirstName:E('gFirst').value,guardianLastName:E('gLast').value,guardianPhone:E('gPhone').value,guardianAltPhone:E('gAltPhone').value||undefined,guardianEmail:E('gEmail').value||undefined,guardianRelationship:E('gRelationship').value,address:E('address').value||undefined,emergencyContactName:E('emergencyName').value||undefined,emergencyContactPhone:E('emergencyPhone').value||undefined,notes:E('notes').value||undefined};var x=await raw('/api/public/admissions',{method:'POST',body:JSON.stringify(b)});E('success').innerHTML='<b>Application submitted successfully.</b><br>Application number: <b>'+esc(x.applicationNo)+'</b><br>Keep this application reference. It is only for tracking your application. Your Student ID will be generated after the school approves and enrols the applicant. The school can also contact the guardian by email, SMS or WhatsApp when those channels are enabled.';E('success').classList.remove('hide');E('applicationNo').value=x.applicationNo}catch(e){E('applyError').textContent=e.message}}
E('check').onclick=async function(){try{var ref=E('applicationNo').value.trim();if(!ref)throw Error('Enter your admission reference');var x=await raw('/api/public/admissions/status?applicationNo='+encodeURIComponent(ref));E('statusOut').innerHTML='<div class="success" style="margin-top:12px"><b>'+esc(x.applicationNo)+'</b><br>Current status: <b>'+esc(x.status.replace('_',' '))+'</b><br><span class="muted">Last updated '+esc(new Date(x.updatedAt).toLocaleString())+'</span></div>'+(x.history&&x.history.length?'<div class="panel" style="margin-top:12px"><h3>Application Progress</h3>'+x.history.map(function(h){return'<div style="padding:8px 0;border-bottom:1px solid #203844"><b>'+esc(h.new_status.replace('_',' '))+'</b><div class="muted">'+esc(new Date(h.created_at).toLocaleString())+'</div></div>'}).join('')+'</div>':'')}catch(e){E('statusOut').innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
boot().catch(function(e){E('schoolInfo').textContent=e.message});
})();
</script></body></html>`,'admissions');
