export const parentFrontend=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Revolt-X School Parent Portal</title>
<style>
:root{--bg:#071018;--panel:#0e1e29;--line:#203844;--text:#f4f8fa;--muted:#90a8b5;--green:#45ddb2;--blue:#48a9ff;--red:#ff7482}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px Arial,sans-serif}.wrap{max-width:1100px;margin:auto;padding:22px}.brand{font-size:20px;font-weight:900;margin-bottom:22px}.brand span{color:var(--green)}.panel{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px;margin-bottom:12px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.stat b{font-size:25px;display:block;margin-top:6px}.muted{color:var(--muted)}input,select{width:100%;padding:11px;margin:6px 0 12px;background:#07141d;border:1px solid var(--line);border-radius:8px;color:white}.primary,.ghost{padding:10px 14px;border-radius:9px;cursor:pointer}.primary{border:0;background:linear-gradient(90deg,var(--green),var(--blue));font-weight:800;color:#041018}.ghost{border:1px solid var(--line);background:transparent;color:white}.top{display:flex;justify-content:space-between;gap:12px;align-items:center}.hide{display:none}.badge{display:inline-block;padding:4px 7px;border-radius:10px;background:#15342b;color:#73e6c6;font-size:11px}.table{overflow:auto}.table table{width:100%;border-collapse:collapse}.table td,.table th{padding:9px;border-bottom:1px solid var(--line);text-align:left}.table th{color:var(--muted);font-size:11px;text-transform:uppercase}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.tabs button{padding:8px 10px}.error{color:#ffb0bb}.child{cursor:pointer}.child:hover{border-color:#3a6578}@media(max-width:760px){.grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}}
</style></head><body>
<div class="wrap">
<div class="brand"><span>RX</span> REVOLT-X SCHOOL <span class="muted">Parent Portal</span></div>
<section id="login" class="panel" style="max-width:480px;margin:70px auto">
<h2>Parent / Guardian Sign In</h2><p class="muted">Use your phone number, a linked student admission number and your school-issued PIN.</p>
<label>Phone number</label><input id="phone"><label>Student admission number</label><input id="admission"><label>PIN</label><input id="pin" type="password" maxlength="6">
<button id="signin" class="primary" style="width:100%">Sign in</button><p id="loginError" class="error"></p>
</section>
<section id="portal" class="hide"><div class="top"><div><h2 id="guardianName"></h2><div class="muted" id="schoolName"></div></div><button id="logout" class="ghost">Sign out</button></div><div id="children" class="grid"></div><div id="studentArea"></div></section>
</div>
<script>
(function(){
var token=sessionStorage.getItem('rx_parent_token')||'',me=null,currentStudent=null;
function E(i){return document.getElementById(i)}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
async function raw(path,opt){opt=opt||{};opt.headers=Object.assign({'content-type':'application/json'},opt.headers||{},token?{authorization:'Bearer '+token}:{});var r=await fetch(path,opt),j=null;try{j=await r.json()}catch(e){}if(!r.ok)throw Error(j&&j.error&&j.error.message?j.error.message:'Request failed');return j}
function table(rows,cols){if(!rows||!rows.length)return'<p class="muted">No records yet.</p>';return'<div class="table"><table><thead><tr>'+cols.map(function(c){return'<th>'+esc(c.label||c.key)+'</th>'}).join('')+'</tr></thead><tbody>'+rows.map(function(r){return'<tr>'+cols.map(function(c){var v=c.render?c.render(r):r[c.key];return'<td>'+String(v==null?'':v)+'</td>'}).join('')+'</tr>'}).join('')+'</tbody></table></div>'}
async function boot(){if(!token)return;try{me=await raw('/api/parent/me');showPortal()}catch(e){sessionStorage.removeItem('rx_parent_token');token=''}}
function showPortal(){E('login').classList.add('hide');E('portal').classList.remove('hide');E('guardianName').textContent=me.guardian.first_name+' '+me.guardian.last_name;E('schoolName').textContent=me.school.school_name;E('children').innerHTML=me.students.map(function(s){return'<div class="panel child" data-student="'+s.id+'"><b>'+esc(s.first_name+' '+s.last_name)+'</b><div class="muted">'+esc(s.admission_no)+'</div><div>'+esc(s.classroom_name||'Not currently enrolled')+'</div></div>'}).join('');E('children').onclick=function(e){var c=e.target.closest('[data-student]');if(c)loadStudent(c.dataset.student)};if(me.students[0])loadStudent(me.students[0].id)}
async function loadStudent(id){currentStudent=id;var d=await raw('/api/parent/students/'+id+'/dashboard');E('studentArea').innerHTML='<div class="panel"><div class="top"><div><h2>'+esc(d.student.first_name+' '+d.student.last_name)+'</h2><div class="muted">'+esc(d.student.admission_no)+' • '+esc(d.student.classroom_name||'No class')+'</div></div></div><div class="grid" style="margin-top:12px"><div class="panel stat"><span class="muted">Outstanding fees</span><b>GHS '+Number(d.fees.outstanding||0).toFixed(2)+'</b></div><div class="panel stat"><span class="muted">Present days</span><b>'+esc(d.attendance.present||0)+'</b></div><div class="panel stat"><span class="muted">Absent days</span><b>'+esc(d.attendance.absent||0)+'</b></div></div></div><div class="tabs"><button class="ghost" id="tabHomework">Homework</button><button class="ghost" id="tabFees">Fees & Payments</button><button class="ghost" id="tabReports">Report Card</button><button class="ghost" id="tabNews">Announcements</button></div><div id="detail"></div>';E('tabHomework').onclick=function(){E('detail').innerHTML='<div class="panel"><h3>Homework</h3>'+table(d.homework,[{key:'subject_name',label:'Subject'},{key:'title'},{key:'due_at',label:'Due',render:function(r){return esc(r.due_at?new Date(r.due_at).toLocaleString():'') }},{key:'status'}])+'</div>'};E('tabFees').onclick=async function(){var x=await raw('/api/parent/students/'+id+'/fees');E('detail').innerHTML='<div class="panel"><h3>Fee Statement</h3>'+table(x.items,[{key:'fee_name',label:'Fee'},{key:'due'},{key:'paid'},{key:'balance'},{key:'status'}])+'<h3 style="margin-top:18px">Payments</h3>'+table(x.payments,[{key:'paid_at',label:'Date',render:function(r){return esc(new Date(r.paid_at).toLocaleString())}},{key:'amount'},{key:'payment_method',label:'Method'},{key:'reference'}])+'</div>'};E('tabReports').onclick=async function(){var x=await raw('/api/parent/students/'+id+'/latest-report');E('detail').innerHTML='<div class="panel"><h3>'+esc(x.term?x.term.name:'Latest Report')+'</h3>'+table(x.subjects,[{key:'subject_name',label:'Subject'},{key:'percentage',label:'Average %'},{key:'grade'},{key:'remark'}])+'<p><b>Teacher comment:</b> '+esc(x.comments&&x.comments.class_teacher_comment||'')+'</p><p><b>Headteacher comment:</b> '+esc(x.comments&&x.comments.headteacher_comment||'')+'</p></div>'};E('tabNews').onclick=function(){E('detail').innerHTML='<div class="panel"><h3>Announcements</h3>'+table(d.announcements,[{key:'title'},{key:'body'},{key:'published_at',label:'Published',render:function(r){return esc(r.published_at?new Date(r.published_at).toLocaleDateString():'')}}])+'</div>'};E('tabHomework').click()}
E('signin').onclick=async function(){E('loginError').textContent='';try{var x=await raw('/api/parent/login',{method:'POST',body:JSON.stringify({phone:E('phone').value,admissionNo:E('admission').value,pin:E('pin').value})});token=x.token;sessionStorage.setItem('rx_parent_token',token);me=await raw('/api/parent/me');showPortal()}catch(e){E('loginError').textContent=e.message}};
E('logout').onclick=async function(){try{await raw('/api/parent/logout',{method:'POST',body:'{}'})}catch(e){}sessionStorage.removeItem('rx_parent_token');location.reload()};
boot();
})();
</script></body></html>`;
