export const parentFrontend=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Revolt-X School Parent Portal</title>
<style>
:root{--bg:#071018;--panel:#0e1e29;--line:#203844;--text:#f4f8fa;--muted:#90a8b5;--green:#45ddb2;--blue:#48a9ff;--red:#ff7482}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px Arial,sans-serif}.wrap{max-width:1100px;margin:auto;padding:22px}.brand{font-size:20px;font-weight:900;margin-bottom:22px}.brand span{color:var(--green)}.panel{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px;margin-bottom:12px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.stat b{font-size:25px;display:block;margin-top:6px}.muted{color:var(--muted)}input,select,textarea{width:100%;padding:11px;margin:6px 0 12px;background:#07141d;border:1px solid var(--line);border-radius:8px;color:white}.primary,.ghost{padding:10px 14px;border-radius:9px;cursor:pointer}.primary{border:0;background:linear-gradient(90deg,var(--green),var(--blue));font-weight:800;color:#041018}.ghost{border:1px solid var(--line);background:transparent;color:white}.top{display:flex;justify-content:space-between;gap:12px;align-items:center}.hide{display:none}.toast{position:fixed;right:18px;bottom:18px;background:#102a24;border:1px solid #2c6d5c;border-radius:9px;padding:11px 14px;z-index:40;max-width:min(420px,90vw)}.badge{display:inline-block;padding:4px 7px;border-radius:10px;background:#15342b;color:#73e6c6;font-size:11px}.badge.warn{background:#382a14;color:#ffd273}.badge.red{background:#3a181c;color:#ff9eaa}.badge.gray{background:#253039;color:#bec9ce}.badge.info{background:#123449;color:#80c9ff}.table{overflow:auto}.table table{width:100%;border-collapse:collapse}.table td,.table th{padding:9px;border-bottom:1px solid var(--line);text-align:left}.table th{color:var(--muted);font-size:11px;text-transform:uppercase}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.tabs button{padding:8px 10px}.error{color:#ffb0bb}.child{cursor:pointer}.child:hover{border-color:#3a6578}
.homework-card{border:1px solid #2c4857;border-radius:14px;padding:16px;margin:10px 0;background:linear-gradient(135deg,#0b1c27,#102a2c)}.homework-card h3{margin:0 0 5px}.homework-meta{display:flex;gap:8px;flex-wrap:wrap;margin:8px 0}.homework-instructions{white-space:pre-wrap;background:#08151d;border:1px solid #203844;border-radius:10px;padding:12px;line-height:1.55}.homework-result{margin-top:10px;padding:10px;border-radius:10px;background:#0c2330}
.pay-actions{display:flex;gap:6px;flex-wrap:wrap}.pay-card,.pay-momo{border:0;border-radius:9px;padding:8px 10px;font-weight:800;cursor:pointer}.pay-card{background:#48a9ff;color:#041018}.pay-momo{background:#ffd84d;color:#201b00}
.parent-report{background:#fff;color:#172027;border-radius:18px;overflow:hidden;box-shadow:0 14px 45px #0005}.parent-report-head{background:linear-gradient(120deg,#0f705e,#2678d8);color:#fff;padding:22px;display:flex;justify-content:space-between;gap:18px;align-items:center}.parent-report-head h2{margin:0;font-size:24px}.parent-report-head p{margin:4px 0 0;color:#d7f7ef}.parent-report-term{text-align:right}.parent-report-term b{display:block;font-size:16px}.parent-report-body{padding:20px}.parent-report-student{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:14px}.parent-report-student div,.parent-report-metrics div{border-radius:10px;padding:10px;background:#eef7f8}.parent-report-student span,.parent-report-metrics span{display:block;font-size:10px;text-transform:uppercase;color:#61747d}.parent-report-metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-bottom:18px}.parent-report-metrics b{font-size:19px}.parent-report table{color:#172027}.parent-report .table th{background:#e7f4f2;color:#315b5a}.report-comments-parent{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:16px}.report-comments-parent>div{padding:14px;border-radius:12px;background:#f1f6fb;border-left:5px solid #48a9ff}.report-comments-parent>div:first-child{border-left-color:#45ddb2}.report-comments-parent h4{margin:0 0 6px;color:#315b5a}.report-footer-parent{text-align:center;padding:12px;color:#667780;font-size:10px}
@media(max-width:760px){.grid,.parent-report-student,.parent-report-metrics,.report-comments-parent{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}.parent-report-head{align-items:flex-start;flex-direction:column}.parent-report-term{text-align:left}}
@media print{body{background:#fff}.brand,#login,#children,.tabs,#logout,.pay-actions{display:none!important}.wrap{max-width:none;padding:0}.parent-report{box-shadow:none;border-radius:0}.parent-report-head{-webkit-print-color-adjust:exact;print-color-adjust:exact}.parent-report-body{padding:10mm}}
</style></head><body>
<div class="wrap">
<div class="brand"><span>RX</span> REVOLT-X SCHOOL <span class="muted">Parent Portal</span></div>
<section id="login" class="panel" style="max-width:480px;margin:70px auto">
<h2>Parent / Guardian Sign In</h2><p class="muted">Use your phone number, a linked student admission number and your school-issued PIN.</p>
<label>Phone number</label><input id="phone"><label>Student admission number</label><input id="admission"><label>PIN</label><input id="pin" type="password" maxlength="6">
<button id="signin" class="primary" style="width:100%">Sign in</button><p id="loginError" class="error"></p>
</section>
<section id="portal" class="hide"><div class="top"><div><h2 id="guardianName"></h2><div class="muted" id="schoolName"></div></div><button id="logout" class="ghost">Sign out</button></div><div id="children" class="grid"></div><div id="studentArea"></div></section>
</div><div id="toast" class="toast hide"></div>
<script>
(function(){
var token=sessionStorage.getItem('rx_parent_token')||'',me=null,currentStudent=null;
function E(i){return document.getElementById(i)}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}function statusBadge(v){var s=String(v||'not_submitted'),cls=/late/.test(s)?'warn':/not_submitted/.test(s)?'gray':/submitted/.test(s)?'info':/graded/.test(s)?'':'gray';return'<span class="badge '+cls+'">'+esc(s.replace(/_/g,' '))+'</span>'}function toast(m,b){var t=E('toast');if(!t)return;t.textContent=m;t.style.borderColor=b?'#71323a':'#2c6d5c';t.classList.remove('hide');setTimeout(function(){t.classList.add('hide')},3200)}
async function raw(path,opt){opt=opt||{};var method=String(opt.method||'GET').toUpperCase();opt.headers=Object.assign({'content-type':'application/json'},opt.headers||{},token?{authorization:'Bearer '+token}:{});var r=await fetch(path,opt),j=null;try{j=await r.json()}catch(e){}if(!r.ok){var msg=j&&j.error&&j.error.message?j.error.message:'Request failed ('+r.status+')';if(j&&j.error&&j.error.errorId)msg+=' • Error ref: '+j.error.errorId;toast(msg,true);throw Error(msg)}if(method!=='GET'&&method!=='HEAD'&&!opt.silent){var msgOk=path.indexOf('/login')>=0?'Signed in successfully':path.indexOf('academic-statement')>=0?'Request submitted successfully':path.indexOf('/logout')>=0?'Signed out successfully':'Action completed successfully';toast(msgOk,false)}return j}
function table(rows,cols,act){if(!rows||!rows.length)return'<p class="muted">No records yet.</p>';return'<div class="table"><table><thead><tr>'+cols.map(function(c){return'<th>'+esc(c.label||c.key)+'</th>'}).join('')+(act?'<th>Actions</th>':'')+'</tr></thead><tbody>'+rows.map(function(r){return'<tr>'+cols.map(function(c){var v=c.render?c.render(r):r[c.key];return'<td>'+String(v==null?'':v)+'</td>'}).join('')+(act?'<td>'+act(r)+'</td>':'')+'</tr>'}).join('')+'</tbody></table></div>'}
async function boot(){if(!token)return;try{me=await raw('/api/parent/me');showPortal();var q=new URLSearchParams(location.search),p=q.get('payment');if(p){setTimeout(function(){alert(p==='success'?'Payment received successfully. Your fee statement has been updated.':'Payment status: '+p)},200)}}catch(e){sessionStorage.removeItem('rx_parent_token');token=''}}
function showPortal(){E('login').classList.add('hide');E('portal').classList.remove('hide');E('guardianName').textContent=me.guardian.first_name+' '+me.guardian.last_name;E('schoolName').textContent=me.school.school_name;E('children').innerHTML=me.students.map(function(s){return'<div class="panel child" data-student="'+s.id+'"><b>'+esc(s.first_name+' '+s.last_name)+'</b><div class="muted">'+esc(s.admission_no)+'</div><div>'+esc(s.classroom_name||'Not currently enrolled')+'</div></div>'}).join('');E('children').onclick=function(e){var c=e.target.closest('[data-student]');if(c)loadStudent(c.dataset.student)};if(me.students[0])loadStudent(me.students[0].id)}
async function loadStudent(id){
 currentStudent=id;var d=await raw('/api/parent/students/'+id+'/dashboard');
 E('studentArea').innerHTML='<div class="panel"><div class="top"><div><h2>'+esc(d.student.first_name+' '+d.student.last_name)+'</h2><div class="muted">'+esc(d.student.admission_no)+' • '+esc(d.student.classroom_name||'No class')+'</div></div></div><div class="grid" style="margin-top:12px"><div class="panel stat"><span class="muted">Outstanding fees</span><b>GHS '+Number(d.fees.outstanding||0).toFixed(2)+'</b></div><div class="panel stat"><span class="muted">Present days</span><b>'+esc(d.attendance.present||0)+'</b></div><div class="panel stat"><span class="muted">Absent days</span><b>'+esc(d.attendance.absent||0)+'</b></div></div></div><div class="tabs"><button class="ghost" id="tabHomework">Homework</button><button class="ghost" id="tabFees">Fees & Payments</button><button class="ghost" id="tabReports">Report Card</button><button class="ghost" id="tabStatement">Academic Statement</button><button class="ghost" id="tabTimetable">Timetable</button><button class="ghost" id="tabNews">Announcements</button></div><div id="detail"></div>';
 E('tabHomework').onclick=function(){
   var cards=d.homework.length?d.homework.map(function(h){
     var submission=h.submission_status||'not_submitted',score=h.score==null?'Not graded':String(h.score)+(h.max_score!=null?' / '+h.max_score:'');
     return '<div class="homework-card"><div class="top"><div><h3>'+esc(h.title)+'</h3><div class="muted">'+esc(h.subject_name)+'</div></div><span class="badge">'+esc(submission.replace('_',' '))+'</span></div>'+
       '<div class="homework-meta"><span class="badge">Due: '+esc(h.due_at?new Date(h.due_at).toLocaleString():'No due date')+'</span>'+(h.max_score!=null?'<span class="badge">Marks: '+esc(h.max_score)+'</span>':'')+'</div>'+
       '<h4>Instructions</h4><div class="homework-instructions">'+esc(h.instructions||'No instructions provided.')+'</div>'+
       '<div class="homework-result"><b>Submission status:</b> '+esc(submission.replace('_',' '))+'<br><b>Score:</b> '+esc(score)+(h.teacher_comment?'<br><b>Teacher feedback:</b> '+esc(h.teacher_comment):'')+'</div></div>'
   }).join(''):'<div class="panel"><p class="muted">No published homework at the moment.</p></div>';
   E('detail').innerHTML='<div class="panel"><div class="top"><div><h3>Homework</h3><p class="muted">Full instructions, due dates and submission updates from the class teacher.</p></div></div></div>'+cards
 };
 E('tabFees').onclick=async function(){
   var x=await raw('/api/parent/students/'+id+'/fees'),requests=await raw('/api/parent/students/'+id+'/payment-requests').catch(function(){return[]});
   function paymentButtons(attrs){return'<div class="pay-actions"><button class="pay-momo" '+attrs+' data-method="mobile_money">Pay with Mobile Money</button><button class="pay-card" '+attrs+' data-method="card">Pay with Card</button></div>'}
   E('detail').innerHTML='<div class="panel"><div class="top"><div><h3>Fees & Payments</h3><p class="muted">Choose Mobile Money or Card. You will be redirected to the secure payment checkout and your fee balance updates only after verification.</p></div></div>'+
     (requests.length?'<div class="panel" style="background:#102821"><h3>School Payment Requests</h3>'+table(requests,[{key:'fee_name',label:'Fee'},{key:'amount',render:function(r){return'GHS '+Number(r.amount).toFixed(2)}},{key:'note'},{key:'created_at',label:'Requested',render:function(r){return esc(new Date(r.created_at).toLocaleDateString())}}],function(r){return paymentButtons('data-pay-request="'+r.id+'" data-fee="'+(r.student_fee_id||'')+'" data-amount="'+r.amount+'"')})+'</div>':'')+
     '<h3>Outstanding / Assigned Fees</h3>'+table(x.items,[{key:'fee_name',label:'Fee'},{key:'due',render:function(r){return'GHS '+Number(r.due).toFixed(2)}},{key:'paid',render:function(r){return'GHS '+Number(r.paid).toFixed(2)}},{key:'balance',render:function(r){return'<b>GHS '+Number(r.balance).toFixed(2)+'</b>'}},{key:'status'}],function(r){return Number(r.balance)>0?paymentButtons('data-pay-fee="'+r.id+'" data-amount="'+r.balance+'"'):''})+
     '<h3 style="margin-top:18px">Payment History</h3>'+table(x.payments,[{key:'paid_at',label:'Date',render:function(r){return esc(new Date(r.paid_at).toLocaleString())}},{key:'amount',render:function(r){return'GHS '+Number(r.amount).toFixed(2)}},{key:'payment_method',label:'Method'},{key:'reference'}])+'</div>';
   E('detail').onclick=async function(ev){
     var b=ev.target.closest('[data-method]');if(!b)return;
     var method=b.dataset.method,amount=Number(b.dataset.amount),body={studentId:id,amount:amount,method:method};
     if(b.dataset.payRequest){body.paymentRequestId=b.dataset.payRequest;if(b.dataset.fee)body.studentFeeId=b.dataset.fee}
     else body.studentFeeId=b.dataset.payFee;
     b.disabled=true;b.textContent='Opening secure checkout...';
     try{var intent=await raw('/api/parent/payment-intents',{method:'POST',body:JSON.stringify(body)});if(intent.authorization_url)window.location.href=intent.authorization_url;else throw Error('Payment checkout could not be created')}catch(err){b.disabled=false;b.textContent=method==='mobile_money'?'Pay with Mobile Money':'Pay with Card';alert(err.message)}
   };
 };
 E('tabReports').onclick=async function(){
   var x=await raw('/api/parent/students/'+id+'/latest-report');
   if(!x.available)return E('detail').innerHTML='<div class="panel"><h3>Report Card</h3><p class="muted">The latest report has not yet been approved for release by the school.</p></div>';
   var p=x.performance||{},a=x.attendance||{},s=x.student||{},t=x.term||{},cmt=x.comments||{},position=p.classPosition?p.classPosition+' / '+p.classSize:'—';
   E('detail').innerHTML='<div class="top" style="margin-bottom:10px"><div></div><button id="printParentReport" class="ghost">Print / Save PDF</button></div>'+
     '<div class="parent-report"><div class="parent-report-head"><div><h2>'+esc((x.school&&x.school.school_name)||'School Report Card')+'</h2><p>'+esc((x.school&&x.school.motto)||'Student Academic Report')+'</p></div><div class="parent-report-term"><b>STUDENT REPORT CARD</b><span>'+esc(t.academic_year||'')+'</span><br><span>'+esc(t.name||'')+'</span></div></div>'+
     '<div class="parent-report-body"><div class="parent-report-student"><div><span>Student</span><b>'+esc(s.first_name+' '+s.last_name)+'</b></div><div><span>Admission No.</span><b>'+esc(s.admission_no||'—')+'</b></div><div><span>Class</span><b>'+esc(s.classroom_name||'—')+'</b></div><div><span>Grade</span><b>'+esc(s.grade_name||'—')+'</b></div></div>'+
     '<div class="parent-report-metrics"><div><span>Overall Average</span><b>'+esc(p.overallAverage==null?'—':p.overallAverage+'%')+'</b></div><div><span>Class Position</span><b>'+esc(position)+'</b></div><div><span>Attendance</span><b>'+esc(a.rate||0)+'%</b></div><div><span>Promotion Status</span><b>'+esc(String(cmt.promotion_decision||'Pending').replace('_',' '))+'</b></div><div><span>Present</span><b>'+esc(a.present||0)+'</b></div><div><span>Absent</span><b>'+esc(a.absent||0)+'</b></div></div>'+
     '<h3>Academic Performance</h3>'+table(x.subjects,[{key:'subject_name',label:'Subject'},{key:'class_assessment_score',label:'Class Assessment (30%)',render:function(r){return r.class_assessment_score==null?'—':esc(r.class_assessment_score)+' / 30'}},{key:'exam_score',label:'Exam (70%)',render:function(r){return r.exam_score==null?'—':esc(r.exam_score)+' / 70'}},{key:'total',label:'Total',render:function(r){return r.total==null?'—':'<b>'+esc(r.total)+'%</b>'}},{key:'grade'},{key:'remark'}])+
     '<div class="report-comments-parent"><div><h4>Class Teacher Remark</h4><p>'+esc(cmt.class_teacher_comment||'—')+'</p><h4>Conduct</h4><p>'+esc(cmt.conduct||'—')+'</p></div><div><h4>Headteacher Remark</h4><p>'+esc(cmt.headteacher_comment||'—')+'</p><h4>Next Term Begins</h4><p>'+esc(cmt.next_term_begins||t.next_term_begins||'—')+'</p></div></div></div>'+
     '<div class="report-footer-parent">Released school report • Generated by Revolt-X School</div></div>';
   E('printParentReport').onclick=function(){window.print()}
 };
 E('tabStatement').onclick=async function(){
   var requests=await raw('/api/parent/students/'+id+'/academic-statement-requests');
   function renderRequests(){return table(requests,[{key:'requested_at',label:'Requested',render:function(r){return esc(new Date(r.requested_at).toLocaleString())}},{key:'purpose',label:'Purpose'},{key:'status'},{key:'statement_reference',label:'Reference',render:function(r){return esc(r.statement_reference||'—')}}],function(r){return r.status==='approved'?'<button class="ghost" data-view-statement="'+r.id+'">View statement</button>':''})}
   E('detail').innerHTML='<div class="panel"><div class="top"><div><h3>Cumulative Academic Statement</h3><p class="muted">Request an official cumulative academic record for transfer, continuation, scholarship or personal use.</p></div></div><label>Purpose</label><select id="statementPurpose"><option value="continuation">Continue at another school</option><option value="transfer">Transfer</option><option value="scholarship">Scholarship</option><option value="personal">Personal record</option><option value="other">Other</option></select><label>Additional note</label><textarea id="statementNote" rows="3" placeholder="Optional details for the school"></textarea><button id="requestStatement" class="primary">Request academic statement</button></div><div class="panel"><h3>Requests</h3><div id="statementRequests">'+renderRequests()+'</div></div>';
   E('requestStatement').onclick=async function(){try{E('requestStatement').disabled=true;E('requestStatement').textContent='Submitting request...';await raw('/api/parent/students/'+id+'/academic-statement-requests',{method:'POST',body:JSON.stringify({purpose:E('statementPurpose').value,note:E('statementNote').value||undefined})});E('requestStatement').textContent='Request submitted';setTimeout(function(){E('tabStatement').click()},500)}catch(err){alert(err.message);E('requestStatement').disabled=false;E('requestStatement').textContent='Request academic statement'}};
   E('statementRequests').onclick=async function(ev){
     var rid=ev.target.dataset.viewStatement;if(!rid)return;
     var x=await raw('/api/parent/academic-statements/'+rid),st=x.statement,req=x.request;
     var terms=st.terms.map(function(t){return'<div class="panel"><h3>'+esc(t.academic_year)+' • '+esc(t.term_name)+' • '+esc(t.classroom_name||'')+'</h3><p><b>Term average:</b> '+esc(t.overallAverage==null?'—':t.overallAverage+'%')+'</p>'+table(t.subjects,[{key:'subject_name',label:'Subject'},{key:'percentage',label:'Final %'},{key:'grade'},{key:'remark'}])+'</div>'}).join('');
     E('detail').innerHTML='<div class="top"><div><h2>Cumulative Academic Statement</h2><p class="muted">Reference: '+esc(req.statement_reference||'')+'</p></div><button id="printAcademicStatement" class="ghost">Print / Save PDF</button></div><div class="panel"><h3>'+esc(st.school.school_name)+'</h3><p>'+esc(st.school.address||'')+'</p><p><b>Student:</b> '+esc(st.student.first_name+' '+st.student.last_name)+'<br><b>Admission No.:</b> '+esc(st.student.admission_no)+'<br><b>Academic years covered:</b> '+esc(st.summary.academicYears)+'<br><b>Terms recorded:</b> '+esc(st.summary.terms)+'</p></div>'+terms;
     E('printAcademicStatement').onclick=function(){window.print()}
   }
 };
 E('tabTimetable').onclick=async function(){
   var rows=await raw('/api/parent/students/'+id+'/timetable'),days=['','Monday','Tuesday','Wednesday','Thursday','Friday'];
   E('detail').innerHTML='<div class="panel"><div class="top"><div><h3>Class Timetable</h3><p class="muted">Current timetable for '+esc(d.student.classroom_name||'this class')+'.</p></div><button id="printParentTimetable" class="ghost">Print</button></div>'+table(rows,[{key:'day_of_week',label:'Day',render:function(r){return days[r.day_of_week]}},{key:'start_time',label:'Start',render:function(r){return esc(String(r.start_time).slice(0,5))}},{key:'end_time',label:'End',render:function(r){return esc(String(r.end_time).slice(0,5))}},{key:'subject_name',label:'Subject'},{key:'room'}])+'</div>';E('printParentTimetable').onclick=function(){window.print()}
 };
 E('tabNews').onclick=function(){E('detail').innerHTML='<div class="panel"><h3>Announcements</h3>'+table(d.announcements,[{key:'title'},{key:'body'},{key:'published_at',label:'Published',render:function(r){return esc(r.published_at?new Date(r.published_at).toLocaleDateString():'')}}])+'</div>'};
 E('tabHomework').click();
}
E('signin').onclick=async function(){E('loginError').textContent='';try{var x=await raw('/api/parent/login',{method:'POST',body:JSON.stringify({phone:E('phone').value,admissionNo:E('admission').value,pin:E('pin').value})});token=x.token;sessionStorage.setItem('rx_parent_token',token);me=await raw('/api/parent/me');showPortal()}catch(e){E('loginError').textContent=e.message}};
E('logout').onclick=async function(){try{await raw('/api/parent/logout',{method:'POST',body:'{}'})}catch(e){}sessionStorage.removeItem('rx_parent_token');location.reload()};
boot();
})();
</script></body></html>`;
