export const studentFrontend=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Revolt-X School Student Portal</title>
<style>
:root{--bg:#071018;--panel:#0e1e29;--line:#203844;--text:#f4f8fa;--muted:#90a8b5;--green:#45ddb2;--blue:#48a9ff}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px Arial,sans-serif}.wrap{max-width:1100px;margin:auto;padding:22px}.brand{font-size:20px;font-weight:900;margin-bottom:22px}.brand span{color:var(--green)}.panel{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px;margin-bottom:12px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stat b{display:block;font-size:25px;margin-top:6px}.muted{color:var(--muted)}input,select,textarea{width:100%;padding:11px;margin:6px 0 12px;background:#07141d;border:1px solid var(--line);border-radius:8px;color:white}.primary,.ghost{padding:10px 14px;border-radius:9px;cursor:pointer}.primary{border:0;background:linear-gradient(90deg,var(--green),var(--blue));font-weight:800;color:#041018}.ghost{border:1px solid var(--line);background:transparent;color:white}.top{display:flex;justify-content:space-between;gap:12px;align-items:center}.hide{display:none}.toast{position:fixed;right:18px;bottom:18px;background:#102a24;border:1px solid #2c6d5c;border-radius:9px;padding:11px 14px;z-index:40;max-width:min(420px,90vw)}.table{overflow:auto}.table table{width:100%;border-collapse:collapse}.table td,.table th{padding:9px;border-bottom:1px solid var(--line);text-align:left}.table th{color:var(--muted);font-size:11px;text-transform:uppercase}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.error{color:#ffb0bb}@media(max-width:760px){.grid{grid-template-columns:1fr 1fr}.top{align-items:flex-start;flex-direction:column}}@media(max-width:520px){.grid{grid-template-columns:1fr}}
</style></head><body>
<div class="wrap"><div class="brand"><span>RX</span> REVOLT-X SCHOOL <span class="muted">Student Portal</span></div>
<section id="login" class="panel" style="max-width:460px;margin:70px auto"><h2>Student Sign In</h2><p class="muted">Enter your admission number and school-issued PIN.</p><label>Admission number</label><input id="admission"><label>PIN</label><input id="pin" type="password" maxlength="6"><button id="signin" class="primary" style="width:100%">Sign in</button><p id="err" class="error"></p></section>
<section id="portal" class="hide"><div class="top"><div><h2 id="studentName"></h2><div id="schoolName" class="muted"></div></div><button id="logout" class="ghost">Sign out</button></div><div id="summary" class="grid"></div><div class="tabs"><button id="homework" class="ghost">Homework</button><button id="results" class="ghost">Results</button><button id="statement" class="ghost">Academic Statement</button><button id="timetable" class="ghost">Timetable</button><button id="announcements" class="ghost">Announcements</button></div><div id="detail"></div></section>
</div><div id="toast" class="toast hide"></div>
<script>
(function(){
var token=sessionStorage.getItem('rx_student_token')||'',me=null;
function E(i){return document.getElementById(i)}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}function toast(m,b){var t=E('toast');if(!t)return;t.textContent=m;t.style.borderColor=b?'#71323a':'#2c6d5c';t.classList.remove('hide');setTimeout(function(){t.classList.add('hide')},3200)}
function table(rows,cols){if(!rows||!rows.length)return'<p class="muted">No records yet.</p>';return'<div class="table"><table><thead><tr>'+cols.map(function(c){return'<th>'+esc(c.label||c.key)+'</th>'}).join('')+'</tr></thead><tbody>'+rows.map(function(r){return'<tr>'+cols.map(function(c){var v=c.render?c.render(r):r[c.key];return'<td>'+String(v==null?'':v)+'</td>'}).join('')+'</tr>'}).join('')+'</tbody></table></div>'}
async function raw(path,opt){opt=opt||{};opt.headers=Object.assign({'content-type':'application/json'},opt.headers||{},token?{authorization:'Bearer '+token}:{});var r=await fetch(path,opt),j=null;try{j=await r.json()}catch(e){}if(!r.ok)throw Error(j&&j.error&&j.error.message?j.error.message:'Request failed');return j}
async function boot(){if(!token)return;try{me=await raw('/api/student/me');show()}catch(e){sessionStorage.removeItem('rx_student_token');token=''}}
function show(){E('login').classList.add('hide');E('portal').classList.remove('hide');E('studentName').textContent=me.student.first_name+' '+me.student.last_name;E('schoolName').textContent=me.school.school_name+' • '+(me.student.classroom_name||'No current class');E('summary').innerHTML=[['Admission No.',me.student.admission_no],['Grade',me.student.grade_name||'—'],['Present days',me.attendance.present||0],['Absent days',me.attendance.absent||0]].map(function(x){return'<div class="panel stat"><span class="muted">'+esc(x[0])+'</span><b>'+esc(x[1])+'</b></div>'}).join('');E('homework').click()}
E('signin').onclick=async function(){E('err').textContent='';try{var x=await raw('/api/student/login',{method:'POST',body:JSON.stringify({admissionNo:E('admission').value,pin:E('pin').value})});token=x.token;sessionStorage.setItem('rx_student_token',token);me=await raw('/api/student/me');show()}catch(e){E('err').textContent=e.message}}
E('logout').onclick=async function(){try{await raw('/api/student/logout',{method:'POST',body:'{}'})}catch(e){}sessionStorage.removeItem('rx_student_token');location.reload()};
E('homework').onclick=function(){E('detail').innerHTML='<div class="panel"><h3>Homework</h3>'+table(me.homework,[{key:'subject_name',label:'Subject'},{key:'title'},{key:'due_at',label:'Due',render:function(r){return esc(r.due_at?new Date(r.due_at).toLocaleString():'')}},{key:'submission_status',label:'Status'}])+'</div>'};
E('results').onclick=async function(){var r=await raw('/api/student/latest-report');E('detail').innerHTML='<div class="panel"><h3>'+(r.term?esc(r.term.name):'Latest Report')+'</h3>'+table(r.subjects,[{key:'subject_name',label:'Subject'},{key:'percentage',label:'Average %'},{key:'grade'},{key:'remark'}])+'<p><b>Teacher comment:</b> '+esc(r.comments&&r.comments.class_teacher_comment||'')+'</p><p><b>Headteacher comment:</b> '+esc(r.comments&&r.comments.headteacher_comment||'')+'</p><p><b>Next term begins:</b> '+esc((r.comments&&r.comments.next_term_begins)||(r.term&&r.term.next_term_begins)||'—')+'</p></div>'};
E('statement').onclick=async function(){
  var requests=await raw('/api/student/academic-statement-requests');
  function reqTable(){return table(requests,[{key:'requested_at',label:'Requested',render:function(r){return esc(new Date(r.requested_at).toLocaleString())}},{key:'purpose',label:'Purpose'},{key:'status'},{key:'statement_reference',label:'Reference',render:function(r){return esc(r.statement_reference||'—')}}])}
  E('detail').innerHTML='<div class="panel"><h3>Cumulative Academic Statement</h3><p class="muted">Request your cumulative academic record for continuation, transfer, scholarship or personal use.</p><label>Purpose</label><select id="studentStatementPurpose"><option value="continuation">Continue at another school</option><option value="transfer">Transfer</option><option value="scholarship">Scholarship</option><option value="personal">Personal record</option><option value="other">Other</option></select><label>Note</label><textarea id="studentStatementNote" rows="3"></textarea><button id="studentStatementRequest" class="primary">Request statement</button></div><div class="panel"><h3>My requests</h3>'+reqTable()+'<div id="statementActions"></div></div>';
  var approved=requests.find(function(r){return r.status==='approved'});
  if(approved)E('statementActions').innerHTML='<button id="viewStudentStatement" class="ghost">View latest approved statement</button>';
  E('studentStatementRequest').onclick=async function(){try{E('studentStatementRequest').disabled=true;E('studentStatementRequest').textContent='Submitting...';await raw('/api/student/academic-statement-requests',{method:'POST',body:JSON.stringify({purpose:E('studentStatementPurpose').value,note:E('studentStatementNote').value||undefined})});E('studentStatementRequest').textContent='Request submitted';setTimeout(function(){E('statement').click()},500)}catch(err){E('studentStatementRequest').disabled=false;E('studentStatementRequest').textContent='Request statement';alert(err.message)}};
  var view=E('viewStudentStatement');if(view)view.onclick=async function(){var x=await raw('/api/student/academic-statements/'+approved.id),st=x.statement;E('detail').innerHTML='<div class="top"><div><h2>Cumulative Academic Statement</h2><p class="muted">Reference: '+esc(x.request.statement_reference||'')+'</p></div><button id="printStudentStatement" class="ghost">Print / Save PDF</button></div><div class="panel"><h3>'+esc(st.school.school_name)+'</h3><p><b>Student:</b> '+esc(st.student.first_name+' '+st.student.last_name)+'<br><b>Admission No.:</b> '+esc(st.student.admission_no)+'</p></div>'+st.terms.map(function(t){return'<div class="panel"><h3>'+esc(t.academic_year)+' • '+esc(t.term_name)+'</h3><p><b>Class:</b> '+esc(t.classroom_name||'—')+' • <b>Average:</b> '+esc(t.overallAverage==null?'—':t.overallAverage+'%')+'</p>'+table(t.subjects,[{key:'subject_name',label:'Subject'},{key:'percentage',label:'Final %'},{key:'grade'},{key:'remark'}])+'</div>'}).join('');E('printStudentStatement').onclick=function(){window.print()}}
};
E('timetable').onclick=async function(){var rows=await raw('/api/student/timetable');E('detail').innerHTML='<div class="panel"><h3>My Timetable</h3>'+table(rows,[{key:'day_of_week',label:'Day',render:function(r){return['','Mon','Tue','Wed','Thu','Fri'][r.day_of_week]}},{key:'start_time',label:'Start',render:function(r){return esc(String(r.start_time).slice(0,5))}},{key:'end_time',label:'End',render:function(r){return esc(String(r.end_time).slice(0,5))}},{key:'subject_name',label:'Subject'},{key:'room'}])+'</div>'};
E('announcements').onclick=function(){E('detail').innerHTML='<div class="panel"><h3>Announcements</h3>'+table(me.announcements,[{key:'title'},{key:'body'},{key:'published_at',label:'Published',render:function(r){return esc(r.published_at?new Date(r.published_at).toLocaleDateString():'')}}])+'</div>'};
boot();
})();
</script></body></html>`;
