export const teacherFrontend=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Revolt-X School Teacher Portal</title>
<style>
:root{--bg:#071018;--side:#0a1721;--panel:#0e1e29;--line:#203844;--text:#f4f8fa;--muted:#90a8b5;--green:#45ddb2;--blue:#48a9ff;--red:#ff7482}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 Arial,sans-serif}.shell{display:grid;grid-template-columns:240px 1fr;min-height:100vh}.side{position:fixed;inset:0 auto 0 0;width:240px;height:100vh;background:var(--side);border-right:1px solid var(--line);padding:18px 10px;overflow:auto}.brand{font-weight:900;letter-spacing:.06em;padding:8px 10px 18px}.brand span{color:var(--green)}.nav{display:grid;gap:5px}.nav button{border:0;background:none;color:#aec0ca;text-align:left;padding:11px 12px;border-radius:9px;cursor:pointer}.nav button.active,.nav button:hover{background:#142a36;color:white}.main{grid-column:2;padding:22px 26px 60px;min-width:0}.top{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:22px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px}.panel+.panel{margin-top:12px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.two{display:grid;grid-template-columns:1fr 1fr;gap:12px}.stat b{display:block;font-size:26px;margin-top:6px}.muted{color:var(--muted)}.section{display:flex;justify-content:space-between;align-items:center;gap:10px;margin:18px 0 10px}.primary,.ghost,.mini,.danger{border-radius:9px;padding:9px 12px;cursor:pointer}.primary{border:0;background:linear-gradient(90deg,var(--green),var(--blue));font-weight:800;color:#051018}.ghost,.mini{border:1px solid var(--line);background:transparent;color:white}.danger{border:1px solid #6c3038;background:#281318;color:#ffb6be}.mini{padding:6px 8px;font-size:12px}.table{overflow:auto}.table table{width:100%;border-collapse:collapse}.table th,.table td{padding:10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}.table th{font-size:11px;color:var(--muted);text-transform:uppercase}.badge{display:inline-block;padding:4px 7px;border-radius:10px;background:#15342b;color:#73e6c6;font-size:10px}input,select,textarea{width:100%;padding:10px;background:#07141d;border:1px solid var(--line);border-radius:8px;color:white;margin:5px 0 10px}.row{display:flex;gap:10px}.row>*{flex:1}.modal{position:fixed;inset:0;background:#000b;display:grid;place-items:center;padding:16px;z-index:10}.box{width:min(720px,96vw);max-height:90vh;overflow:auto;background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:20px}.hide{display:none!important}.toast{position:fixed;right:18px;bottom:18px;background:#102a24;border:1px solid #2c6d5c;border-radius:9px;padding:11px 14px;z-index:20}.attendance{display:grid;grid-template-columns:1.4fr repeat(4,auto);gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line)}.attendance .sel{background:#1b483b}.loading{min-height:100vh;display:grid;place-items:center}
@media(max-width:850px){.shell{grid-template-columns:72px 1fr}.side{width:72px}.brand{font-size:0}.brand span{font-size:15px}.nav button{font-size:0;text-align:center}.nav button:before{content:attr(data-i);font-size:18px}.main{padding:16px 12px}.grid{grid-template-columns:repeat(2,1fr)}.two{grid-template-columns:1fr}}@media(max-width:520px){.grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}.attendance{grid-template-columns:1fr 1fr 1fr}.attendance .student{grid-column:1/-1}.row{flex-direction:column}}
</style></head><body>
<div id="loading" class="loading"><div><b>REVOLT-X TEACHER</b><p class="muted">Opening teacher workspace...</p></div></div>
<div id="app" class="shell hide"><aside class="side"><div class="brand"><span>RX</span> TEACHER</div><nav id="nav" class="nav"></nav></aside><main class="main"><header class="top"><div><b id="school">Revolt-X School</b><div id="who" class="muted"></div></div><button id="refresh" class="ghost">Refresh</button></header><div id="content"></div></main></div>
<div id="modal" class="modal hide"><div class="box"><div id="modalBody"></div><button id="closeModal" class="ghost">Close</button></div></div><div id="toast" class="toast hide"></div>
<script>
(function(){
var token=sessionStorage.getItem('rx_teacher_token')||'',ctx=null,current='dashboard';
var nav=[['dashboard','My Dashboard','⌂'],['classes','My Classes','C'],['attendance','Attendance','✓'],['homework','Homework','H'],['assessments','Assessments & Scores','A'],['timetable','Timetable','T'],['reports','Report Cards','R']];
function E(i){return document.getElementById(i)}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}function toast(m,b){var t=E('toast');t.textContent=m;t.style.borderColor=b?'#6d3038':'#2c6d5c';t.classList.remove('hide');setTimeout(function(){t.classList.add('hide')},2500)}function badge(v){return'<span class="badge">'+esc(v||'—')+'</span>'}
function table(rows,cols,act){if(!rows||!rows.length)return'<p class="muted">No records.</p>';return'<div class="table"><table><thead><tr>'+cols.map(function(c){return'<th>'+esc(c.label||c.key)+'</th>'}).join('')+(act?'<th>Actions</th>':'')+'</tr></thead><tbody>'+rows.map(function(r){return'<tr>'+cols.map(function(c){var v=c.render?c.render(r):r[c.key];return'<td>'+String(v==null?'':v)+'</td>'}).join('')+(act?'<td>'+act(r)+'</td>':'')+'</tr>'}).join('')+'</tbody></table></div>'}
async function raw(path,opt){opt=opt||{};opt.headers=Object.assign({'content-type':'application/json'},opt.headers||{},token?{authorization:'Bearer '+token}:{});var r=await fetch(path,opt),j=null;try{j=await r.json()}catch(e){}if(!r.ok)throw Error(j&&j.error&&j.error.message?j.error.message:'Request failed ('+r.status+')');return j}
function modal(h){E('modalBody').innerHTML=h;E('modal').classList.remove('hide')}function close(){E('modal').classList.add('hide');E('modalBody').innerHTML=''}E('closeModal').onclick=close;
function field(f,v){v=v==null?'':v;if(f.type==='select')return'<label>'+esc(f.label)+'</label><select data-f="'+f.key+'">'+(f.options||[]).map(function(o){var value=typeof o==='string'?o:o.value,label=typeof o==='string'?o:o.label;return'<option value="'+esc(value)+'"'+(String(value)===String(v)?' selected':'')+'>'+esc(label)+'</option>'}).join('')+'</select>';if(f.type==='textarea')return'<label>'+esc(f.label)+'</label><textarea rows="5" data-f="'+f.key+'">'+esc(v)+'</textarea>';return'<label>'+esc(f.label)+'</label><input type="'+(f.type||'text')+'" data-f="'+f.key+'" value="'+esc(v)+'">'}
function form(title,fields,vals,save){vals=vals||{};modal('<h2>'+esc(title)+'</h2>'+fields.map(function(f){return field(f,vals[f.key])}).join('')+'<button id="saveModal" class="primary" style="width:100%">Save</button>');E('saveModal').onclick=async function(){var v={};E('modalBody').querySelectorAll('[data-f]').forEach(function(x){v[x.dataset.f]=x.value});try{await save(v);close();toast('Saved');page(current)}catch(e){toast(e.message,true)}}}
async function boot(){try{if(!token){var p=await fetch('/api/auth/preview',{method:'POST'}),j=await p.json();if(!p.ok)throw Error(j.error&&j.error.message||'Core OS access failed');token=j.accessToken;sessionStorage.setItem('rx_teacher_token',token)}ctx=await raw('/api/teacher/context');E('school').textContent=ctx.school.school_name;E('who').textContent=ctx.core.first_name+' '+ctx.core.last_name+' • '+ctx.schoolRole.replace('_',' ');E('nav').innerHTML=nav.map(function(n){return'<button data-p="'+n[0]+'" data-i="'+n[2]+'">'+n[1]+'</button>'}).join('');E('nav').onclick=function(e){var b=e.target.closest('[data-p]');if(b)page(b.dataset.p)};E('refresh').onclick=function(){page(current)};E('loading').classList.add('hide');E('app').classList.remove('hide');page('dashboard')}catch(e){E('loading').innerHTML='<div><h2>Teacher workspace unavailable</h2><p>'+esc(e.message)+'</p></div>'}}
async function page(p){current=p;document.querySelectorAll('#nav button').forEach(function(b){b.classList.toggle('active',b.dataset.p===p)});E('content').innerHTML='<p class="muted">Loading...</p>';try{
if(p==='dashboard'){var d=await raw('/api/teacher/dashboard');E('content').innerHTML='<h1>My Dashboard</h1><div class="grid">'+[['Assigned classes',d.assignedClasses],['Students',d.students],['Homework',d.homework],['Assessments',d.assessments]].map(function(x){return'<div class="panel stat"><span class="muted">'+x[0]+'</span><b>'+esc(x[1])+'</b></div>'}).join('')+'</div><div class="two" style="margin-top:12px"><div class="panel"><h3>Today</h3><p><b>'+esc(d.presentToday)+'</b> marked present</p><p><b>'+esc(d.absentToday)+'</b> marked absent</p></div><div class="panel"><h3>Current term</h3><p>'+esc(d.term?d.term.name:'No active term')+'</p></div></div>'}
else if(p==='classes'){var rows=await raw('/api/teacher/classes');E('content').innerHTML='<h1>My Classes</h1><div class="panel">'+table(rows,[{key:'classroom_name',label:'Class'},{key:'grade_name',label:'Grade'},{key:'subject_name',label:'Subject',render:function(r){return esc(r.subject_name||'Class teacher / all subjects')}},{key:'student_count',label:'Students'}])+'</div>'}
else if(p==='attendance'){var classes=await raw('/api/teacher/classes');var unique=[];classes.forEach(function(x){if(!unique.some(function(y){return y.classroom_id===x.classroom_id}))unique.push(x)});E('content').innerHTML='<h1>Attendance</h1><div class="row"><select id="cls">'+unique.map(function(c){return'<option value="'+c.classroom_id+'">'+esc(c.classroom_name)+'</option>'}).join('')+'</select><input id="date" type="date" value="'+new Date().toISOString().slice(0,10)+'"></div><button id="load" class="primary">Load class</button><div id="att" class="panel" style="margin-top:12px"></div>';E('load').onclick=async function(){var cid=E('cls').value,date=E('date').value,rows=await raw('/api/attendance?classroomId='+cid+'&date='+date);E('att').innerHTML=rows.map(function(r){return'<div class="attendance" data-student="'+r.student_id+'"><div class="student"><b>'+esc(r.first_name+' '+r.last_name)+'</b><div class="muted">'+esc(r.admission_no)+'</div></div>'+['present','absent','late','excused'].map(function(s){return'<button class="mini '+(r.attendance_status===s?'sel':'')+'" data-status="'+s+'">'+s+'</button>'}).join('')+'</div>'}).join('')+'<button id="saveAtt" class="primary" style="margin-top:12px">Save attendance</button>';E('att').onclick=function(e){var b=e.target.closest('[data-status]');if(b){var row=b.closest('[data-student]');row.querySelectorAll('[data-status]').forEach(function(x){x.classList.remove('sel')});b.classList.add('sel')}};E('saveAtt').onclick=async function(){var records=[];E('att').querySelectorAll('[data-student]').forEach(function(r){var s=r.querySelector('.sel');if(s)records.push({studentId:r.dataset.student,status:s.dataset.status})});if(!records.length)return toast('Mark at least one student',true);await raw('/api/attendance/mark',{method:'POST',body:JSON.stringify({classroomId:cid,date:date,records:records})});toast('Attendance saved')}}}
else if(p==='homework'){
 var rr=await Promise.all([raw('/api/academic-years'),raw('/api/terms'),raw('/api/teacher/classes'),raw('/api/subjects'),raw('/api/homework')]);var years=rr[0],terms=rr[1],classes=rr[2],subjects=rr[3],homework=rr[4];var unique=[];classes.forEach(function(x){if(!unique.some(function(y){return y.classroom_id===x.classroom_id}))unique.push(x)});
 E('content').innerHTML='<div class="section"><h1>Homework</h1><button id="newHw" class="primary">Create homework</button></div><div class="panel">'+table(homework,[{key:'title'},{key:'classroom_name',label:'Class'},{key:'subject_name',label:'Subject'},{key:'due_at',label:'Due',render:function(r){return esc(r.due_at?new Date(r.due_at).toLocaleString():'')}},{key:'status',render:function(r){return badge(r.status)}}],function(r){return(r.status==='draft'?'<button class="mini" data-publish="'+r.id+'">Publish</button>':'')+'<button class="mini" data-subs="'+r.id+'">Submissions</button>'})+'</div>';
 E('newHw').onclick=function(){form('Create homework',[{key:'academicYearId',label:'Academic year',type:'select',options:years.map(function(x){return{value:x.id,label:x.name}})},{key:'termId',label:'Term',type:'select',options:terms.map(function(x){return{value:x.id,label:x.name}})},{key:'classroomId',label:'Class',type:'select',options:unique.map(function(x){return{value:x.classroom_id,label:x.classroom_name}})},{key:'subjectId',label:'Subject',type:'select',options:subjects.map(function(x){return{value:x.id,label:x.name}})},{key:'title',label:'Title'},{key:'instructions',label:'Instructions',type:'textarea'},{key:'dueAt',label:'Due',type:'datetime-local'},{key:'maxScore',label:'Maximum score',type:'number'}],{},function(v){return raw('/api/homework',{method:'POST',body:JSON.stringify({academicYearId:v.academicYearId,termId:v.termId,classroomId:v.classroomId,subjectId:v.subjectId,title:v.title,instructions:v.instructions,dueAt:v.dueAt?new Date(v.dueAt).toISOString():undefined,maxScore:v.maxScore?Number(v.maxScore):undefined})})})};
 E('content').onclick=async function(e){var id=e.target.dataset.publish;if(id){await raw('/api/homework/'+id+'/publish',{method:'POST',body:'{}'});toast('Homework published');return page('homework')}id=e.target.dataset.subs;if(id){var rows=await raw('/api/homework/'+id+'/submissions');modal('<h2>Homework submissions</h2>'+rows.map(function(s){return'<div class="row"><div><b>'+esc(s.first_name+' '+s.last_name)+'</b><div class="muted">'+esc(s.admission_no)+'</div></div><select data-status="'+s.student_id+'"><option'+(s.status==='not_submitted'?' selected':'')+'>not_submitted</option><option'+(s.status==='submitted'?' selected':'')+'>submitted</option><option'+(s.status==='late'?' selected':'')+'>late</option><option'+(s.status==='graded'?' selected':'')+'>graded</option></select><input data-score="'+s.student_id+'" type="number" value="'+esc(s.score==null?'':s.score)+'" placeholder="Score"></div>'}).join('')+'<button id="saveSubs" class="primary">Save submissions</button>');E('saveSubs').onclick=async function(){var records=[];E('modalBody').querySelectorAll('[data-status]').forEach(function(s){var score=E('modalBody').querySelector('[data-score="'+s.dataset.status+'"]');records.push({studentId:s.dataset.status,status:s.value,score:score&&score.value!==''?Number(score.value):null})});await raw('/api/homework/'+id+'/submissions',{method:'POST',body:JSON.stringify({records:records})});close();toast('Homework records saved')}}}
}
else if(p==='assessments'){
 var rr=await Promise.all([raw('/api/academic-years'),raw('/api/terms'),raw('/api/teacher/classes'),raw('/api/subjects'),raw('/api/assessments')]);
 var years=rr[0],terms=rr[1],classes=rr[2],subjects=rr[3],rows=rr[4],activeTerm=terms.find(function(t){return t.status==='active'})||terms[0],unique=[];
 classes.forEach(function(x){if(!unique.some(function(y){return y.classroom_id===x.classroom_id}))unique.push(x)});
 var scheme=activeTerm?await raw('/api/assessment-categories?academicYearId='+encodeURIComponent(activeTerm.academic_year_id)+'&termId='+encodeURIComponent(activeTerm.id)):{categories:[]},categories=scheme.categories||[];
 E('content').innerHTML='<div class="section"><div><h1>Assessments & Scores</h1><p class="muted">Create exercises under the School assessment scheme. Category weights are fixed by the School.</p></div><button id="newAssess" class="primary">Create exercise</button></div><div class="panel"><div class="row">'+categories.filter(function(c){return c.is_active}).map(function(cat){return'<div><b>'+esc(cat.name)+'</b><div class="muted">'+esc(cat.weight_percent)+'% • default '+esc(cat.default_max_score)+' marks</div></div>'}).join('')+'</div></div><div class="panel" style="margin-top:12px">'+table(rows,[{key:'category_name',label:'Category'},{key:'name',label:'Exercise'},{key:'classroom_name',label:'Class'},{key:'subject_name',label:'Subject'},{key:'max_score',label:'Marks'},{key:'scored_students',label:'Scores'}],function(r){return'<button class="mini" data-scores="'+r.id+'">Enter scores</button>'})+'</div>';
 E('newAssess').onclick=function(){
   if(!activeTerm||!categories.length)return toast('Assessment scheme is not configured for the active term',true);
   modal('<h2>Create assessment exercise</h2><label>Category</label><select id="taCat">'+categories.filter(function(x){return x.is_active}).map(function(x){return'<option value="'+x.id+'" data-max="'+x.default_max_score+'">'+esc(x.name)+' • '+esc(x.weight_percent)+'%</option>'}).join('')+'</select><label>Class</label><select id="taClass">'+unique.map(function(x){return'<option value="'+x.classroom_id+'">'+esc(x.classroom_name)+'</option>'}).join('')+'</select><label>Subject</label><select id="taSubject">'+subjects.filter(function(x){return x.is_active}).map(function(x){return'<option value="'+x.id+'">'+esc(x.name)+'</option>'}).join('')+'</select><label>Exercise title</label><input id="taName" placeholder="e.g. Classwork 3"><label>Maximum marks</label><input id="taMax" type="number"><label>Date</label><input id="taDate" type="date"><button id="taSave" class="primary">Create exercise</button>');
   function sync(){var o=E('taCat').selectedOptions[0];E('taMax').value=o?o.dataset.max:''}sync();E('taCat').onchange=sync;
   E('taSave').onclick=async function(){try{await raw('/api/assessments',{method:'POST',body:JSON.stringify({academicYearId:activeTerm.academic_year_id,termId:activeTerm.id,classroomId:E('taClass').value,subjectId:E('taSubject').value,categoryId:E('taCat').value,name:E('taName').value,maxScore:Number(E('taMax').value),assessmentDate:E('taDate').value||undefined})});close();toast('Exercise created');page('assessments')}catch(err){toast(err.message,true)}}
 };
 E('content').onclick=async function(e){var id=e.target.dataset.scores;if(!id)return;var x=await raw('/api/assessments/'+id+'/scores');modal('<h2>'+esc(x.assessment.name)+'</h2><p class="muted">Enter raw marks out of '+esc(x.assessment.max_score)+'. The School weighting is applied automatically.</p>'+x.students.map(function(s){return'<div class="row"><div><b>'+esc(s.first_name+' '+s.last_name)+'</b><div class="muted">'+esc(s.admission_no)+'</div></div><input data-score-student="'+s.student_id+'" type="number" max="'+esc(x.assessment.max_score)+'" value="'+esc(s.score==null?'':s.score)+'"></div>'}).join('')+'<button id="saveScores" class="primary">Save scores</button>');E('saveScores').onclick=async function(){var scores=[];E('modalBody').querySelectorAll('[data-score-student]').forEach(function(i){if(i.value!=='')scores.push({studentId:i.dataset.scoreStudent,score:Number(i.value)})});if(!scores.length)return toast('Enter at least one score',true);await raw('/api/assessments/'+id+'/scores',{method:'POST',body:JSON.stringify({scores:scores})});close();toast('Scores saved')}}
}
else if(p==='timetable'){var classes=await raw('/api/teacher/classes');var ids=classes.map(function(x){return x.classroom_id});var t=await raw('/api/timetable');t=t.filter(function(x){return ids.indexOf(x.classroom_id)>=0});E('content').innerHTML='<h1>My Timetable</h1><div class="panel">'+table(t,[{key:'day_of_week',label:'Day',render:function(r){return['','Mon','Tue','Wed','Thu','Fri'][r.day_of_week]}},{key:'start_time',label:'Start'},{key:'end_time',label:'End'},{key:'classroom_name',label:'Class'},{key:'subject_name',label:'Subject'},{key:'room'}])+'</div>'}
else if(p==='reports'){
 var rr=await Promise.all([raw('/api/teacher/students'),raw('/api/terms')]);var students=rr[0],terms=rr[1];E('content').innerHTML='<h1>Report Cards</h1><div class="panel"><div class="row"><select id="student">'+students.map(function(s){return'<option value="'+s.id+'">'+esc(s.first_name+' '+s.last_name+' • '+s.classroom_name)+'</option>'}).join('')+'</select><select id="term">'+terms.map(function(t){return'<option value="'+t.id+'">'+esc(t.name)+'</option>'}).join('')+'</select></div><button id="loadReport" class="primary">Load report</button></div><div id="report"></div>';E('loadReport').onclick=async function(){var sid=E('student').value,tid=E('term').value,r=await raw('/api/report-cards/'+sid+'?termId='+tid);var cm=r.comments||{};E('report').innerHTML='<div class="panel" style="margin-top:12px"><h2>'+esc(r.student.first_name+' '+r.student.last_name)+'</h2>'+table(r.subjects,[{key:'subject_name',label:'Subject'},{key:'percentage',label:'Average %'},{key:'grade'},{key:'remark'}])+'<h3>Comments</h3><textarea id="teacherComment" placeholder="Class teacher comment">'+esc(cm.class_teacher_comment||'')+'</textarea><input id="conduct" placeholder="Conduct" value="'+esc(cm.conduct||'')+'"><textarea id="interest" placeholder="Interests">'+esc(cm.interest||'')+'</textarea><button id="saveComments" class="primary">Save comments</button></div>';E('saveComments').onclick=async function(){await raw('/api/report-comments/'+sid,{method:'PUT',body:JSON.stringify({termId:tid,classTeacherComment:E('teacherComment').value||null,conduct:E('conduct').value||null,interest:E('interest').value||null})});toast('Report comments saved')}}}
}catch(e){E('content').innerHTML='<div class="panel"><h3>Could not load this area</h3><p class="muted">'+esc(e.message)+'</p></div>'}}
boot();
})();
</script></body></html>`;
