export const schoolFrontend=`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Revolt-X School</title>
<style>
:root{--bg:#071018;--side:#0a1721;--panel:#0e1e29;--panel2:#122733;--line:#203844;--text:#f4f8fa;--muted:#90a8b5;--green:#45ddb2;--blue:#48a9ff;--gold:#f2bd6e;--red:#ff7482}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 Arial,sans-serif}button,input,select,textarea{font:inherit}button{cursor:pointer}
.shell{display:grid;grid-template-columns:260px 1fr;min-height:100vh}.side{position:fixed;inset:0 auto 0 0;width:260px;background:var(--side);border-right:1px solid var(--line);padding:16px 10px;overflow:auto}.brand{font-weight:900;letter-spacing:.08em;padding:10px}.brand span{color:var(--green)}.schoolname{padding:0 10px 14px;color:var(--muted);font-size:12px}.nav{display:grid;gap:4px}.nav button{border:0;background:none;color:#adc0ca;text-align:left;padding:10px 12px;border-radius:9px}.nav button:hover,.nav button.active{background:#142a36;color:white}.nav small{display:block;color:#607a88;padding:14px 10px 5px;text-transform:uppercase;letter-spacing:.12em}.main{grid-column:2;padding:22px 28px 60px;min-width:0}.top{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:22px}.top .right{display:flex;gap:8px;align-items:center;flex-wrap:wrap}
h1{font-size:26px;margin:0 0 16px}h2,h3{margin:0}.muted{color:var(--muted)}.panel{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px}.panel+.panel{margin-top:12px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.two{display:grid;grid-template-columns:1fr 1fr;gap:12px}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.stat b{display:block;font-size:27px;margin-top:6px}.section{display:flex;justify-content:space-between;align-items:center;gap:10px;margin:18px 0 10px}.actions{display:flex;gap:7px;flex-wrap:wrap}
.primary,.ghost,.mini,.danger{border-radius:9px;padding:9px 12px}.primary{border:0;background:linear-gradient(90deg,var(--green),var(--blue));color:#051018;font-weight:800}.ghost{border:1px solid var(--line);background:transparent;color:white}.mini{padding:6px 8px;border:1px solid var(--line);background:#0a1821;color:#e4eef2;font-size:12px}.danger{border:1px solid #693038;background:#281317;color:#ffb8c0}
input,select,textarea{width:100%;padding:10px;background:#07141d;border:1px solid var(--line);border-radius:8px;color:white;margin:5px 0 10px}label{font-size:12px;color:#b8c9d1}.row{display:flex;gap:10px}.row>*{flex:1;min-width:0}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.toolbar input,.toolbar select{max-width:280px;margin:0}
.table{overflow:auto}.table table{width:100%;border-collapse:collapse}.table th,.table td{padding:10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}.table th{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.06em}.badge{display:inline-block;padding:4px 7px;border-radius:10px;font-size:10px;background:#15342b;color:#73e6c6}.badge.warn{background:#342b18;color:#ffdc97}.badge.red{background:#321b20;color:#ffabb5}.empty{text-align:center;color:var(--muted);padding:24px}.modal{position:fixed;inset:0;background:#000b;display:grid;place-items:center;padding:16px;z-index:20}.modalbox{width:min(680px,96vw);max-height:90vh;overflow:auto;background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:20px}.hide{display:none!important}.toast{position:fixed;right:18px;bottom:18px;background:#102a24;border:1px solid #2c6d5c;border-radius:9px;padding:11px 14px;z-index:30}.notice{padding:11px 13px;border-left:3px solid var(--blue);background:#0b1d29;border-radius:8px}.notice.warn{border-left-color:var(--gold)}.loading{min-height:100vh;display:grid;place-items:center}.attendance-row{display:grid;grid-template-columns:1.4fr repeat(4,auto);gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line)}.attendance-row button.sel{background:#1b483b;border-color:#3b9a7f}
@media(max-width:1050px){.grid{grid-template-columns:repeat(2,1fr)}.three{grid-template-columns:1fr 1fr}}
@media(max-width:820px){.shell{grid-template-columns:74px 1fr}.side{width:74px}.brand{font-size:0}.brand span{font-size:14px}.schoolname,.nav small{display:none}.nav button{font-size:0;text-align:center}.nav button:before{content:attr(data-i);font-size:18px}.main{padding:16px 12px}.two,.three{grid-template-columns:1fr}}
@media(max-width:540px){.grid{grid-template-columns:1fr}.row{flex-direction:column}.top{align-items:flex-start;flex-direction:column}.attendance-row{grid-template-columns:1fr 1fr 1fr}.attendance-row .student{grid-column:1/-1}}
</style>
</head>
<body>
<div id="loading" class="loading"><div><b>REVOLT-X SCHOOL</b><p class="muted">Connecting to Core Revolt-X OS...</p></div></div>
<div id="app" class="shell hide">
<aside class="side"><div class="brand"><span>RX</span> SCHOOL</div><div id="schoolName" class="schoolname"></div><nav id="nav" class="nav"></nav></aside>
<main class="main"><header class="top"><div><b id="pageTitle">Dashboard</b><div id="who" class="muted"></div></div><div class="right"><span id="role" class="badge"></span><button id="refresh" class="ghost">Refresh</button></div></header><div id="content"></div></main>
</div>
<div id="modal" class="modal hide"><div class="modalbox"><div id="modalBody"></div><button id="closeModal" class="ghost">Close</button></div></div>
<div id="toast" class="toast hide"></div>
<script>
(function(){
var token='',ctx=null,current='dashboard';
var nav=[
['core','School'],['dashboard','Dashboard','⌂'],['setup','School Setup','⚙'],['students','Students','S'],['classes','Classes & Subjects','C'],['attendance','Attendance','✓'],['assessments','Assessments','A'],['fees','Fees & Payments','₵'],['timetable','Timetable','T'],['reports','Reports','R'],['staff','Staff Access','P']
];
function E(id){return document.getElementById(id)}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function toast(m,bad){var t=E('toast');t.textContent=m;t.style.borderColor=bad?'#71323a':'#2c6d5c';t.classList.remove('hide');setTimeout(function(){t.classList.add('hide')},2500)}
function badge(v){var s=String(v||'');var c=/absent|withdrawn|closed|suspended|unpaid/i.test(s)?' red':/draft|planned|late|part_paid|unmarked/i.test(s)?' warn':'';return '<span class="badge'+c+'">'+esc(s||'—')+'</span>'}
function table(rows,cols,act){if(!rows||!rows.length)return '<div class="empty">No records yet.</div>';return '<div class="table"><table><thead><tr>'+cols.map(function(c){return'<th>'+esc(c.label||c.key)+'</th>'}).join('')+(act?'<th>Actions</th>':'')+'</tr></thead><tbody>'+rows.map(function(r){return'<tr>'+cols.map(function(c){var v=c.render?c.render(r):r[c.key];return'<td>'+String(v==null?'':v)+'</td>'}).join('')+(act?'<td>'+act(r)+'</td>':'')+'</tr>'}).join('')+'</tbody></table></div>'}
async function raw(path,opt){opt=opt||{};opt.headers=Object.assign({'content-type':'application/json'},opt.headers||{},token?{authorization:'Bearer '+token}:{});var r=await fetch(path,opt),j=null;try{j=await r.json()}catch(e){}if(!r.ok)throw Error(j&&j.error&&j.error.message?j.error.message:'Request failed ('+r.status+')');return j}
function modal(html){E('modalBody').innerHTML=html;E('modal').classList.remove('hide')}function close(){E('modal').classList.add('hide');E('modalBody').innerHTML=''}E('closeModal').onclick=close;
function field(f,v){v=v==null?'':v;if(f.type==='select')return'<label>'+esc(f.label)+'</label><select data-f="'+f.key+'">'+(f.options||[]).map(function(o){var value=typeof o==='string'?o:o.value,label=typeof o==='string'?o:o.label;return'<option value="'+esc(value)+'"'+(String(value)===String(v)?' selected':'')+'>'+esc(label)+'</option>'}).join('')+'</select>';if(f.type==='textarea')return'<label>'+esc(f.label)+'</label><textarea rows="'+(f.rows||4)+'" data-f="'+f.key+'">'+esc(v)+'</textarea>';return'<label>'+esc(f.label)+'</label><input type="'+(f.type||'text')+'" data-f="'+f.key+'" value="'+esc(v)+'">'}
function form(title,fields,vals,save){vals=vals||{};modal('<h2 style="margin-bottom:15px">'+esc(title)+'</h2>'+fields.map(function(f){return field(f,vals[f.key])}).join('')+'<button id="saveModal" class="primary" style="width:100%;margin:8px 0 12px">Save</button>');E('saveModal').onclick=async function(){var v={};E('modalBody').querySelectorAll('[data-f]').forEach(function(x){v[x.dataset.f]=x.value});try{E('saveModal').disabled=true;await save(v);close();toast('Saved');await page(current)}catch(e){toast(e.message,true);E('saveModal').disabled=false}}}
function confirmDo(message,action){if(!confirm(message))return;Promise.resolve().then(action).then(function(){toast('Action completed');return page(current)}).catch(function(e){toast(e.message,true)})}
async function boot(){
 try{
   token=sessionStorage.getItem('rx_school_token')||'';
   if(!token){var p=await fetch('/api/auth/preview',{method:'POST'});var j=await p.json();if(!p.ok)throw Error(j.error&&j.error.message||'Core OS access failed');token=j.accessToken;sessionStorage.setItem('rx_school_token',token)}
   ctx=await raw('/api/context');
   if(!ctx.profile){await raw('/api/school/bootstrap',{method:'POST',body:JSON.stringify({schoolName:ctx.core.organisation_name})});ctx=await raw('/api/context')}
   E('schoolName').textContent=ctx.profile.school_name;E('who').textContent=ctx.core.first_name+' '+ctx.core.last_name+' • '+ctx.core.organisation_name;E('role').textContent=ctx.schoolRole.replace('_',' ');
   E('nav').innerHTML=nav.map(function(n){return n[0]==='core'?'<small>'+n[1]+'</small>':'<button data-p="'+n[0]+'" data-i="'+n[2]+'">'+n[1]+'</button>'}).join('');
   E('nav').onclick=function(e){var b=e.target.closest('button[data-p]');if(b)page(b.dataset.p)};E('refresh').onclick=function(){page(current)};
   E('loading').classList.add('hide');E('app').classList.remove('hide');await page('dashboard')
 }catch(e){E('loading').innerHTML='<div><h2>School workspace unavailable</h2><p>'+esc(e.message)+'</p></div>'}
}
async function page(p){
 current=p;document.querySelectorAll('#nav button').forEach(function(b){b.classList.toggle('active',b.dataset.p===p)});E('pageTitle').textContent=(nav.find(function(n){return n[0]===p})||['',p])[1];E('content').innerHTML='<p class="muted">Loading...</p>';
 try{
 if(p==='dashboard'){
   var d=await raw('/api/dashboard');E('content').innerHTML='<h1>School Dashboard</h1><div class="grid">'+[['Students',d.students],['Classes',d.classes],['Subjects',d.subjects],['School staff',d.staff_users],['Present today',d.present_today],['Absent today',d.absent_today],['Fees billed','GHS '+Number(d.fees_billed||0).toFixed(2)],['Payments received','GHS '+Number(d.payments_received||0).toFixed(2)]].map(function(x){return'<div class="panel stat"><span class="muted">'+esc(x[0])+'</span><b>'+esc(x[1])+'</b></div>'}).join('')+'</div><div class="two" style="margin-top:12px"><div class="panel"><h3>Academic year</h3><p>'+(d.activeYear?'<b>'+esc(d.activeYear.name)+'</b><br>'+esc(d.activeYear.start_date)+' to '+esc(d.activeYear.end_date):'<span class="muted">No active academic year</span>')+'</p></div><div class="panel"><h3>Current term</h3><p>'+(d.activeTerm?'<b>'+esc(d.activeTerm.name)+'</b><br>'+esc(d.activeTerm.start_date)+' to '+esc(d.activeTerm.end_date):'<span class="muted">No active term</span>')+'</p></div></div>'
 }
 else if(p==='setup'){
   var rs=await Promise.all([raw('/api/school/profile'),raw('/api/academic-years'),raw('/api/terms'),raw('/api/grade-levels')]);var prof=rs[0],years=rs[1],terms=rs[2],grades=rs[3];
   E('content').innerHTML='<div class="section"><h1>School Setup</h1><button id="editProfile" class="primary">Edit profile</button></div><div class="panel"><div class="two"><div><b>'+esc(prof.school_name)+'</b><p class="muted">'+esc(prof.motto||'No motto set')+'</p></div><div><p>'+esc(prof.phone||'')+'<br>'+esc(prof.email||'')+'<br>'+esc(prof.address||'')+'</p></div></div></div>'+
   '<div class="section"><h2>Academic Years</h2><button id="addYear" class="ghost">Add year</button></div><div class="panel">'+table(years,[{key:'name'},{key:'start_date',label:'Starts'},{key:'end_date',label:'Ends'},{key:'status',render:function(r){return badge(r.status)}}],function(r){return (r.status!=='active'?'<button class="mini" data-activate-year="'+r.id+'">Activate</button>':'')+'<button class="mini" data-edit-year="'+r.id+'">Edit</button><button class="mini danger" data-delete-year="'+r.id+'">Delete</button>'})+'</div>'+
   '<div class="section"><h2>Terms</h2><button id="addTerm" class="ghost">Add term</button></div><div class="panel">'+table(terms,[{key:'name'},{key:'term_no',label:'Term'},{key:'start_date',label:'Starts'},{key:'end_date',label:'Ends'},{key:'status',render:function(r){return badge(r.status)}}],function(r){return (r.status!=='active'?'<button class="mini" data-activate-term="'+r.id+'">Activate</button>':'')+'<button class="mini" data-edit-term="'+r.id+'">Edit</button><button class="mini danger" data-delete-term="'+r.id+'">Delete</button>'})+'</div>'+
   '<div class="section"><h2>Grade Levels</h2></div><div class="panel">'+table(grades,[{key:'code'},{key:'name'},{key:'stage',render:function(r){return badge(r.stage)}},{key:'is_active',label:'Status',render:function(r){return badge(r.is_active?'active':'inactive')}}],function(r){return '<button class="mini" data-edit-grade="'+r.id+'">Edit</button>'})+'</div>';
   E('editProfile').onclick=function(){form('Edit school profile',[{key:'schoolName',label:'School name'},{key:'shortName',label:'Short name'},{key:'motto',label:'Motto'},{key:'phone',label:'Phone'},{key:'email',label:'Email',type:'email'},{key:'address',label:'Address',type:'textarea'}],{schoolName:prof.school_name,shortName:prof.short_name||'',motto:prof.motto||'',phone:prof.phone||'',email:prof.email||'',address:prof.address||''},function(v){return raw('/api/school/profile',{method:'PATCH',body:JSON.stringify(v)})})};
   E('addYear').onclick=function(){form('New academic year',[{key:'name',label:'Name e.g. 2027/2028'},{key:'startDate',label:'Start date',type:'date'},{key:'endDate',label:'End date',type:'date'}],{},function(v){return raw('/api/academic-years',{method:'POST',body:JSON.stringify(v)})})};
   E('addTerm').onclick=function(){form('New term',[{key:'academicYearId',label:'Academic year',type:'select',options:years.map(function(y){return{value:y.id,label:y.name}})},{key:'termNo',label:'Term number',type:'select',options:['1','2','3']},{key:'name',label:'Term name'},{key:'startDate',label:'Start date',type:'date'},{key:'endDate',label:'End date',type:'date'}],{},function(v){return raw('/api/terms',{method:'POST',body:JSON.stringify({academicYearId:v.academicYearId,termNo:Number(v.termNo),name:v.name,startDate:v.startDate,endDate:v.endDate})})})};
   E('content').onclick=async function(e){
     var id=e.target.dataset.activateYear;if(id){await raw('/api/academic-years/'+id+'/activate',{method:'POST',body:'{}'});toast('Academic year activated');return page('setup')}
     id=e.target.dataset.editYear;if(id){var y=years.find(function(x){return x.id===id});return form('Edit academic year',[{key:'name',label:'Name'},{key:'startDate',label:'Start date',type:'date'},{key:'endDate',label:'End date',type:'date'}],{name:y.name,startDate:String(y.start_date).slice(0,10),endDate:String(y.end_date).slice(0,10)},function(v){return raw('/api/academic-years/'+id,{method:'PATCH',body:JSON.stringify(v)})})}
     id=e.target.dataset.deleteYear;if(id){return confirmDo('Delete this academic year? This is only allowed when it has no student enrolments.',function(){return raw('/api/academic-years/'+id,{method:'DELETE'})})}
     id=e.target.dataset.activateTerm;if(id){await raw('/api/terms/'+id+'/activate',{method:'POST',body:'{}'});toast('Term activated');return page('setup')}
     id=e.target.dataset.editTerm;if(id){var t=terms.find(function(x){return x.id===id});return form('Edit term',[{key:'name',label:'Term name'},{key:'startDate',label:'Start date',type:'date'},{key:'endDate',label:'End date',type:'date'}],{name:t.name,startDate:String(t.start_date).slice(0,10),endDate:String(t.end_date).slice(0,10)},function(v){return raw('/api/terms/'+id,{method:'PATCH',body:JSON.stringify(v)})})}
     id=e.target.dataset.deleteTerm;if(id){return confirmDo('Delete this term and its related records?',function(){return raw('/api/terms/'+id,{method:'DELETE'})})}
     id=e.target.dataset.editGrade;if(id){var g=grades.find(function(x){return x.id===id});return form('Edit grade level',[{key:'name',label:'Name'},{key:'isActive',label:'Status',type:'select',options:[{value:'true',label:'Active'},{value:'false',label:'Inactive'}]}],{name:g.name,isActive:String(g.is_active)},function(v){return raw('/api/grade-levels/'+id,{method:'PATCH',body:JSON.stringify({name:v.name,isActive:v.isActive==='true'})})})}
   }
 }
 else if(p==='classes'){
   var rr=await Promise.all([raw('/api/academic-years'),raw('/api/grade-levels'),raw('/api/classes'),raw('/api/subjects')]);var ys=rr[0],gs=rr[1],cls=rr[2],subs=rr[3];
   E('content').innerHTML='<div class="section"><h1>Classes & Subjects</h1><div class="actions"><button id="addClass" class="primary">Add class</button><button id="addSubject" class="ghost">Add subject</button></div></div><div class="two"><div class="panel"><h3>Classes</h3>'+table(cls,[{key:'name'},{key:'grade_name',label:'Grade'},{key:'stream'}])+'</div><div class="panel"><h3>Subjects</h3>'+table(subs,[{key:'code'},{key:'name'},{key:'stage',render:function(r){return badge(r.stage)}}])+'</div></div>';
   E('addClass').onclick=function(){form('Create class',[{key:'academicYearId',label:'Academic year',type:'select',options:ys.map(function(y){return{value:y.id,label:y.name}})},{key:'gradeLevelId',label:'Grade level',type:'select',options:gs.map(function(g){return{value:g.id,label:g.name}})},{key:'name',label:'Class name'},{key:'stream',label:'Stream'},{key:'capacity',label:'Capacity',type:'number'}],{},function(v){return raw('/api/classes',{method:'POST',body:JSON.stringify({academicYearId:v.academicYearId,gradeLevelId:v.gradeLevelId,name:v.name,stream:v.stream||undefined,capacity:v.capacity?Number(v.capacity):undefined})})})};
   E('addSubject').onclick=function(){form('Add subject',[{key:'code',label:'Code'},{key:'name',label:'Subject name'},{key:'stage',label:'Stage',type:'select',options:['primary','jhs','both']}],{stage:'both'},function(v){return raw('/api/subjects',{method:'POST',body:JSON.stringify(v)})})}
 }
 else if(p==='students'){
   var rr=await Promise.all([raw('/api/students'),raw('/api/academic-years'),raw('/api/classes')]);var students=rr[0],years=rr[1],classes=rr[2];
   E('content').innerHTML='<div class="section"><h1>Students</h1><button id="addStudent" class="primary">Admit student</button></div><div class="toolbar"><input id="studentSearch" placeholder="Search name or admission number"><button id="searchStudent" class="ghost">Search</button></div><div class="panel" id="studentTable">'+table(students,[{key:'admission_no',label:'Admission No.'},{key:'first_name',label:'Student',render:function(r){return esc(r.first_name+' '+r.last_name)}},{key:'grade_name',label:'Grade'},{key:'classroom_name',label:'Class'},{key:'status',render:function(r){return badge(r.status)}}],function(r){return'<button class="mini" data-view-student="'+r.id+'">Open</button>'})+'</div>';
   E('addStudent').onclick=function(){form('Admit student',[{key:'admissionNo',label:'Admission number'},{key:'firstName',label:'First name'},{key:'middleName',label:'Middle name'},{key:'lastName',label:'Last name'},{key:'sex',label:'Sex',type:'select',options:[{value:'',label:'Not set'},'male','female']},{key:'dateOfBirth',label:'Date of birth',type:'date'}],{},function(v){var b={admissionNo:v.admissionNo,firstName:v.firstName,lastName:v.lastName};if(v.middleName)b.middleName=v.middleName;if(v.sex)b.sex=v.sex;if(v.dateOfBirth)b.dateOfBirth=v.dateOfBirth;return raw('/api/students',{method:'POST',body:JSON.stringify(b)})})};
   async function search(){var q=E('studentSearch').value.trim();students=await raw('/api/students'+(q?'?q='+encodeURIComponent(q):''));E('studentTable').innerHTML=table(students,[{key:'admission_no',label:'Admission No.'},{key:'first_name',label:'Student',render:function(r){return esc(r.first_name+' '+r.last_name)}},{key:'grade_name',label:'Grade'},{key:'classroom_name',label:'Class'},{key:'status',render:function(r){return badge(r.status)}}],function(r){return'<button class="mini" data-view-student="'+r.id+'">Open</button>'})}E('searchStudent').onclick=search;E('studentSearch').onkeydown=function(e){if(e.key==='Enter')search()};
   E('content').onclick=async function(e){var id=e.target.dataset.viewStudent;if(!id)return;var s=await raw('/api/students/'+id);var y=years.find(function(x){return x.status==='active'})||years[0];var opts=classes.filter(function(c){return !y||c.academic_year_id===y.id}).map(function(c){return'<option value="'+c.id+'">'+esc(c.name)+'</option>'}).join('');modal('<h2>'+esc(s.first_name+' '+s.last_name)+'</h2><p class="muted">'+esc(s.admission_no)+'</p><h3>Current/Previous Enrolments</h3>'+table(s.enrolments,[{key:'academic_year',label:'Year'},{key:'grade_name',label:'Grade'},{key:'classroom_name',label:'Class'},{key:'status',render:function(r){return badge(r.status)}}])+'<h3 style="margin-top:14px">Enrol in class</h3><select id="enrolClass">'+opts+'</select><button id="enrolBtn" class="primary">Enrol</button><h3 style="margin-top:18px">Guardians</h3>'+table(s.guardians,[{key:'first_name',label:'Name',render:function(r){return esc(r.first_name+' '+r.last_name)}},{key:'relationship'},{key:'phone'}])+'<button id="addGuardian" class="ghost">Add guardian</button>');E('enrolBtn').onclick=async function(){if(!y)return toast('Create an academic year first',true);await raw('/api/enrolments',{method:'POST',body:JSON.stringify({studentId:id,academicYearId:y.id,classroomId:E('enrolClass').value})});toast('Student enrolled');close();page('students')};E('addGuardian').onclick=function(){close();form('Add guardian',[{key:'firstName',label:'First name'},{key:'lastName',label:'Last name'},{key:'phone',label:'Phone'},{key:'email',label:'Email',type:'email'},{key:'relationship',label:'Relationship'},{key:'isPrimary',label:'Primary guardian',type:'select',options:[{value:'false',label:'No'},{value:'true',label:'Yes'}]}],{isPrimary:'false'},function(v){return raw('/api/students/'+id+'/guardians',{method:'POST',body:JSON.stringify({firstName:v.firstName,lastName:v.lastName,phone:v.phone,email:v.email||undefined,relationship:v.relationship,isPrimary:v.isPrimary==='true'})})})}}
 }
 else if(p==='attendance'){
   var classes=await raw('/api/classes');E('content').innerHTML='<h1>Attendance</h1><div class="toolbar"><select id="attClass">'+classes.map(function(c){return'<option value="'+c.id+'">'+esc(c.name)+'</option>'}).join('')+'</select><input id="attDate" type="date" value="'+new Date().toISOString().slice(0,10)+'"><button id="loadAtt" class="primary">Load class</button></div><div id="attPanel" class="panel"><div class="empty">Choose a class and date.</div></div>';
   E('loadAtt').onclick=async function(){var cid=E('attClass').value,date=E('attDate').value,rows=await raw('/api/attendance?classroomId='+cid+'&date='+date);E('attPanel').innerHTML=rows.length?rows.map(function(r){return'<div class="attendance-row" data-student="'+r.student_id+'"><div class="student"><b>'+esc(r.first_name+' '+r.last_name)+'</b><div class="muted">'+esc(r.admission_no)+'</div></div>'+['present','absent','late','excused'].map(function(s){return'<button class="mini '+(r.attendance_status===s?'sel':'')+'" data-status="'+s+'">'+s+'</button>'}).join('')+'</div>'}).join('')+'<button id="saveAtt" class="primary" style="margin-top:12px">Save attendance</button>':'<div class="empty">No students enrolled in this class.</div>';E('attPanel').onclick=function(e){var b=e.target.closest('[data-status]');if(b){var row=b.closest('[data-student]');row.querySelectorAll('[data-status]').forEach(function(x){x.classList.remove('sel')});b.classList.add('sel')}};var save=E('saveAtt');if(save)save.onclick=async function(){var records=[];E('attPanel').querySelectorAll('[data-student]').forEach(function(row){var s=row.querySelector('.sel');if(s)records.push({studentId:row.dataset.student,status:s.dataset.status})});if(!records.length)return toast('Mark at least one student',true);await raw('/api/attendance/mark',{method:'POST',body:JSON.stringify({classroomId:cid,date:date,records:records})});toast('Attendance saved')}}
 }
 else if(p==='assessments'){
   var rr=await Promise.all([raw('/api/academic-years'),raw('/api/terms'),raw('/api/classes'),raw('/api/subjects'),raw('/api/assessments')]);var years=rr[0],terms=rr[1],classes=rr[2],subs=rr[3],as=rr[4];
   E('content').innerHTML='<div class="section"><h1>Assessments</h1><button id="addAssess" class="primary">New assessment</button></div><div class="panel">'+table(as,[{key:'name'},{key:'subject_name',label:'Subject'},{key:'classroom_name',label:'Class'},{key:'assessment_type',label:'Type'},{key:'max_score',label:'Max'}],function(r){return'<button class="mini" data-score="'+r.id+'">Enter scores</button>'})+'</div>';
   E('addAssess').onclick=function(){form('New assessment',[{key:'academicYearId',label:'Academic year',type:'select',options:years.map(function(x){return{value:x.id,label:x.name}})},{key:'termId',label:'Term',type:'select',options:terms.map(function(x){return{value:x.id,label:x.name}})},{key:'classroomId',label:'Class',type:'select',options:classes.map(function(x){return{value:x.id,label:x.name}})},{key:'subjectId',label:'Subject',type:'select',options:subs.map(function(x){return{value:x.id,label:x.name}})},{key:'name',label:'Assessment name'},{key:'assessmentType',label:'Type',type:'select',options:['classwork','homework','project','test','exam','other']},{key:'maxScore',label:'Maximum score',type:'number'},{key:'assessmentDate',label:'Date',type:'date'}],{assessmentType:'test',maxScore:'100'},function(v){return raw('/api/assessments',{method:'POST',body:JSON.stringify({academicYearId:v.academicYearId,termId:v.termId,classroomId:v.classroomId,subjectId:v.subjectId,name:v.name,assessmentType:v.assessmentType,maxScore:Number(v.maxScore),assessmentDate:v.assessmentDate||undefined})})})};
   E('content').onclick=async function(e){var id=e.target.dataset.score;if(!id)return;var x=await raw('/api/assessments/'+id+'/scores');modal('<h2>'+esc(x.assessment.name)+'</h2><p class="muted">Maximum score: '+esc(x.assessment.max_score)+'</p>'+x.students.map(function(s){return'<div class="row"><div><b>'+esc(s.first_name+' '+s.last_name)+'</b><div class="muted">'+esc(s.admission_no)+'</div></div><div><input type="number" min="0" max="'+esc(x.assessment.max_score)+'" data-score-student="'+s.student_id+'" value="'+esc(s.score==null?'':s.score)+'"></div></div>'}).join('')+'<button id="saveScores" class="primary">Save scores</button>');E('saveScores').onclick=async function(){var scores=[];E('modalBody').querySelectorAll('[data-score-student]').forEach(function(inp){if(inp.value!=='')scores.push({studentId:inp.dataset.scoreStudent,score:Number(inp.value)})});if(!scores.length)return toast('Enter at least one score',true);await raw('/api/assessments/'+id+'/scores',{method:'POST',body:JSON.stringify({scores:scores})});toast('Scores saved');close()}}
 }
 else if(p==='fees'){
   var rr=await Promise.all([raw('/api/academic-years'),raw('/api/terms'),raw('/api/grade-levels'),raw('/api/classes'),raw('/api/fee-items'),raw('/api/students')]);var years=rr[0],terms=rr[1],grades=rr[2],classes=rr[3],fees=rr[4],students=rr[5];
   E('content').innerHTML='<div class="section"><h1>Fees & Payments</h1><div class="actions"><button id="newFee" class="primary">Create fee</button><button id="recordPay" class="ghost">Record payment</button></div></div><div class="panel">'+table(fees,[{key:'name'},{key:'grade_name',label:'Grade'},{key:'term_name',label:'Term'},{key:'amount',render:function(r){return'GHS '+Number(r.amount).toFixed(2)}}],function(r){return'<button class="mini" data-assign-fee="'+r.id+'">Assign</button>'})+'</div>';
   E('newFee').onclick=function(){form('Create fee item',[{key:'academicYearId',label:'Academic year',type:'select',options:years.map(function(x){return{value:x.id,label:x.name}})},{key:'termId',label:'Term',type:'select',options:[{value:'',label:'Whole year'}].concat(terms.map(function(x){return{value:x.id,label:x.name}}))},{key:'gradeLevelId',label:'Grade',type:'select',options:[{value:'',label:'All grades'}].concat(grades.map(function(x){return{value:x.id,label:x.name}}))},{key:'name',label:'Fee name'},{key:'amount',label:'Amount',type:'number'}],{},function(v){return raw('/api/fee-items',{method:'POST',body:JSON.stringify({academicYearId:v.academicYearId,termId:v.termId||undefined,gradeLevelId:v.gradeLevelId||undefined,name:v.name,amount:Number(v.amount)})})})};
   E('recordPay').onclick=function(){form('Record payment',[{key:'studentId',label:'Student',type:'select',options:students.map(function(s){return{value:s.id,label:s.first_name+' '+s.last_name+' ('+s.admission_no+')'}})},{key:'amount',label:'Amount',type:'number'},{key:'paymentMethod',label:'Method',type:'select',options:['cash','mobile_money','bank','card','other']},{key:'reference',label:'Reference'}],{paymentMethod:'cash'},function(v){return raw('/api/payments',{method:'POST',body:JSON.stringify({studentId:v.studentId,amount:Number(v.amount),paymentMethod:v.paymentMethod,reference:v.reference||undefined})})})};
   E('content').onclick=function(e){var id=e.target.dataset.assignFee;if(!id)return;form('Assign fee',[{key:'classroomId',label:'Class',type:'select',options:classes.map(function(c){return{value:c.id,label:c.name}})}],{},function(v){return raw('/api/fees/assign',{method:'POST',body:JSON.stringify({feeItemId:id,classroomId:v.classroomId})})})}
 }
 else if(p==='timetable'){
   var rr=await Promise.all([raw('/api/academic-years'),raw('/api/terms'),raw('/api/classes'),raw('/api/subjects'),raw('/api/timetable')]);var years=rr[0],terms=rr[1],classes=rr[2],subs=rr[3],tt=rr[4];
   E('content').innerHTML='<div class="section"><h1>Timetable</h1><button id="addSlot" class="primary">Add period</button></div><div class="panel">'+table(tt,[{key:'day_of_week',label:'Day',render:function(r){return['','Mon','Tue','Wed','Thu','Fri'][r.day_of_week]}},{key:'start_time',label:'Start'},{key:'end_time',label:'End'},{key:'classroom_name',label:'Class'},{key:'subject_name',label:'Subject'},{key:'room'}])+'</div>';
   E('addSlot').onclick=function(){form('Add timetable period',[{key:'academicYearId',label:'Academic year',type:'select',options:years.map(function(x){return{value:x.id,label:x.name}})},{key:'termId',label:'Term',type:'select',options:[{value:'',label:'No specific term'}].concat(terms.map(function(x){return{value:x.id,label:x.name}}))},{key:'classroomId',label:'Class',type:'select',options:classes.map(function(x){return{value:x.id,label:x.name}})},{key:'subjectId',label:'Subject',type:'select',options:subs.map(function(x){return{value:x.id,label:x.name}})},{key:'dayOfWeek',label:'Day',type:'select',options:[{value:'1',label:'Monday'},{value:'2',label:'Tuesday'},{value:'3',label:'Wednesday'},{value:'4',label:'Thursday'},{value:'5',label:'Friday'}]},{key:'startTime',label:'Start time',type:'time'},{key:'endTime',label:'End time',type:'time'},{key:'room',label:'Room'}],{},function(v){return raw('/api/timetable',{method:'POST',body:JSON.stringify({academicYearId:v.academicYearId,termId:v.termId||undefined,classroomId:v.classroomId,subjectId:v.subjectId,dayOfWeek:Number(v.dayOfWeek),startTime:v.startTime,endTime:v.endTime,room:v.room||undefined})})})}
 }
 else if(p==='reports'){
   var rr=await Promise.all([raw('/api/students'),raw('/api/terms')]);var students=rr[0],terms=rr[1];E('content').innerHTML='<h1>Reports</h1><div class="panel"><div class="row"><div><label>Student</label><select id="reportStudent">'+students.map(function(s){return'<option value="'+s.id+'">'+esc(s.first_name+' '+s.last_name+' ('+s.admission_no+')')+'</option>'}).join('')+'</select></div><div><label>Term</label><select id="reportTerm">'+terms.map(function(t){return'<option value="'+t.id+'">'+esc(t.name)+'</option>'}).join('')+'</select></div></div><button id="loadReport" class="primary">Generate report card</button></div><div id="reportOut"></div>';
   E('loadReport').onclick=async function(){var r=await raw('/api/report-cards/'+E('reportStudent').value+'?termId='+E('reportTerm').value);E('reportOut').innerHTML='<div class="panel" style="margin-top:12px"><h2>'+esc(r.student.first_name+' '+r.student.last_name)+'</h2><p class="muted">'+esc(r.student.admission_no)+'</p><h3>Academic results</h3>'+table(r.subjects,[{key:'subject_name',label:'Subject'},{key:'percentage',label:'Average %'},{key:'assessment_count',label:'Assessments'}])+'<h3 style="margin-top:15px">Attendance</h3>'+table(r.attendance,[{key:'status',render:function(x){return badge(x.status)}},{key:'count'}])+'<button id="printReport" class="ghost">Print report</button></div>';E('printReport').onclick=function(){window.print()}}
 }
 else if(p==='staff'){
   var rr=await Promise.all([raw('/api/staff/core-users'),raw('/api/staff/module-memberships')]);var users=rr[0],m=rr[1];E('content').innerHTML='<div class="section"><h1>Staff Access</h1><button id="assignStaff" class="primary">Assign school role</button></div><div class="notice">Staff identities come from Core Revolt-X OS. This school application only assigns school-specific responsibilities.</div><div class="panel" style="margin-top:12px">'+table(users,[{key:'first_name',label:'Staff',render:function(u){return esc(u.first_name+' '+u.last_name)}},{key:'email'},{key:'job_title',label:'Job title'},{key:'membership_status',label:'Core status',render:function(u){return badge(u.membership_status)}}])+'</div><div class="section"><h2>School module roles</h2></div><div class="panel">'+table(m,[{key:'os_user_id',label:'OS user ID'},{key:'role',render:function(x){return badge(x.role)}},{key:'status',render:function(x){return badge(x.status)}}])+'</div>';
   E('assignStaff').onclick=function(){form('Assign school role',[{key:'osUserId',label:'Core OS user',type:'select',options:users.map(function(u){return{value:u.id,label:u.first_name+' '+u.last_name+' ('+u.email+')'}})},{key:'role',label:'School role',type:'select',options:['school_admin','headteacher','teacher','bursar','registrar']},{key:'status',label:'Status',type:'select',options:['active','suspended']}],{role:'teacher',status:'active'},function(v){return raw('/api/staff/module-memberships',{method:'POST',body:JSON.stringify(v)})})}
 }
 }catch(e){E('content').innerHTML='<div class="panel"><h3>Could not load this area</h3><p class="muted">'+esc(e.message)+'</p><button class="ghost" id="retry">Retry</button></div>';E('retry').onclick=function(){page(p)}}
}
boot();
})();
</script>
</body></html>`;
