export const schoolFrontend=`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Revolt-X School</title>
<style>
:root{--bg:#071018;--side:#0a1721;--panel:#0e1e29;--panel2:#122733;--line:#203844;--text:#f4f8fa;--muted:#90a8b5;--green:#45ddb2;--blue:#48a9ff;--gold:#f2bd6e;--red:#ff7482}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 Arial,sans-serif}button,input,select,textarea{font:inherit}button{cursor:pointer}
.shell{display:grid;grid-template-columns:260px 1fr;min-height:100vh}.side{position:fixed;inset:0 auto 0 0;width:260px;background:var(--side);border-right:1px solid var(--line);padding:16px 10px;overflow:auto}.brand{font-weight:900;letter-spacing:.08em;padding:10px}.brand span{color:var(--green)}.schoolname{padding:0 10px 14px;color:var(--muted);font-size:12px}.nav{display:grid;gap:4px}.nav button{border:0;background:none;color:#adc0ca;text-align:left;padding:10px 12px;border-radius:9px}.nav button:hover,.nav button.active{background:#142a36;color:white}.nav small{display:block;color:#607a88;padding:14px 10px 5px;text-transform:uppercase;letter-spacing:.12em}.main{grid-column:2;padding:22px 28px 60px;min-width:0}.top{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:22px}.top .right{display:flex;gap:8px;align-items:center;flex-wrap:wrap}
h1{font-size:26px;margin:0 0 16px}h2,h3{margin:0}.muted{color:var(--muted)}.panel{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px}.panel+.panel{margin-top:12px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.two{display:grid;grid-template-columns:1fr 1fr;gap:12px}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.stat b{display:block;font-size:27px;margin-top:6px}.section{display:flex;justify-content:space-between;align-items:center;gap:10px;margin:18px 0 10px}.actions{display:flex;gap:7px;flex-wrap:wrap}
.primary,.ghost,.mini,.danger{border-radius:9px;padding:9px 12px}.primary{border:0;background:linear-gradient(90deg,var(--green),var(--blue));color:#051018;font-weight:800}.ghost{border:1px solid var(--line);background:transparent;color:white}.mini{padding:6px 8px;border:1px solid var(--line);background:#0a1821;color:#e4eef2;font-size:12px}.danger{border:1px solid #693038;background:#281317;color:#ffb8c0}
input,select,textarea{width:100%;padding:10px;background:#07141d;border:1px solid var(--line);border-radius:8px;color:white;margin:5px 0 10px}label{font-size:12px;color:#b8c9d1}.row{display:flex;gap:10px}.row>*{flex:1;min-width:0}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.toolbar input,.toolbar select{max-width:280px;margin:0}
.table{overflow:auto}.table table{width:100%;border-collapse:collapse}.table th,.table td{padding:10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}.table th{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.06em}.badge{display:inline-block;padding:4px 7px;border-radius:10px;font-size:10px;background:#15342b;color:#73e6c6}.badge.warn{background:#342b18;color:#ffdc97}.badge.red{background:#321b20;color:#ffabb5}.empty{text-align:center;color:var(--muted);padding:24px}.modal{position:fixed;inset:0;background:#000b;display:grid;place-items:center;padding:16px;z-index:20}.modalbox{width:min(680px,96vw);max-height:90vh;overflow:auto;background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:20px}.hide{display:none!important}.toast{position:fixed;right:18px;bottom:18px;background:#102a24;border:1px solid #2c6d5c;border-radius:9px;padding:11px 14px;z-index:30}.notice{padding:11px 13px;border-left:3px solid var(--blue);background:#0b1d29;border-radius:8px}.notice.warn{border-left-color:var(--gold)}.loading{min-height:100vh;display:grid;place-items:center}.attendance-row{display:grid;grid-template-columns:1.4fr repeat(4,auto);gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line)}.attendance-row button.sel{background:#1b483b;border-color:#3b9a7f}

.primary-lite{border-color:#2c6d5c!important;background:#102a24!important;color:#8ff0d4!important}
.academic-toolbar{display:flex;align-items:end;gap:12px}.academic-toolbar label{min-width:110px}.academic-toolbar select{max-width:300px;margin:0}
.academic-manager{display:grid;grid-template-columns:290px minmax(0,1fr);gap:12px;margin-top:12px}.class-browser{min-height:560px}.class-card{width:100%;display:flex;justify-content:space-between;gap:10px;text-align:left;padding:12px;margin:7px 0;border:1px solid var(--line);border-radius:10px;background:#091821;color:white}.class-card:hover,.class-card.selected{border-color:#3b8f7a;background:#102821}.class-card small{display:block;color:var(--muted);margin-top:4px}.class-count{text-align:right;color:#8eabb8;font-size:11px;white-space:nowrap}.class-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;padding-bottom:14px;border-bottom:1px solid var(--line)}.class-head h2{font-size:24px;margin:7px 0 0}.teacher-box{display:grid;grid-template-columns:1fr minmax(260px,420px);align-items:center;gap:18px;padding:16px 0;border-bottom:1px solid var(--line)}.teacher-assign{display:flex;gap:8px;align-items:center}.teacher-assign select{margin:0}.curriculum-list{display:grid;gap:8px}.curriculum-row{display:grid;grid-template-columns:minmax(150px,.8fr) minmax(220px,1.5fr) auto;gap:12px;align-items:center;padding:12px;background:#091821;border:1px solid var(--line);border-radius:10px}.curriculum-row small{display:block;color:var(--muted);margin-top:4px}.teacher-chip-area{display:flex;gap:6px;flex-wrap:wrap}.teacher-chip{display:inline-flex;align-items:center;gap:6px;background:#12352d;color:#8ce9cf;border:1px solid #28624f;border-radius:14px;padding:5px 8px;font-size:11px}.teacher-chip button{border:0;background:none;color:#d8fff4;padding:0;font-size:15px}.section.compact{margin:0 0 10px}
.student360-head{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:14px;flex-wrap:wrap}.student360-identity{display:flex;align-items:center;gap:14px;flex:1;min-width:260px}.student360-identity h1{margin:3px 0 0}.student-avatar{width:64px;height:64px;border-radius:18px;display:grid;place-items:center;font-size:24px;font-weight:900;background:linear-gradient(145deg,#123b33,#143657);border:1px solid #315a67}.student360-stats{margin-bottom:12px}.student360-stats small{color:var(--muted)}.student360-columns{align-items:start}.info-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.info-grid div{padding:9px;background:#091821;border:1px solid var(--line);border-radius:9px}.info-grid span{display:block;color:var(--muted);font-size:11px}.info-grid b{display:block;margin-top:3px}.mini-stats{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.mini-stats span{flex:1;min-width:100px;background:#091821;border:1px solid var(--line);border-radius:9px;padding:9px;color:var(--muted);font-size:11px}.mini-stats b{display:block;color:white;font-size:17px}.timeline{display:grid;gap:9px}.timeline div{display:flex;justify-content:space-between;gap:10px;border-left:2px solid #315b68;padding:4px 0 4px 10px}.timeline span{color:var(--muted);font-size:11px}
.report-controls{margin-bottom:12px}.report-card{background:white;color:#172027;border-radius:12px;padding:28px;max-width:980px;margin:16px auto;box-shadow:0 10px 40px #0004}.report-school-head{display:grid;grid-template-columns:74px 1fr auto;gap:16px;align-items:center;border-bottom:3px solid #172027;padding-bottom:16px}.report-logo{width:64px;height:64px;border-radius:16px;background:#102a24;color:#45ddb2;display:grid;place-items:center;font-weight:900;font-size:21px}.report-school-head h1{margin:0;font-size:24px}.report-school-head p{margin:4px 0}.report-school-head small{color:#5d6d75}.report-term{text-align:right;display:grid;gap:3px}.report-term b{font-size:16px}.report-term span{color:#52626a}.report-student-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;padding:16px 0}.report-student-grid div{border:1px solid #d9e0e4;border-radius:8px;padding:9px}.report-student-grid span{display:block;color:#6c7a82;font-size:10px;text-transform:uppercase}.report-student-grid b{display:block;margin-top:2px}.report-summary{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;background:#f3f7f8;border-radius:10px;padding:10px}.report-summary div{text-align:center;padding:7px}.report-summary span{display:block;font-size:10px;color:#687780;text-transform:uppercase}.report-summary b{font-size:18px}.report-section{margin-top:18px}.report-section h3{font-size:14px;text-transform:uppercase;letter-spacing:.05em;margin-bottom:8px}.report-table{width:100%;border-collapse:collapse}.report-table th,.report-table td{padding:9px;border:1px solid #d9e0e4;text-align:left}.report-table th{background:#f2f6f7;font-size:10px;text-transform:uppercase}.report-attendance{display:flex;gap:8px;flex-wrap:wrap}.report-attendance span{border:1px solid #d9e0e4;border-radius:8px;padding:8px 12px;min-width:120px}.report-attendance b{font-size:16px;margin-right:4px}.report-comments{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:18px}.report-comments>div{border:1px solid #d9e0e4;border-radius:8px;padding:12px}.report-comments h4{margin:0 0 4px;font-size:11px;text-transform:uppercase;color:#60717a}.report-comments p{min-height:20px;margin:0 0 12px}.report-signatures{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:34px}.report-signatures div{border-top:1px solid #86969e;padding-top:7px}.report-signatures span{display:block;font-size:10px;color:#6d7b83;text-transform:uppercase}.report-signatures b{font-size:12px}.report-footer{text-align:center;color:#7b8990;font-size:9px;border-top:1px solid #e1e6e8;margin-top:24px;padding-top:8px}.report-actions{justify-content:center;margin:12px 0 22px}
@media(max-width:1050px){.grid{grid-template-columns:repeat(2,1fr)}.three{grid-template-columns:1fr 1fr}.academic-manager{grid-template-columns:240px minmax(0,1fr)}.curriculum-row{grid-template-columns:1fr}.report-summary{grid-template-columns:repeat(3,1fr)}}
@media(max-width:820px){.shell{grid-template-columns:74px 1fr}.side{width:74px}.brand{font-size:0}.brand span{font-size:14px}.schoolname,.nav small{display:none}.nav button{font-size:0;text-align:center}.nav button:before{content:attr(data-i);font-size:18px}.main{padding:16px 12px}.two,.three{grid-template-columns:1fr}.academic-manager{grid-template-columns:1fr}.class-browser{min-height:auto}.teacher-box{grid-template-columns:1fr}.report-student-grid{grid-template-columns:1fr 1fr}.report-comments{grid-template-columns:1fr}.report-school-head{grid-template-columns:58px 1fr}.report-term{grid-column:1/-1;text-align:left}.student360-columns{grid-template-columns:1fr}}
@media(max-width:540px){.grid{grid-template-columns:1fr}.row{flex-direction:column}.top{align-items:flex-start;flex-direction:column}.attendance-row{grid-template-columns:1fr 1fr 1fr}.attendance-row .student{grid-column:1/-1}.info-grid{grid-template-columns:1fr}.report-student-grid,.report-summary,.report-signatures{grid-template-columns:1fr}.report-card{padding:16px}.student360-head{align-items:flex-start}.teacher-assign{flex-direction:column;align-items:stretch}}
@media print{body{background:white!important}.side,.top,#modal,#toast,.report-controls,.report-actions{display:none!important}.shell{display:block!important}.main{padding:0!important}.report-card{box-shadow:none!important;border-radius:0!important;margin:0!important;max-width:none!important;padding:12mm!important}.report-table th,.report-table td{font-size:10px}.report-school-head{break-inside:avoid}.report-comments,.report-signatures{break-inside:avoid}#content>*:not(#reportOut){display:none!important}#reportOut{display:block!important}}
</style>
</head>
<body>
<div id="loading" class="loading"><div><b>REVOLT-X SCHOOL</b><p class="muted">Connecting to Core Revolt-X OS...</p></div></div>
<div id="app" class="shell hide">
<aside class="side"><div class="brand"><span>RX</span> SCHOOL</div><div id="schoolName" class="schoolname"></div><nav id="nav" class="nav"></nav></aside>
<main class="main"><header class="top"><div><b id="pageTitle">Dashboard</b><div id="who" class="muted"></div></div><div class="right"><span id="role" class="badge"></span><button id="refresh" class="ghost">Refresh</button></div></header><div id="content"></div></main>
</div>
<div id="modal" class="modal hide"><div class="modalbox"><div id="modalBody"></div><button id="closeModal" class="ghost">Close</button></div></div>
<div id="toast" class="toast hide"></div>
<script>
(function(){
var token='',ctx=null,current='dashboard';
var nav=[
['core','School'],['dashboard','Dashboard','⌂'],['setup','School Setup','⚙'],['admissions','Admissions','✚'],['students','Students','S'],['classes','Academic Manager','C'],['attendance','Attendance','✓'],['assessments','Assessments','A'],['homework','Homework','H'],['reports','Report Cards','R'],['promotions','Promotion & Rollover','⇧'],['grading','Grading Setup','G'],['fees','Fees & Payments','₵'],['timetable','Timetable','T'],['announcements','Announcements','N'],['staff','Staff Access','P'],['portals','Portals & Interfaces','◫']
];
function E(id){return document.getElementById(id)}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function toast(m,bad){var t=E('toast');t.textContent=m;t.style.borderColor=bad?'#71323a':'#2c6d5c';t.classList.remove('hide');setTimeout(function(){t.classList.add('hide')},2500)}
function badge(v){var s=String(v||'');var c=/absent|withdrawn|closed|suspended|unpaid/i.test(s)?' red':/draft|planned|late|part_paid|unmarked/i.test(s)?' warn':'';return '<span class="badge'+c+'">'+esc(s||'—')+'</span>'}
function table(rows,cols,act){if(!rows||!rows.length)return '<div class="empty">No records yet.</div>';return '<div class="table"><table><thead><tr>'+cols.map(function(c){return'<th>'+esc(c.label||c.key)+'</th>'}).join('')+(act?'<th>Actions</th>':'')+'</tr></thead><tbody>'+rows.map(function(r){return'<tr>'+cols.map(function(c){var v=c.render?c.render(r):r[c.key];return'<td>'+String(v==null?'':v)+'</td>'}).join('')+(act?'<td>'+act(r)+'</td>':'')+'</tr>'}).join('')+'</tbody></table></div>'}
async function raw(path,opt){opt=opt||{};opt.headers=Object.assign({'content-type':'application/json'},opt.headers||{},token?{authorization:'Bearer '+token}:{});var r=await fetch(path,opt),j=null;try{j=await r.json()}catch(e){}if(!r.ok)throw Error(j&&j.error&&j.error.message?j.error.message:'Request failed ('+r.status+')');return j}
function modal(html){E('modalBody').innerHTML=html;E('modal').classList.remove('hide')}function close(){E('modal').classList.add('hide');E('modalBody').innerHTML=''}E('closeModal').onclick=close;
function field(f,v){v=v==null?'':v;if(f.type==='select')return'<label>'+esc(f.label)+'</label><select data-f="'+f.key+'">'+(f.options||[]).map(function(o){var value=typeof o==='string'?o:o.value,label=typeof o==='string'?o:o.label;return'<option value="'+esc(value)+'"'+(String(value)===String(v)?' selected':'')+'>'+esc(label)+'</option>'}).join('')+'</select>';if(f.type==='textarea')return'<label>'+esc(f.label)+'</label><textarea rows="'+(f.rows||4)+'" data-f="'+f.key+'">'+esc(v)+'</textarea>';return'<label>'+esc(f.label)+'</label><input type="'+(f.type||'text')+'" data-f="'+f.key+'" value="'+esc(v)+'">'}
function form(title,fields,vals,save){vals=vals||{};modal('<h2 style="margin-bottom:15px">'+esc(title)+'</h2>'+fields.map(function(f){return field(f,vals[f.key])}).join('')+'<button id="saveModal" class="primary" style="width:100%;margin:8px 0 12px">Save</button>');E('saveModal').onclick=async function(){var v={};E('modalBody').querySelectorAll('[data-f]').forEach(function(x){v[x.dataset.f]=x.value});try{E('saveModal').disabled=true;await save(v);close();toast('Saved');await page(current)}catch(e){toast(e.message,true);E('saveModal').disabled=false}}}
function confirmDo(message,action){if(!confirm(message))return;Promise.resolve().then(action).then(function(){toast('Action completed');return page(current)}).catch(function(e){toast(e.message,true)})}
async function boot(){
 try{
   token=sessionStorage.getItem('rx_school_token')||'';
   if(!token){var p=await fetch('/api/auth/preview',{method:'POST'});var j=await p.json();if(!p.ok)throw Error(j.error&&j.error.message||'Core OS access failed');token=j.accessToken;sessionStorage.setItem('rx_school_token',token)}
   ctx=await raw('/api/context');
   if(!ctx.profile){await raw('/api/school/bootstrap',{method:'POST',body:JSON.stringify({schoolName:ctx.core.organisation_name})});ctx=await raw('/api/context')}
   E('schoolName').textContent=ctx.profile.school_name;E('who').textContent=ctx.core.first_name+' '+ctx.core.last_name+' • '+ctx.core.organisation_name;E('role').textContent=ctx.schoolRole.replace('_',' ');
   E('nav').innerHTML=nav.map(function(n){return n[0]==='core'?'<small>'+n[1]+'</small>':'<button data-p="'+n[0]+'" data-i="'+n[2]+'">'+n[1]+'</button>'}).join('');
   E('nav').onclick=function(e){var b=e.target.closest('button[data-p]');if(b)page(b.dataset.p)};E('refresh').onclick=function(){page(current)};
   E('loading').classList.add('hide');E('app').classList.remove('hide');await page('dashboard')
 }catch(e){E('loading').innerHTML='<div><h2>School workspace unavailable</h2><p>'+esc(e.message)+'</p></div>'}
}
async function page(p){
 current=p;document.querySelectorAll('#nav button').forEach(function(b){b.classList.toggle('active',b.dataset.p===p)});E('pageTitle').textContent=(nav.find(function(n){return n[0]===p})||['',p])[1];E('content').innerHTML='<p class="muted">Loading...</p>';
 try{
 if(p==='dashboard'){
   var d=await raw('/api/dashboard');E('content').innerHTML='<h1>School Dashboard</h1><div class="grid">'+[['Students',d.students],['Classes',d.classes],['Subjects',d.subjects],['School staff',d.staff_users],['Present today',d.present_today],['Absent today',d.absent_today],['Fees billed','GHS '+Number(d.fees_billed||0).toFixed(2)],['Payments received','GHS '+Number(d.payments_received||0).toFixed(2)]].map(function(x){return'<div class="panel stat"><span class="muted">'+esc(x[0])+'</span><b>'+esc(x[1])+'</b></div>'}).join('')+'</div><div class="two" style="margin-top:12px"><div class="panel"><h3>Academic year</h3><p>'+(d.activeYear?'<b>'+esc(d.activeYear.name)+'</b><br>'+esc(d.activeYear.start_date)+' to '+esc(d.activeYear.end_date):'<span class="muted">No active academic year</span>')+'</p></div><div class="panel"><h3>Current term</h3><p>'+(d.activeTerm?'<b>'+esc(d.activeTerm.name)+'</b><br>'+esc(d.activeTerm.start_date)+' to '+esc(d.activeTerm.end_date):'<span class="muted">No active term</span>')+'</p></div></div>'
 }
 else if(p==='setup'){
   var rs=await Promise.all([raw('/api/school/profile'),raw('/api/academic-years'),raw('/api/terms'),raw('/api/grade-levels')]);var prof=rs[0],years=rs[1],terms=rs[2],grades=rs[3];
   E('content').innerHTML='<div class="section"><h1>School Setup</h1><button id="editProfile" class="primary">Edit profile</button></div><div class="panel"><div class="two"><div><b>'+esc(prof.school_name)+'</b><p class="muted">'+esc(prof.motto||'No motto set')+'</p></div><div><p>'+esc(prof.phone||'')+'<br>'+esc(prof.email||'')+'<br>'+esc(prof.address||'')+'</p></div></div></div>'+
   '<div class="section"><h2>Academic Years</h2><button id="addYear" class="ghost">Add year</button></div><div class="panel">'+table(years,[{key:'name'},{key:'start_date',label:'Starts'},{key:'end_date',label:'Ends'},{key:'status',render:function(r){return badge(r.status)}}],function(r){return (r.status!=='active'?'<button class="mini" data-activate-year="'+r.id+'">Activate</button>':'')+'<button class="mini" data-edit-year="'+r.id+'">Edit</button><button class="mini danger" data-delete-year="'+r.id+'">Delete</button>'})+'</div>'+
   '<div class="section"><h2>Terms</h2><button id="addTerm" class="ghost">Add term</button></div><div class="panel">'+table(terms,[{key:'name'},{key:'term_no',label:'Term'},{key:'start_date',label:'Starts'},{key:'end_date',label:'Ends'},{key:'status',render:function(r){return badge(r.status)}}],function(r){return (r.status!=='active'?'<button class="mini" data-activate-term="'+r.id+'">Activate</button>':'')+'<button class="mini" data-edit-term="'+r.id+'">Edit</button><button class="mini danger" data-delete-term="'+r.id+'">Delete</button>'})+'</div>'+
   '<div class="section"><h2>Grade Levels</h2></div><div class="panel">'+table(grades,[{key:'code'},{key:'name'},{key:'stage',render:function(r){return badge(r.stage)}},{key:'is_active',label:'Status',render:function(r){return badge(r.is_active?'active':'inactive')}}],function(r){return '<button class="mini" data-edit-grade="'+r.id+'">Edit</button>'})+'</div>';
   E('editProfile').onclick=function(){form('Edit school profile',[{key:'schoolName',label:'School name'},{key:'shortName',label:'Short name'},{key:'motto',label:'Motto'},{key:'phone',label:'Phone'},{key:'email',label:'Email',type:'email'},{key:'address',label:'Address',type:'textarea'}],{schoolName:prof.school_name,shortName:prof.short_name||'',motto:prof.motto||'',phone:prof.phone||'',email:prof.email||'',address:prof.address||''},function(v){return raw('/api/school/profile',{method:'PATCH',body:JSON.stringify(v)})})};
   E('addYear').onclick=function(){form('New academic year',[{key:'name',label:'Name e.g. 2027/2028'},{key:'startDate',label:'Start date',type:'date'},{key:'endDate',label:'End date',type:'date'}],{},function(v){return raw('/api/academic-years',{method:'POST',body:JSON.stringify(v)})})};
   E('addTerm').onclick=function(){form('New term',[{key:'academicYearId',label:'Academic year',type:'select',options:years.map(function(y){return{value:y.id,label:y.name}})},{key:'termNo',label:'Term number',type:'select',options:['1','2','3']},{key:'name',label:'Term name'},{key:'startDate',label:'Start date',type:'date'},{key:'endDate',label:'End date',type:'date'}],{},function(v){return raw('/api/terms',{method:'POST',body:JSON.stringify({academicYearId:v.academicYearId,termNo:Number(v.termNo),name:v.name,startDate:v.startDate,endDate:v.endDate})})})};
   E('content').onclick=async function(e){
     var id=e.target.dataset.activateYear;if(id){await raw('/api/academic-years/'+id+'/activate',{method:'POST',body:'{}'});toast('Academic year activated');return page('setup')}
     id=e.target.dataset.editYear;if(id){var y=years.find(function(x){return x.id===id});return form('Edit academic year',[{key:'name',label:'Name'},{key:'startDate',label:'Start date',type:'date'},{key:'endDate',label:'End date',type:'date'}],{name:y.name,startDate:String(y.start_date).slice(0,10),endDate:String(y.end_date).slice(0,10)},function(v){return raw('/api/academic-years/'+id,{method:'PATCH',body:JSON.stringify(v)})})}
     id=e.target.dataset.deleteYear;if(id){return confirmDo('Delete this academic year? This is only allowed when it has no student enrolments.',function(){return raw('/api/academic-years/'+id,{method:'DELETE'})})}
     id=e.target.dataset.activateTerm;if(id){await raw('/api/terms/'+id+'/activate',{method:'POST',body:'{}'});toast('Term activated');return page('setup')}
     id=e.target.dataset.editTerm;if(id){var t=terms.find(function(x){return x.id===id});return form('Edit term',[{key:'name',label:'Term name'},{key:'startDate',label:'Start date',type:'date'},{key:'endDate',label:'End date',type:'date'}],{name:t.name,startDate:String(t.start_date).slice(0,10),endDate:String(t.end_date).slice(0,10)},function(v){return raw('/api/terms/'+id,{method:'PATCH',body:JSON.stringify(v)})})}
     id=e.target.dataset.deleteTerm;if(id){return confirmDo('Delete this term and its related records?',function(){return raw('/api/terms/'+id,{method:'DELETE'})})}
     id=e.target.dataset.editGrade;if(id){var g=grades.find(function(x){return x.id===id});return form('Edit grade level',[{key:'name',label:'Name'},{key:'isActive',label:'Status',type:'select',options:[{value:'true',label:'Active'},{value:'false',label:'Inactive'}]}],{name:g.name,isActive:String(g.is_active)},function(v){return raw('/api/grade-levels/'+id,{method:'PATCH',body:JSON.stringify({name:v.name,isActive:v.isActive==='true'})})})}
   }
 }
 else if(p==='classes'){
   var rr=await Promise.all([raw('/api/academic-years'),raw('/api/grade-levels'),raw('/api/classes'),raw('/api/subjects'),raw('/api/class-subjects'),raw('/api/staff/core-users'),raw('/api/staff/module-memberships'),raw('/api/teacher-assignments'),raw('/api/terms')]);
   var ys=rr[0],gs=rr[1],cls=rr[2],subs=rr[3],classSubs=rr[4],users=rr[5],memberships=rr[6],assignments=rr[7],terms=rr[8];
   var teacherIds=memberships.filter(function(m){return m.status==='active'&&(m.role==='teacher'||m.role==='headteacher'||m.role==='school_admin')}).map(function(m){return m.os_user_id});
   var teachers=users.filter(function(u){return teacherIds.indexOf(u.id)>=0});
   function userName(id){var u=users.find(function(x){return x.id===id});return u?u.first_name+' '+u.last_name:'Not assigned'}
   var activeYear=ys.find(function(y){return y.status==='active'})||ys[0],selectedYear=activeYear?activeYear.id:'',selectedClass=null;
   function yearClasses(){return cls.filter(function(x){return !selectedYear||x.academic_year_id===selectedYear})}
   function classCard(x){return '<button class="class-card'+(selectedClass===x.id?' selected':'')+'" data-pick-class="'+x.id+'"><span><b>'+esc(x.name)+'</b><small>'+esc(x.grade_name)+' • '+esc(x.stream||'No stream')+'</small></span><span class="class-count">'+esc(x.student_count||0)+' students<br>'+esc(x.subject_count||0)+' subjects</span></button>'}
   function renderManager(){
     var list=yearClasses();if(!selectedClass&&list[0])selectedClass=list[0].id;
     E('content').innerHTML='<div class="section"><div><h1>Academic Manager</h1><p class="muted">Manage classes, curriculum subjects and teacher assignments from one screen.</p></div><div class="actions"><button id="addClass" class="primary">Add class</button><button id="addSubject" class="ghost">Add subject</button></div></div>'+
     '<div class="panel academic-toolbar"><label>Academic year</label><select id="academicYearFilter">'+ys.map(function(y){return'<option value="'+y.id+'"'+(y.id===selectedYear?' selected':'')+'>'+esc(y.name)+(y.status==='active'?' • Active':'')+'</option>'}).join('')+'</select></div>'+
     '<div class="academic-manager"><div class="panel class-browser"><h3>Classes</h3><div id="classCards">'+(list.length?list.map(classCard).join(''):'<div class="empty">No classes for this academic year.</div>')+'</div></div><div id="classDetail" class="panel"></div></div>'+
     '<div class="section"><h2>Subject Catalogue</h2></div><div class="panel">'+table(subs,[{key:'code'},{key:'name'},{key:'stage',render:function(r){return badge(r.stage)}},{key:'is_active',label:'Status',render:function(r){return badge(r.is_active?'active':'inactive')}}],function(r){return '<button class="mini" data-edit-subject="'+r.id+'">Edit</button><button class="mini danger" data-delete-subject="'+r.id+'">Delete</button>'})+'</div>';
     renderDetail(selectedClass);
     E('academicYearFilter').onchange=function(){selectedYear=this.value;selectedClass=null;renderManager()}
     E('addClass').onclick=function(){form('Create class',[{key:'academicYearId',label:'Academic year',type:'select',options:ys.map(function(y){return{value:y.id,label:y.name}})},{key:'gradeLevelId',label:'Grade level',type:'select',options:gs.filter(function(g){return g.is_active}).map(function(g){return{value:g.id,label:g.name}})},{key:'name',label:'Class name'},{key:'stream',label:'Stream'},{key:'capacity',label:'Capacity',type:'number'},{key:'classTeacherOsUserId',label:'Class teacher',type:'select',options:[{value:'',label:'Not assigned'}].concat(teachers.map(function(t){return{value:t.id,label:t.first_name+' '+t.last_name}}))}],{academicYearId:selectedYear},function(v){return raw('/api/classes',{method:'POST',body:JSON.stringify({academicYearId:v.academicYearId,gradeLevelId:v.gradeLevelId,name:v.name,stream:v.stream||undefined,capacity:v.capacity?Number(v.capacity):undefined,classTeacherOsUserId:v.classTeacherOsUserId||undefined})})})};
     E('addSubject').onclick=function(){form('Add subject to catalogue',[{key:'code',label:'Code'},{key:'name',label:'Subject name'},{key:'stage',label:'Stage',type:'select',options:['primary','jhs','both']}],{stage:'both'},function(v){return raw('/api/subjects',{method:'POST',body:JSON.stringify(v)})})};
   }
   function renderDetail(id){
     var box=E('classDetail');if(!box)return;var x=cls.find(function(r){return r.id===id&&(!selectedYear||r.academic_year_id===selectedYear)});
     if(!x){box.innerHTML='<div class="empty">Select a class to manage it.</div>';return}
     selectedClass=x.id;
     var links=classSubs.filter(function(cs){return cs.classroom_id===x.id&&cs.is_active});
     var stage=gs.find(function(g){return g.id===x.grade_level_id});
     var available=subs.filter(function(s){return s.is_active&&(s.stage==='both'||s.stage===(stage&&stage.stage))&&!links.some(function(l){return l.subject_id===s.id})});
     box.innerHTML='<div class="class-head"><div><span class="badge">'+esc(x.grade_name)+'</span><h2>'+esc(x.name)+'</h2><p class="muted">'+esc(x.student_count||0)+' students • '+esc(x.subject_count||0)+' curriculum subjects • Capacity '+esc(x.capacity||'—')+'</p></div><button class="mini" data-edit-class="'+x.id+'">Edit class</button></div>'+
     '<div class="teacher-box"><div><b>Class Teacher</b><p class="muted">Responsible for the class overall.</p></div><div class="teacher-assign"><select id="classTeacherSelect"><option value="">Not assigned</option>'+teachers.map(function(t){return'<option value="'+t.id+'"'+(x.class_teacher_os_user_id===t.id?' selected':'')+'>'+esc(t.first_name+' '+t.last_name)+'</option>'}).join('')+'</select><button class="primary" data-save-class-teacher="'+x.id+'">Save</button></div></div>'+
     '<div class="section"><h3>Class Curriculum & Subject Teachers</h3><button class="ghost" data-add-class-subject="'+x.id+'">Add subject</button></div>'+
     (links.length?'<div class="curriculum-list">'+links.map(function(link){var tas=assignments.filter(function(a){return a.classroom_id===x.id&&a.subject_id===link.subject_id&&a.is_active});return'<div class="curriculum-row"><div><b>'+esc(link.subject_name)+'</b><small>'+esc(link.subject_code)+' • '+esc(link.stage)+'</small></div><div class="teacher-chip-area">'+(tas.length?tas.map(function(a){return'<span class="teacher-chip">'+esc(userName(a.teacher_os_user_id))+' <button data-delete-ta="'+a.id+'" title="Remove assignment">×</button></span>'}).join(''):'<span class="muted">No subject teacher assigned</span>')+'</div><div class="actions"><button class="mini" data-assign-subject-teacher="'+link.id+'" data-subject-id="'+link.subject_id+'" data-class-id="'+x.id+'">Assign teacher</button><button class="mini danger" data-remove-class-subject="'+link.id+'">Remove</button></div></div>'}).join('')+'</div>':'<div class="empty">No subjects assigned to this class yet.</div>')+
     (available.length?'<p class="muted" style="margin-top:14px">Available to add: '+available.map(function(s){return esc(s.name)}).join(', ')+'</p>':'');
   }
   renderManager();
   E('content').onclick=async function(e){
     var id=e.target.dataset.pickClass;if(id){selectedClass=id;E('content').querySelectorAll('.class-card').forEach(function(b){b.classList.toggle('selected',b.dataset.pickClass===id)});return renderDetail(id)}
     id=e.target.dataset.editClass;if(id){var x=cls.find(function(r){return r.id===id});return form('Edit class',[{key:'name',label:'Class name'},{key:'stream',label:'Stream'},{key:'capacity',label:'Capacity',type:'number'},{key:'isActive',label:'Status',type:'select',options:[{value:'true',label:'Active'},{value:'false',label:'Inactive'}]}],{name:x.name,stream:x.stream||'',capacity:x.capacity||'',isActive:String(x.is_active)},function(v){return raw('/api/classes/'+id,{method:'PATCH',body:JSON.stringify({name:v.name,stream:v.stream||null,capacity:v.capacity?Number(v.capacity):null,isActive:v.isActive==='true'})})})}
     id=e.target.dataset.saveClassTeacher;if(id){var tid=E('classTeacherSelect').value;try{await raw('/api/classes/'+id,{method:'PATCH',body:JSON.stringify({classTeacherOsUserId:tid||null})});toast('Class teacher saved');return page('classes')}catch(err){return toast(err.message,true)}}
     id=e.target.dataset.addClassSubject;if(id){var x=cls.find(function(r){return r.id===id});var stage=gs.find(function(g){return g.id===x.grade_level_id});var links=classSubs.filter(function(cs){return cs.classroom_id===id&&cs.is_active});var opts=subs.filter(function(s){return s.is_active&&(s.stage==='both'||s.stage===(stage&&stage.stage))&&!links.some(function(l){return l.subject_id===s.id})});if(!opts.length)return toast('All available subjects are already assigned',true);return form('Add subject to '+x.name,[{key:'subjectId',label:'Subject',type:'select',options:opts.map(function(s){return{value:s.id,label:s.name+' ('+s.code+')'}})}],{},function(v){return raw('/api/class-subjects',{method:'POST',body:JSON.stringify({academicYearId:x.academic_year_id,classroomId:id,subjectId:v.subjectId})})})}
     id=e.target.dataset.assignSubjectTeacher;if(id){var classId=e.target.dataset.classId,subjectId=e.target.dataset.subjectId;var x=cls.find(function(r){return r.id===classId});return form('Assign subject teacher',[{key:'teacherOsUserId',label:'Teacher',type:'select',options:teachers.map(function(t){return{value:t.id,label:t.first_name+' '+t.last_name+' • '+(t.job_title||'Teacher')}})},{key:'termId',label:'Applies to',type:'select',options:[{value:'',label:'All terms'}].concat(terms.filter(function(t){return t.academic_year_id===x.academic_year_id}).map(function(t){return{value:t.id,label:t.name+(t.status==='active'?' • Active':'')}}))}],{termId:''},function(v){return raw('/api/teacher-assignments',{method:'POST',body:JSON.stringify({teacherOsUserId:v.teacherOsUserId,academicYearId:x.academic_year_id,termId:v.termId||null,classroomId:classId,subjectId:subjectId})})})}
     id=e.target.dataset.removeClassSubject;if(id){return confirmDo('Remove this subject from the class curriculum?',function(){return raw('/api/class-subjects/'+id,{method:'DELETE'})})}
     id=e.target.dataset.deleteTa;if(id){return confirmDo('Remove this teacher assignment?',function(){return raw('/api/teacher-assignments/'+id,{method:'DELETE'})})}
     id=e.target.dataset.editSubject;if(id){var s=subs.find(function(r){return r.id===id});return form('Edit subject',[{key:'code',label:'Code'},{key:'name',label:'Subject name'},{key:'stage',label:'Stage',type:'select',options:['primary','jhs','both']},{key:'isActive',label:'Status',type:'select',options:[{value:'true',label:'Active'},{value:'false',label:'Inactive'}]}],{code:s.code,name:s.name,stage:s.stage,isActive:String(s.is_active)},function(v){return raw('/api/subjects/'+id,{method:'PATCH',body:JSON.stringify({code:v.code,name:v.name,stage:v.stage,isActive:v.isActive==='true'})})})}
     id=e.target.dataset.deleteSubject;if(id){return confirmDo('Delete this subject? It cannot be deleted while used by a class, assessment or timetable.',function(){return raw('/api/subjects/'+id,{method:'DELETE'})})}
   }
 }
 else if(p==='admissions'){
   var rr=await Promise.all([raw('/api/admissions'),raw('/api/classes')]);var apps=rr[0],classes=rr[1];
   E('content').innerHTML='<div class="section"><h1>Admissions</h1><button id="publicAdmissions" class="primary">Open public admissions</button></div><div class="notice">Applications submitted through the public admissions page appear here for review. Approved applications can be converted directly into student and guardian records.</div><div class="panel" style="margin-top:12px">'+table(apps,[{key:'application_no',label:'Application No.'},{key:'first_name',label:'Applicant',render:function(r){return esc(r.first_name+' '+r.last_name)}},{key:'requested_grade_name',label:'Requested Grade'},{key:'guardian_phone',label:'Guardian Phone'},{key:'submitted_at',label:'Submitted',render:function(r){return esc(new Date(r.submitted_at).toLocaleDateString())}},{key:'status',render:function(r){return badge(r.status)}}],function(r){return '<button class="mini" data-review-app="'+r.id+'">Review</button>'+(r.status==='approved'?'<button class="mini" data-enrol-app="'+r.id+'">Enrol</button>':'')})+'</div>';
   E('publicAdmissions').onclick=function(){window.open('/admissions','_blank')};
   E('content').onclick=function(e){
     var id=e.target.dataset.reviewApp;if(id){var a=apps.find(function(x){return x.id===id});return form('Review admission application',[{key:'status',label:'Status',type:'select',options:['submitted','under_review','approved','waitlisted','declined']},{key:'reviewNote',label:'Review note',type:'textarea'}],{status:a.status,reviewNote:a.review_note||''},function(v){return raw('/api/admissions/'+id,{method:'PATCH',body:JSON.stringify({status:v.status,reviewNote:v.reviewNote||null})})})}
     id=e.target.dataset.enrolApp;if(id){var a2=apps.find(function(x){return x.id===id});return form('Enrol approved applicant',[{key:'admissionNo',label:'Admission number'},{key:'classroomId',label:'Class',type:'select',options:[{value:'',label:'Create student without class'}].concat(classes.map(function(x){return{value:x.id,label:x.name}}))}],{admissionNo:'RX/2026/'+String(apps.indexOf(a2)+101).padStart(3,'0')},function(v){return raw('/api/admissions/'+id+'/enrol',{method:'POST',body:JSON.stringify({admissionNo:v.admissionNo,classroomId:v.classroomId||undefined})})})}
   }
 }
 else if(p==='students'){
   var rr=await Promise.all([raw('/api/students'),raw('/api/academic-years'),raw('/api/classes')]);var students=rr[0],years=rr[1],classes=rr[2],current360=null;
   function studentActions(r){return '<button class="mini primary-lite" data-view-student="'+r.id+'">360 View</button><button class="mini" data-student-pin="'+r.id+'">Student PIN</button><button class="mini" data-edit-student="'+r.id+'">Edit</button><button class="mini danger" data-delete-student="'+r.id+'">Delete</button>'}
   function renderStudentTable(){return table(students,[{key:'admission_no',label:'Admission No.'},{key:'first_name',label:'Student',render:function(r){return '<b>'+esc(r.first_name+' '+r.last_name)+'</b>'}},{key:'grade_name',label:'Grade'},{key:'classroom_name',label:'Class'},{key:'status',render:function(r){return badge(r.status)}}],studentActions)}
   function renderList(){E('content').innerHTML='<div class="section"><div><h1>Students</h1><p class="muted">Open the 360 View for a complete academic, attendance, finance and family profile.</p></div><button id="addStudent" class="primary">Admit student</button></div><div class="toolbar"><input id="studentSearch" placeholder="Search name or admission number"><button id="searchStudent" class="ghost">Search</button></div><div class="panel" id="studentTable">'+renderStudentTable()+'</div>';
     E('addStudent').onclick=function(){form('Admit student',[{key:'admissionNo',label:'Admission number'},{key:'firstName',label:'First name'},{key:'middleName',label:'Middle name'},{key:'lastName',label:'Last name'},{key:'sex',label:'Sex',type:'select',options:[{value:'',label:'Not set'},'male','female']},{key:'dateOfBirth',label:'Date of birth',type:'date'}],{},function(v){var b={admissionNo:v.admissionNo,firstName:v.firstName,lastName:v.lastName};if(v.middleName)b.middleName=v.middleName;if(v.sex)b.sex=v.sex;if(v.dateOfBirth)b.dateOfBirth=v.dateOfBirth;return raw('/api/students',{method:'POST',body:JSON.stringify(b)})})};
     async function search(){var q=E('studentSearch').value.trim();students=await raw('/api/students'+(q?'?q='+encodeURIComponent(q):''));E('studentTable').innerHTML=renderStudentTable()}E('searchStudent').onclick=search;E('studentSearch').onkeydown=function(e){if(e.key==='Enter')search()};
   }
   async function show360(id){
     E('content').innerHTML='<p class="muted">Loading complete student profile...</p>';
     var d=await raw('/api/students/'+id+'/360');current360=d;var s=d.student,perf=d.performance||{},att=d.attendance||{},fees=d.fees||{};
     var initials=(String(s.first_name||'').charAt(0)+String(s.last_name||'').charAt(0)).toUpperCase();
     var pos=perf.classPosition?(perf.classPosition+(perf.classPosition===1?'st':perf.classPosition===2?'nd':perf.classPosition===3?'rd':'th')+' of '+perf.classSize):'—';
     E('content').innerHTML='<div class="student360-head"><button class="ghost" data-back-students="1">← Students</button><div class="student360-identity"><div class="student-avatar">'+esc(initials)+'</div><div><span class="badge">'+esc(s.status)+'</span><h1>'+esc(s.first_name+' '+(s.middle_name||'')+' '+s.last_name)+'</h1><p class="muted">'+esc(s.admission_no)+' • '+esc(s.grade_name||'No grade')+' • '+esc(s.classroom_name||'No class')+' • '+esc(s.academic_year||'')+'</p></div></div><div class="actions"><button class="ghost" data-edit-student="'+s.id+'">Edit profile</button><button class="ghost" data-student-pin="'+s.id+'">Portal PIN</button><button class="primary" data-open-student-report="'+s.id+'">Report Card</button></div></div>'+
     '<div class="grid student360-stats"><div class="panel stat"><span class="muted">Attendance rate</span><b>'+esc(att.rate||0)+'%</b><small>'+esc(att.present||0)+' present • '+esc(att.late||0)+' late</small></div><div class="panel stat"><span class="muted">Overall average</span><b>'+(perf.overallAverage==null?'—':esc(perf.overallAverage)+'%')+'</b><small>'+esc(d.term?d.term.name:'No active term')+'</small></div><div class="panel stat"><span class="muted">Class position</span><b>'+esc(pos)+'</b><small>Based on recorded assessments</small></div><div class="panel stat"><span class="muted">Outstanding fees</span><b>GHS '+Number(fees.outstanding||0).toFixed(2)+'</b><small>Paid GHS '+Number(fees.paid||0).toFixed(2)+'</small></div></div>'+
     '<div class="two student360-columns"><div>'+
       '<div class="panel"><div class="section compact"><h3>Student Information</h3><button class="mini" data-enrol-student="'+s.id+'">Move / Enrol</button></div><div class="info-grid"><div><span>Admission No.</span><b>'+esc(s.admission_no)+'</b></div><div><span>Date of birth</span><b>'+esc(s.date_of_birth?String(s.date_of_birth).slice(0,10):'—')+'</b></div><div><span>Sex</span><b>'+esc(s.sex||'—')+'</b></div><div><span>Admission date</span><b>'+esc(s.admission_date?String(s.admission_date).slice(0,10):'—')+'</b></div><div><span>Current class</span><b>'+esc(s.classroom_name||'—')+'</b></div><div><span>Grade</span><b>'+esc(s.grade_name||'—')+'</b></div></div>'+(s.notes?'<div class="notice" style="margin-top:12px">'+esc(s.notes)+'</div>':'')+'</div>'+
       '<div class="panel"><div class="section compact"><h3>Guardians & Family</h3><button class="mini" data-add-guardian="'+s.id+'">Add guardian</button></div>'+table(d.guardians,[{key:'first_name',label:'Guardian',render:function(g){return '<b>'+esc(g.first_name+' '+g.last_name)+'</b><br><span class="muted">'+esc(g.relationship)+(g.is_primary?' • Primary':'')+'</span>'}},{key:'phone'},{key:'email'},{key:'portal_active',label:'Portal',render:function(g){return badge(g.portal_active?'active':'not set')}}],function(g){return '<button class="mini" data-edit-guardian="'+g.id+'" data-student-id="'+s.id+'">Edit</button><button class="mini" data-parent-pin="'+g.id+'">PIN</button><button class="mini danger" data-delete-guardian="'+g.id+'" data-student-id="'+s.id+'">Delete</button>'})+'</div>'+
       '<div class="panel"><h3>Academic Performance</h3><p class="muted">'+esc(d.term?d.term.name:'Current term')+'</p>'+table(d.subjects,[{key:'subject_name',label:'Subject'},{key:'percentage',label:'Average %'},{key:'grade'},{key:'remark'},{key:'assessment_count',label:'Assessments'}])+'</div>'+
       '<div class="panel"><h3>Homework</h3>'+table(d.homework,[{key:'subject_name',label:'Subject'},{key:'title'},{key:'due_at',label:'Due',render:function(h){return esc(h.due_at?new Date(h.due_at).toLocaleDateString():'—')}},{key:'submission_status',label:'Status',render:function(h){return badge(h.submission_status)}},{key:'score'}])+'</div>'+
     '</div><div>'+
       '<div class="panel"><h3>Attendance</h3><div class="mini-stats"><span><b>'+esc(att.present||0)+'</b> Present</span><span><b>'+esc(att.absent||0)+'</b> Absent</span><span><b>'+esc(att.late||0)+'</b> Late</span><span><b>'+esc(att.excused||0)+'</b> Excused</span></div>'+table(d.recentAttendance,[{key:'attendance_date',label:'Date',render:function(r){return esc(String(r.attendance_date).slice(0,10))}},{key:'status',render:function(r){return badge(r.status)}},{key:'note'}])+'</div>'+
       '<div class="panel"><h3>Fees & Payments</h3><div class="mini-stats"><span><b>GHS '+Number(fees.billed||0).toFixed(2)+'</b> Billed</span><span><b>GHS '+Number(fees.paid||0).toFixed(2)+'</b> Paid</span><span><b>GHS '+Number(fees.outstanding||0).toFixed(2)+'</b> Balance</span></div>'+table(d.payments,[{key:'paid_at',label:'Date',render:function(r){return esc(new Date(r.paid_at).toLocaleDateString())}},{key:'fee_name',label:'Fee'},{key:'amount',render:function(r){return 'GHS '+Number(r.amount).toFixed(2)}},{key:'payment_method',label:'Method'}])+'</div>'+
       '<div class="panel"><h3>Academic History</h3>'+table(d.enrolments,[{key:'academic_year',label:'Year'},{key:'grade_name',label:'Grade'},{key:'classroom_name',label:'Class'},{key:'status',render:function(r){return badge(r.status)}}])+'</div>'+
       '<div class="panel"><h3>Promotion History</h3>'+table(d.promotions,[{key:'from_year',label:'From'},{key:'from_class',label:'Class'},{key:'to_year',label:'To'},{key:'to_class',label:'Class'},{key:'outcome',render:function(r){return badge(r.outcome)}}])+'</div>'+
       '<div class="panel"><h3>Recent Student Activity</h3>'+(d.activity.length?'<div class="timeline">'+d.activity.map(function(a){return'<div><b>'+esc(a.action.replace(/\./g,' '))+'</b><span>'+esc(new Date(a.created_at).toLocaleString())+'</span></div>'}).join('')+'</div>':'<p class="muted">No recent activity logged.</p>')+'</div>'+
     '</div></div>';
   }
   renderList();
   E('content').onclick=async function(e){
     var id=e.target.dataset.backStudents;if(id){current360=null;return renderList()}
     id=e.target.dataset.viewStudent;if(id){try{return await show360(id)}catch(err){return toast(err.message,true)}}
     id=e.target.dataset.openStudentReport;if(id){sessionStorage.setItem('rx_report_student',id);return page('reports')}
     id=e.target.dataset.studentPin;if(id){return raw('/api/students/'+id+'/portal-reset',{method:'POST',body:'{}'}).then(function(x){modal('<h2>Student Portal PIN</h2><p class="muted">Give this PIN to the student securely. Resetting it signs out older student sessions.</p><div class="panel"><b style="font-size:28px">'+esc(x.pin)+'</b></div><p><a href="/student" target="_blank" style="color:#45ddb2">Open Student Portal</a></p>')}).catch(function(err){toast(err.message,true)})}
     id=e.target.dataset.editStudent;if(id){var st=students.find(function(x){return x.id===id})||(current360&&current360.student);return form('Edit student',[{key:'firstName',label:'First name'},{key:'middleName',label:'Middle name'},{key:'lastName',label:'Last name'},{key:'status',label:'Status',type:'select',options:['active','graduated','transferred','withdrawn']},{key:'notes',label:'Notes',type:'textarea'}],{firstName:st.first_name,middleName:st.middle_name||'',lastName:st.last_name,status:st.status,notes:st.notes||''},function(v){return raw('/api/students/'+id,{method:'PATCH',body:JSON.stringify({firstName:v.firstName,middleName:v.middleName||null,lastName:v.lastName,status:v.status,notes:v.notes||null})})})}
     id=e.target.dataset.deleteStudent;if(id){return confirmDo('Permanently delete this student and all linked school records? This cannot be undone.',function(){return raw('/api/students/'+id,{method:'DELETE'})})}
     id=e.target.dataset.enrolStudent;if(id){var y=years.find(function(x){return x.status==='active'})||years[0];var opts=classes.filter(function(c){return !y||c.academic_year_id===y.id});return form('Move / enrol student',[{key:'classroomId',label:'Class',type:'select',options:opts.map(function(c){return{value:c.id,label:c.name+' • '+c.grade_name}})}],{},function(v){return raw('/api/enrolments',{method:'POST',body:JSON.stringify({studentId:id,academicYearId:y.id,classroomId:v.classroomId})})})}
     id=e.target.dataset.addGuardian;if(id){return form('Add guardian',[{key:'firstName',label:'First name'},{key:'lastName',label:'Last name'},{key:'phone',label:'Phone'},{key:'email',label:'Email',type:'email'},{key:'relationship',label:'Relationship'},{key:'isPrimary',label:'Primary guardian',type:'select',options:[{value:'false',label:'No'},{value:'true',label:'Yes'}]}],{isPrimary:'false'},function(v){return raw('/api/students/'+id+'/guardians',{method:'POST',body:JSON.stringify({firstName:v.firstName,lastName:v.lastName,phone:v.phone,email:v.email||undefined,relationship:v.relationship,isPrimary:v.isPrimary==='true'})})})}
     var gid=e.target.dataset.parentPin;if(gid){return raw('/api/guardians/'+gid+'/portal-reset',{method:'POST',body:'{}'}).then(function(x){modal('<h2>Parent Portal PIN</h2><p class="muted">Give this PIN to the guardian securely.</p><div class="panel"><b style="font-size:28px">'+esc(x.pin)+'</b></div><p><a href="/parent" target="_blank" style="color:#45ddb2">Open Parent Portal</a></p>')}).catch(function(err){toast(err.message,true)})}
     gid=e.target.dataset.editGuardian;if(gid){var sid=e.target.dataset.studentId;var g=current360&&current360.guardians.find(function(x){return x.id===gid});if(!g)return;return form('Edit guardian',[{key:'firstName',label:'First name'},{key:'lastName',label:'Last name'},{key:'phone',label:'Phone'},{key:'email',label:'Email',type:'email'},{key:'relationship',label:'Relationship'},{key:'isPrimary',label:'Primary guardian',type:'select',options:[{value:'true',label:'Yes'},{value:'false',label:'No'}]}],{firstName:g.first_name,lastName:g.last_name,phone:g.phone,email:g.email||'',relationship:g.relationship,isPrimary:String(g.is_primary)},function(v){return raw('/api/students/'+sid+'/guardians/'+gid,{method:'PATCH',body:JSON.stringify({firstName:v.firstName,lastName:v.lastName,phone:v.phone,email:v.email||null,relationship:v.relationship,isPrimary:v.isPrimary==='true'})})})}
     gid=e.target.dataset.deleteGuardian;if(gid){var sid=e.target.dataset.studentId;return confirmDo('Remove this guardian from the student?',function(){return raw('/api/students/'+sid+'/guardians/'+gid,{method:'DELETE'})})}
   }
 }
 else if(p==='attendance'){
   var classes=await raw('/api/classes');
   E('content').innerHTML='<h1>Attendance</h1><div class="toolbar"><select id="attClass">'+classes.map(function(c){return'<option value="'+c.id+'">'+esc(c.name)+'</option>'}).join('')+'</select><input id="attDate" type="date" value="'+new Date().toISOString().slice(0,10)+'"><button id="loadAtt" class="primary">Load class</button></div><div id="attPanel" class="panel"><div class="empty">Choose a class and date.</div></div>';
   E('loadAtt').onclick=async function(){
     var cid=E('attClass').value,date=E('attDate').value,rows=await raw('/api/attendance?classroomId='+cid+'&date='+date);
     E('attPanel').innerHTML=rows.length?'<div class="actions" style="margin-bottom:10px"><button id="allPresent" class="ghost">Mark all present</button><button id="clearAtt" class="danger">Clear this date</button></div>'+rows.map(function(r){return'<div class="attendance-row" data-student="'+r.student_id+'"><div class="student"><b>'+esc(r.first_name+' '+r.last_name)+'</b><div class="muted">'+esc(r.admission_no)+'</div></div>'+['present','absent','late','excused'].map(function(s){return'<button class="mini '+(r.attendance_status===s?'sel':'')+'" data-status="'+s+'">'+s+'</button>'}).join('')+'</div>'}).join('')+'<button id="saveAtt" class="primary" style="margin-top:12px">Save attendance</button>':'<div class="empty">No students enrolled in this class.</div>';
     E('attPanel').onclick=function(e){var b=e.target.closest('[data-status]');if(b){var row=b.closest('[data-student]');row.querySelectorAll('[data-status]').forEach(function(x){x.classList.remove('sel')});b.classList.add('sel')}};
     var all=E('allPresent');if(all)all.onclick=function(){E('attPanel').querySelectorAll('[data-student]').forEach(function(row){row.querySelectorAll('[data-status]').forEach(function(x){x.classList.toggle('sel',x.dataset.status==='present')})})};
     var clearBtn=E('clearAtt');if(clearBtn)clearBtn.onclick=function(){confirmDo('Clear all attendance records for this class and date?',function(){return raw('/api/attendance?classroomId='+cid+'&date='+date,{method:'DELETE'})})};
     var save=E('saveAtt');if(save)save.onclick=async function(){var records=[];E('attPanel').querySelectorAll('[data-student]').forEach(function(row){var s=row.querySelector('.sel');if(s)records.push({studentId:row.dataset.student,status:s.dataset.status})});if(!records.length)return toast('Mark at least one student',true);await raw('/api/attendance/mark',{method:'POST',body:JSON.stringify({classroomId:cid,date:date,records:records})});toast('Attendance saved')}
   }
 }
 else if(p==='assessments'){
   var rr=await Promise.all([raw('/api/academic-years'),raw('/api/terms'),raw('/api/classes'),raw('/api/subjects'),raw('/api/assessments')]);var years=rr[0],terms=rr[1],classes=rr[2],subs=rr[3],as=rr[4];
   E('content').innerHTML='<div class="section"><h1>Assessments</h1><button id="addAssess" class="primary">New assessment</button></div><div class="panel">'+table(as,[{key:'name'},{key:'subject_name',label:'Subject'},{key:'classroom_name',label:'Class'},{key:'assessment_type',label:'Type'},{key:'max_score',label:'Max'},{key:'assessment_date',label:'Date'}],function(r){return'<button class="mini" data-score="'+r.id+'">Enter scores</button><button class="mini" data-edit-assess="'+r.id+'">Edit</button><button class="mini danger" data-delete-assess="'+r.id+'">Delete</button>'})+'</div>';
   E('addAssess').onclick=function(){form('New assessment',[{key:'academicYearId',label:'Academic year',type:'select',options:years.map(function(x){return{value:x.id,label:x.name}})},{key:'termId',label:'Term',type:'select',options:terms.map(function(x){return{value:x.id,label:x.name}})},{key:'classroomId',label:'Class',type:'select',options:classes.map(function(x){return{value:x.id,label:x.name}})},{key:'subjectId',label:'Subject',type:'select',options:subs.filter(function(x){return x.is_active}).map(function(x){return{value:x.id,label:x.name}})},{key:'name',label:'Assessment name'},{key:'assessmentType',label:'Type',type:'select',options:['classwork','homework','project','test','exam','other']},{key:'maxScore',label:'Maximum score',type:'number'},{key:'weight',label:'Weight %',type:'number'},{key:'assessmentDate',label:'Date',type:'date'}],{assessmentType:'test',maxScore:'100',weight:'100'},function(v){return raw('/api/assessments',{method:'POST',body:JSON.stringify({academicYearId:v.academicYearId,termId:v.termId,classroomId:v.classroomId,subjectId:v.subjectId,name:v.name,assessmentType:v.assessmentType,maxScore:Number(v.maxScore),weight:Number(v.weight),assessmentDate:v.assessmentDate||undefined})})})};
   E('content').onclick=async function(e){
     var id=e.target.dataset.editAssess;if(id){var a=as.find(function(x){return x.id===id});return form('Edit assessment',[{key:'name',label:'Name'},{key:'assessmentType',label:'Type',type:'select',options:['classwork','homework','project','test','exam','other']},{key:'maxScore',label:'Maximum score',type:'number'},{key:'weight',label:'Weight %',type:'number'},{key:'assessmentDate',label:'Date',type:'date'}],{name:a.name,assessmentType:a.assessment_type,maxScore:a.max_score,weight:a.weight,assessmentDate:a.assessment_date?String(a.assessment_date).slice(0,10):''},function(v){return raw('/api/assessments/'+id,{method:'PATCH',body:JSON.stringify({name:v.name,assessmentType:v.assessmentType,maxScore:Number(v.maxScore),weight:Number(v.weight),assessmentDate:v.assessmentDate||null})})})}
     id=e.target.dataset.deleteAssess;if(id){return confirmDo('Delete this assessment and all of its recorded scores?',function(){return raw('/api/assessments/'+id,{method:'DELETE'})})}
     id=e.target.dataset.score;if(!id)return;
     var x=await raw('/api/assessments/'+id+'/scores');
     modal('<h2>'+esc(x.assessment.name)+'</h2><p class="muted">Maximum score: '+esc(x.assessment.max_score)+'</p>'+x.students.map(function(s){return'<div class="row"><div><b>'+esc(s.first_name+' '+s.last_name)+'</b><div class="muted">'+esc(s.admission_no)+'</div></div><div><input type="number" min="0" max="'+esc(x.assessment.max_score)+'" data-score-student="'+s.student_id+'" value="'+esc(s.score==null?'':s.score)+'"></div></div>'}).join('')+'<button id="saveScores" class="primary">Save scores</button>');
     E('saveScores').onclick=async function(){var scores=[];E('modalBody').querySelectorAll('[data-score-student]').forEach(function(inp){if(inp.value!=='')scores.push({studentId:inp.dataset.scoreStudent,score:Number(inp.value)})});if(!scores.length)return toast('Enter at least one score',true);await raw('/api/assessments/'+id+'/scores',{method:'POST',body:JSON.stringify({scores:scores})});toast('Scores saved');close();page('assessments')}
   }
 }
 else if(p==='homework'){
   var rr=await Promise.all([raw('/api/academic-years'),raw('/api/terms'),raw('/api/classes'),raw('/api/subjects'),raw('/api/homework')]);var years=rr[0],terms=rr[1],classes=rr[2],subs=rr[3],hw=rr[4];
   E('content').innerHTML='<div class="section"><h1>Homework</h1><button id="addHomework" class="primary">Create homework</button></div><div class="panel">'+table(hw,[{key:'title'},{key:'subject_name',label:'Subject'},{key:'classroom_name',label:'Class'},{key:'due_at',label:'Due',render:function(r){return esc(r.due_at?new Date(r.due_at).toLocaleString():'') }},{key:'status',render:function(r){return badge(r.status)}}],function(r){return (r.status==='draft'?'<button class="mini" data-publish-hw="'+r.id+'">Publish</button>':'')+'<button class="mini" data-grade-hw="'+r.id+'">Submissions</button><button class="mini" data-edit-hw="'+r.id+'">Edit</button><button class="mini danger" data-delete-hw="'+r.id+'">Delete</button>'})+'</div>';
   E('addHomework').onclick=function(){form('Create homework',[{key:'academicYearId',label:'Academic year',type:'select',options:years.map(function(x){return{value:x.id,label:x.name}})},{key:'termId',label:'Term',type:'select',options:terms.map(function(x){return{value:x.id,label:x.name}})},{key:'classroomId',label:'Class',type:'select',options:classes.map(function(x){return{value:x.id,label:x.name}})},{key:'subjectId',label:'Subject',type:'select',options:subs.map(function(x){return{value:x.id,label:x.name}})},{key:'title',label:'Title'},{key:'instructions',label:'Instructions',type:'textarea'},{key:'dueAt',label:'Due date/time',type:'datetime-local'},{key:'maxScore',label:'Maximum score',type:'number'}],{},function(v){return raw('/api/homework',{method:'POST',body:JSON.stringify({academicYearId:v.academicYearId,termId:v.termId,classroomId:v.classroomId,subjectId:v.subjectId,title:v.title,instructions:v.instructions,dueAt:v.dueAt?new Date(v.dueAt).toISOString():undefined,maxScore:v.maxScore?Number(v.maxScore):undefined})})})};
   E('content').onclick=async function(e){
     var id=e.target.dataset.publishHw;if(id){await raw('/api/homework/'+id+'/publish',{method:'POST',body:'{}'});toast('Homework published');return page('homework')}
     id=e.target.dataset.deleteHw;if(id){return confirmDo('Delete this homework and its submissions?',function(){return raw('/api/homework/'+id,{method:'DELETE'})})}
     id=e.target.dataset.editHw;if(id){var h=hw.find(function(x){return x.id===id});return form('Edit homework',[{key:'title',label:'Title'},{key:'instructions',label:'Instructions',type:'textarea'},{key:'dueAt',label:'Due date/time',type:'datetime-local'},{key:'maxScore',label:'Maximum score',type:'number'},{key:'status',label:'Status',type:'select',options:['draft','published','closed']}],{title:h.title,instructions:h.instructions,dueAt:h.due_at?new Date(h.due_at).toISOString().slice(0,16):'',maxScore:h.max_score||'',status:h.status},function(v){return raw('/api/homework/'+id,{method:'PATCH',body:JSON.stringify({title:v.title,instructions:v.instructions,dueAt:v.dueAt?new Date(v.dueAt).toISOString():null,maxScore:v.maxScore?Number(v.maxScore):null,status:v.status})})})}
     id=e.target.dataset.gradeHw;if(id){var rows=await raw('/api/homework/'+id+'/submissions');var h=hw.find(function(x){return x.id===id});modal('<h2>'+esc(h.title)+'</h2>'+rows.map(function(s){return'<div class="row"><div><b>'+esc(s.first_name+' '+s.last_name)+'</b><div class="muted">'+esc(s.admission_no)+'</div></div><div><select data-hw-status="'+s.student_id+'"><option'+(s.status==='not_submitted'?' selected':'')+'>not_submitted</option><option'+(s.status==='submitted'?' selected':'')+'>submitted</option><option'+(s.status==='late'?' selected':'')+'>late</option><option'+(s.status==='graded'?' selected':'')+'>graded</option></select></div><div><input data-hw-score="'+s.student_id+'" type="number" value="'+esc(s.score==null?'':s.score)+'" placeholder="Score"></div></div>'}).join('')+'<button id="saveHwSubs" class="primary">Save submissions</button>');E('saveHwSubs').onclick=async function(){var records=[];E('modalBody').querySelectorAll('[data-hw-status]').forEach(function(sel){var score=E('modalBody').querySelector('[data-hw-score="'+sel.dataset.hwStatus+'"]');records.push({studentId:sel.dataset.hwStatus,status:sel.value,score:score&&score.value!==''?Number(score.value):null})});await raw('/api/homework/'+id+'/submissions',{method:'POST',body:JSON.stringify({records:records})});close();toast('Homework records saved')}}
   }
 }
 else if(p==='promotions'){
   var rr=await Promise.all([raw('/api/academic-years'),raw('/api/classes'),raw('/api/students'),raw('/api/promotions')]);var years=rr[0],classes=rr[1],students=rr[2],history=rr[3];
   E('content').innerHTML='<div class="section"><h1>Promotion & Rollover</h1><button id="runPromotion" class="primary">Promote students</button></div><div class="notice">Use this when moving students into a new academic year. Each action is recorded in the promotion history.</div><div class="panel" style="margin-top:12px">'+table(history,[{key:'first_name',label:'Student',render:function(r){return esc(r.first_name+' '+r.last_name)}},{key:'from_year',label:'From Year'},{key:'from_class',label:'From Class'},{key:'to_year',label:'To Year'},{key:'to_class',label:'To Class'},{key:'outcome',render:function(r){return badge(r.outcome)}}])+'</div>';
   E('runPromotion').onclick=function(){if(years.length<2)return toast('Create the next academic year first',true);modal('<h2>Promotion / Rollover</h2><label>From academic year</label><select id="promoFrom">'+years.map(function(y){return'<option value="'+y.id+'">'+esc(y.name)+'</option>'}).join('')+'</select><label>To academic year</label><select id="promoTo">'+years.map(function(y){return'<option value="'+y.id+'">'+esc(y.name)+'</option>'}).join('')+'</select><label>Student</label><select id="promoStudent">'+students.filter(function(s){return s.status==='active'}).map(function(s){return'<option value="'+s.id+'">'+esc(s.first_name+' '+s.last_name+' • '+(s.classroom_name||''))+'</option>'}).join('')+'</select><label>Outcome</label><select id="promoOutcome"><option>promoted</option><option>repeated</option><option>completed</option></select><label>Destination class</label><select id="promoClass">'+classes.map(function(c){return'<option value="'+c.id+'" data-year="'+c.academic_year_id+'">'+esc(c.name)+'</option>'}).join('')+'</select><button id="savePromotion" class="primary">Process promotion</button>');E('savePromotion').onclick=async function(){var outcome=E('promoOutcome').value;var rec={studentId:E('promoStudent').value,outcome:outcome};if(outcome!=='completed')rec.toClassroomId=E('promoClass').value;await raw('/api/promotions/batch',{method:'POST',body:JSON.stringify({fromAcademicYearId:E('promoFrom').value,toAcademicYearId:E('promoTo').value,records:[rec]})});close();toast('Promotion processed');page('promotions')}}
 }
 else if(p==='grading'){
   var bands=await raw('/api/grading-bands');
   E('content').innerHTML='<div class="section"><h1>Grading Setup</h1><button id="addBand" class="primary">Add grading band</button></div><div class="panel">'+table(bands,[{key:'name',label:'Grade'},{key:'min_percentage',label:'Min %'},{key:'max_percentage',label:'Max %'},{key:'remark'},{key:'is_active',label:'Status',render:function(r){return badge(r.is_active?'active':'inactive')}}],function(r){return'<button class="mini" data-edit-band="'+r.id+'">Edit</button><button class="mini danger" data-delete-band="'+r.id+'">Delete</button>'})+'</div>';
   E('addBand').onclick=function(){form('Add grading band',[{key:'name',label:'Grade'},{key:'minPercentage',label:'Minimum %',type:'number'},{key:'maxPercentage',label:'Maximum %',type:'number'},{key:'remark',label:'Remark'},{key:'sortOrder',label:'Sort order',type:'number'}],{},function(v){return raw('/api/grading-bands',{method:'POST',body:JSON.stringify({name:v.name,minPercentage:Number(v.minPercentage),maxPercentage:Number(v.maxPercentage),remark:v.remark,sortOrder:Number(v.sortOrder||0)})})})};
   E('content').onclick=function(e){var id=e.target.dataset.editBand;if(id){var b=bands.find(function(x){return x.id===id});return form('Edit grading band',[{key:'name',label:'Grade'},{key:'minPercentage',label:'Minimum %',type:'number'},{key:'maxPercentage',label:'Maximum %',type:'number'},{key:'remark',label:'Remark'},{key:'sortOrder',label:'Sort order',type:'number'},{key:'isActive',label:'Status',type:'select',options:[{value:'true',label:'Active'},{value:'false',label:'Inactive'}]}],{name:b.name,minPercentage:b.min_percentage,maxPercentage:b.max_percentage,remark:b.remark||'',sortOrder:b.sort_order,isActive:String(b.is_active)},function(v){return raw('/api/grading-bands/'+id,{method:'PATCH',body:JSON.stringify({name:v.name,minPercentage:Number(v.minPercentage),maxPercentage:Number(v.maxPercentage),remark:v.remark||null,sortOrder:Number(v.sortOrder||0),isActive:v.isActive==='true'})})})}id=e.target.dataset.deleteBand;if(id){return confirmDo('Delete this grading band?',function(){return raw('/api/grading-bands/'+id,{method:'DELETE'})})}}
 }
 else if(p==='fees'){
   var rr=await Promise.all([raw('/api/academic-years'),raw('/api/terms'),raw('/api/grade-levels'),raw('/api/classes'),raw('/api/fee-items'),raw('/api/students'),raw('/api/fees/open-items'),raw('/api/payments?limit=100')]);var years=rr[0],terms=rr[1],grades=rr[2],classes=rr[3],fees=rr[4],students=rr[5],openFees=rr[6],payments=rr[7];
   E('content').innerHTML='<div class="section"><h1>Fees & Payments</h1><div class="actions"><button id="newFee" class="primary">Create fee</button><button id="recordPay" class="ghost">Record payment</button></div></div><div class="panel"><h3>Fee Items</h3>'+table(fees,[{key:'name'},{key:'grade_name',label:'Grade'},{key:'term_name',label:'Term'},{key:'amount',render:function(r){return'GHS '+Number(r.amount).toFixed(2)}}],function(r){return'<button class="mini" data-assign-fee="'+r.id+'">Assign</button><button class="mini" data-edit-fee="'+r.id+'">Edit</button><button class="mini danger" data-delete-fee="'+r.id+'">Delete</button>'})+'</div><div class="section"><h2>Recent Payments</h2></div><div class="panel">'+table(payments,[{key:'first_name',label:'Student',render:function(r){return esc(r.first_name+' '+r.last_name)}},{key:'fee_name',label:'Fee'},{key:'amount',render:function(r){return'GHS '+Number(r.amount).toFixed(2)}},{key:'payment_method',label:'Method'},{key:'reference'},{key:'voided_at',label:'Status',render:function(r){return badge(r.voided_at?'voided':'posted')}}],function(r){return '<button class="mini" data-receipt="'+r.id+'">Receipt</button>'+(r.voided_at?'':'<button class="mini danger" data-void-payment="'+r.id+'">Void</button>')})+'</div>';
   E('newFee').onclick=function(){form('Create fee item',[{key:'academicYearId',label:'Academic year',type:'select',options:years.map(function(x){return{value:x.id,label:x.name}})},{key:'termId',label:'Term',type:'select',options:[{value:'',label:'Whole year'}].concat(terms.map(function(x){return{value:x.id,label:x.name}}))},{key:'gradeLevelId',label:'Grade',type:'select',options:[{value:'',label:'All grades'}].concat(grades.map(function(x){return{value:x.id,label:x.name}}))},{key:'name',label:'Fee name'},{key:'amount',label:'Amount',type:'number'}],{},function(v){return raw('/api/fee-items',{method:'POST',body:JSON.stringify({academicYearId:v.academicYearId,termId:v.termId||undefined,gradeLevelId:v.gradeLevelId||undefined,name:v.name,amount:Number(v.amount)})})})};
   E('recordPay').onclick=function(){
     if(!openFees.length)return toast('There are no outstanding assigned fees',true);
     modal('<h2>Record payment</h2><label>Outstanding fee</label><select id="payFee">'+openFees.map(function(x){return'<option value="'+x.student_fee_id+'">'+esc(x.first_name+' '+x.last_name+' • '+x.fee_name+' • Balance GHS '+Number(x.balance).toFixed(2))+'</option>'}).join('')+'</select><label>Amount</label><input id="payAmount" type="number" min="0.01" step="0.01"><label>Payment method</label><select id="payMethod"><option>cash</option><option>mobile_money</option><option>bank</option><option>card</option><option>other</option></select><label>Reference</label><input id="payRef"><button id="savePayment" class="primary">Save payment</button>');
     E('savePayment').onclick=async function(){var item=openFees.find(function(x){return x.student_fee_id===E('payFee').value});if(!item)return;var amount=Number(E('payAmount').value);if(!amount||amount<=0)return toast('Enter a valid amount',true);if(amount>Number(item.balance))return toast('Amount cannot exceed the outstanding balance',true);await raw('/api/payments',{method:'POST',body:JSON.stringify({studentId:item.student_id,studentFeeId:item.student_fee_id,amount:amount,paymentMethod:E('payMethod').value,reference:E('payRef').value||undefined})});close();toast('Payment recorded');page('fees')}
   };
   E('content').onclick=function(e){
     var id=e.target.dataset.assignFee;if(id){return form('Assign fee',[{key:'classroomId',label:'Class',type:'select',options:classes.map(function(c){return{value:c.id,label:c.name}})}],{},function(v){return raw('/api/fees/assign',{method:'POST',body:JSON.stringify({feeItemId:id,classroomId:v.classroomId})})})}
     id=e.target.dataset.editFee;if(id){var f=fees.find(function(x){return x.id===id});return form('Edit fee item',[{key:'name',label:'Fee name'},{key:'amount',label:'Amount',type:'number'},{key:'mandatory',label:'Mandatory',type:'select',options:[{value:'true',label:'Yes'},{value:'false',label:'No'}]}],{name:f.name,amount:f.amount,mandatory:String(f.mandatory)},function(v){return raw('/api/fee-items/'+id,{method:'PATCH',body:JSON.stringify({name:v.name,amount:Number(v.amount),mandatory:v.mandatory==='true'})})})}
     id=e.target.dataset.deleteFee;if(id){return confirmDo('Delete this fee item? It cannot be deleted after valid payments have been posted.',function(){return raw('/api/fee-items/'+id,{method:'DELETE'})})}
     id=e.target.dataset.receipt;if(id){return raw('/api/payments/'+id+'/receipt').then(function(r){modal('<h2>Payment Receipt</h2><div class="panel"><b>'+esc(r.school_name)+'</b><p class="muted">'+esc(r.school_address||'')+'<br>'+esc(r.school_phone||'')+' '+esc(r.school_email||'')+'</p><hr style="border-color:#203844"><p><b>Receipt:</b> '+esc(r.id)+'</p><p><b>Student:</b> '+esc(r.first_name+' '+r.last_name)+' ('+esc(r.admission_no)+')</p><p><b>Fee:</b> '+esc(r.fee_name||'General payment')+'</p><p><b>Amount:</b> GHS '+Number(r.amount).toFixed(2)+'</p><p><b>Method:</b> '+esc(r.payment_method)+'</p><p><b>Reference:</b> '+esc(r.reference||'')+'</p><p><b>Date:</b> '+esc(new Date(r.paid_at).toLocaleString())+'</p>'+ (r.voided_at?'<p style="color:#ff7482"><b>VOIDED:</b> '+esc(r.void_reason||'')+'</p>':'') +'</div><button id="printReceipt" class="primary">Print receipt</button>');E('printReceipt').onclick=function(){window.print()}}).catch(function(err){toast(err.message,true)})}
     id=e.target.dataset.voidPayment;if(id){var reason=prompt('Reason for voiding this payment:');if(reason&&reason.trim())return raw('/api/payments/'+id+'/void',{method:'POST',body:JSON.stringify({reason:reason.trim()})}).then(function(){toast('Payment voided');page('fees')}).catch(function(err){toast(err.message,true)})}
   }
 }
 else if(p==='timetable'){
   var rr=await Promise.all([raw('/api/academic-years'),raw('/api/terms'),raw('/api/classes'),raw('/api/subjects'),raw('/api/timetable')]);var years=rr[0],terms=rr[1],classes=rr[2],subs=rr[3],tt=rr[4];
   E('content').innerHTML='<div class="section"><h1>Timetable</h1><button id="addSlot" class="primary">Add period</button></div><div class="panel">'+table(tt,[{key:'day_of_week',label:'Day',render:function(r){return['','Mon','Tue','Wed','Thu','Fri'][r.day_of_week]}},{key:'start_time',label:'Start'},{key:'end_time',label:'End'},{key:'classroom_name',label:'Class'},{key:'subject_name',label:'Subject'},{key:'room'}],function(r){return'<button class="mini" data-edit-slot="'+r.id+'">Edit</button><button class="mini danger" data-delete-slot="'+r.id+'">Delete</button>'})+'</div>';
   E('addSlot').onclick=function(){form('Add timetable period',[{key:'academicYearId',label:'Academic year',type:'select',options:years.map(function(x){return{value:x.id,label:x.name}})},{key:'termId',label:'Term',type:'select',options:[{value:'',label:'No specific term'}].concat(terms.map(function(x){return{value:x.id,label:x.name}}))},{key:'classroomId',label:'Class',type:'select',options:classes.map(function(x){return{value:x.id,label:x.name}})},{key:'subjectId',label:'Subject',type:'select',options:subs.filter(function(x){return x.is_active}).map(function(x){return{value:x.id,label:x.name}})},{key:'dayOfWeek',label:'Day',type:'select',options:[{value:'1',label:'Monday'},{value:'2',label:'Tuesday'},{value:'3',label:'Wednesday'},{value:'4',label:'Thursday'},{value:'5',label:'Friday'}]},{key:'startTime',label:'Start time',type:'time'},{key:'endTime',label:'End time',type:'time'},{key:'room',label:'Room'}],{},function(v){return raw('/api/timetable',{method:'POST',body:JSON.stringify({academicYearId:v.academicYearId,termId:v.termId||undefined,classroomId:v.classroomId,subjectId:v.subjectId,dayOfWeek:Number(v.dayOfWeek),startTime:v.startTime,endTime:v.endTime,room:v.room||undefined})})})};
   E('content').onclick=function(e){
     var id=e.target.dataset.editSlot;if(id){var x=tt.find(function(r){return r.id===id});return form('Edit timetable period',[{key:'subjectId',label:'Subject',type:'select',options:subs.map(function(s){return{value:s.id,label:s.name}})},{key:'dayOfWeek',label:'Day',type:'select',options:[{value:'1',label:'Monday'},{value:'2',label:'Tuesday'},{value:'3',label:'Wednesday'},{value:'4',label:'Thursday'},{value:'5',label:'Friday'}]},{key:'startTime',label:'Start time',type:'time'},{key:'endTime',label:'End time',type:'time'},{key:'room',label:'Room'}],{subjectId:x.subject_id,dayOfWeek:String(x.day_of_week),startTime:String(x.start_time).slice(0,5),endTime:String(x.end_time).slice(0,5),room:x.room||''},function(v){return raw('/api/timetable/'+id,{method:'PATCH',body:JSON.stringify({subjectId:v.subjectId,dayOfWeek:Number(v.dayOfWeek),startTime:v.startTime,endTime:v.endTime,room:v.room||null})})})}
     id=e.target.dataset.deleteSlot;if(id){return confirmDo('Delete this timetable period?',function(){return raw('/api/timetable/'+id,{method:'DELETE'})})}
   }
 }
 else if(p==='reports'){
   var rr=await Promise.all([raw('/api/students'),raw('/api/terms'),raw('/api/staff/core-users').catch(function(){return[]})]);var students=rr[0],terms=rr[1],coreUsers=rr[2];
   var remembered=sessionStorage.getItem('rx_report_student')||'';sessionStorage.removeItem('rx_report_student');
   function staffName(id){var u=coreUsers.find(function(x){return x.id===id});return u?u.first_name+' '+u.last_name:'—'}
   E('content').innerHTML='<div class="section"><div><h1>Report Cards</h1><p class="muted">Generate a complete, printable term report with grades, attendance, class position and comments.</p></div></div><div class="panel report-controls"><div class="row"><div><label>Student</label><select id="reportStudent">'+students.map(function(s){return'<option value="'+s.id+'"'+(s.id===remembered?' selected':'')+'>'+esc(s.first_name+' '+s.last_name+' ('+s.admission_no+')')+'</option>'}).join('')+'</select></div><div><label>Term</label><select id="reportTerm">'+terms.map(function(t){return'<option value="'+t.id+'"'+(t.status==='active'?' selected':'')+'>'+esc(t.name)+'</option>'}).join('')+'</select></div></div><button id="loadReport" class="primary">Generate report card</button></div><div id="reportOut"></div>';
   E('loadReport').onclick=async function(){
     var sid=E('reportStudent').value,tid=E('reportTerm').value,r=await raw('/api/report-cards/'+sid+'?termId='+tid),comments=r.comments||{},perf=r.performance||{},att=r.attendance||{},school=r.school||{},term=r.term||{},st=r.student||{};
     var position=perf.classPosition?(perf.classPosition+' / '+perf.classSize):'—';
     var teacher=staffName(st.class_teacher_os_user_id);
     E('reportOut').innerHTML='<div id="printableReport" class="report-card">'+
       '<div class="report-school-head"><div class="report-logo">RX</div><div><h1>'+esc(school.school_name||'Revolt-X School')+'</h1><p>'+esc(school.motto||'')+'</p><small>'+esc([school.address,school.phone,school.email].filter(Boolean).join(' • '))+'</small></div><div class="report-term"><b>STUDENT REPORT CARD</b><span>'+esc(term.academic_year||st.academic_year||'')+'</span><span>'+esc(term.name||'')+'</span></div></div>'+
       '<div class="report-student-grid"><div><span>Student</span><b>'+esc(st.first_name+' '+(st.middle_name||'')+' '+st.last_name)+'</b></div><div><span>Admission No.</span><b>'+esc(st.admission_no)+'</b></div><div><span>Class</span><b>'+esc(st.classroom_name||'—')+'</b></div><div><span>Grade</span><b>'+esc(st.grade_name||'—')+'</b></div><div><span>Class Teacher</span><b>'+esc(teacher)+'</b></div><div><span>Term Dates</span><b>'+esc(String(term.start_date||'').slice(0,10))+' - '+esc(String(term.end_date||'').slice(0,10))+'</b></div></div>'+
       '<div class="report-summary"><div><span>Overall Average</span><b>'+(perf.overallAverage==null?'—':esc(perf.overallAverage)+'%')+'</b></div><div><span>Class Position</span><b>'+esc(position)+'</b></div><div><span>Attendance Rate</span><b>'+esc(att.rate||0)+'%</b></div><div><span>Days Present</span><b>'+esc(att.present||0)+'</b></div><div><span>Days Absent</span><b>'+esc(att.absent||0)+'</b></div></div>'+
       '<div class="report-section"><h3>Academic Performance</h3><table class="report-table"><thead><tr><th>Subject</th><th>Average %</th><th>Grade</th><th>Remark</th><th>Assessments</th></tr></thead><tbody>'+r.subjects.map(function(x){return'<tr><td><b>'+esc(x.subject_name)+'</b></td><td>'+esc(x.percentage==null?'—':x.percentage)+'</td><td><b>'+esc(x.grade||'—')+'</b></td><td>'+esc(x.remark||'')+'</td><td>'+esc(x.assessment_count||0)+'</td></tr>'}).join('')+'</tbody></table></div>'+
       '<div class="report-section"><h3>Attendance Summary</h3><div class="report-attendance"><span><b>'+esc(att.present||0)+'</b> Present</span><span><b>'+esc(att.absent||0)+'</b> Absent</span><span><b>'+esc(att.late||0)+'</b> Late</span><span><b>'+esc(att.excused||0)+'</b> Excused</span><span><b>'+esc(att.total||0)+'</b> Recorded days</span></div></div>'+
       '<div class="report-comments"><div><h4>Class Teacher Comment</h4><p>'+esc(comments.class_teacher_comment||'No comment entered.')+'</p><h4>Conduct</h4><p>'+esc(comments.conduct||'—')+'</p><h4>Interests</h4><p>'+esc(comments.interest||'—')+'</p></div><div><h4>Headteacher Comment</h4><p>'+esc(comments.headteacher_comment||'No comment entered.')+'</p><h4>Next Term Begins</h4><p>'+esc(comments.next_term_begins?String(comments.next_term_begins).slice(0,10):'—')+'</p></div></div>'+
       '<div class="report-signatures"><div><span>Class Teacher</span><b>'+esc(teacher)+'</b></div><div><span>Headteacher Signature</span><b>________________________</b></div><div><span>Parent / Guardian</span><b>________________________</b></div></div>'+
       '<div class="report-footer">Generated by Revolt-X School • '+esc(new Date(r.generatedAt).toLocaleString())+'</div>'+
     '</div><div class="actions report-actions"><button id="editComments" class="ghost">Edit comments</button><button id="printReport" class="primary">Print / Save PDF</button></div>';
     E('printReport').onclick=function(){window.print()};
     E('editComments').onclick=function(){form('Report comments',[{key:'classTeacherComment',label:'Class teacher comment',type:'textarea'},{key:'headteacherComment',label:'Headteacher comment',type:'textarea'},{key:'conduct',label:'Conduct'},{key:'interest',label:'Interest',type:'textarea'},{key:'nextTermBegins',label:'Next term begins',type:'date'}],{classTeacherComment:comments.class_teacher_comment||'',headteacherComment:comments.headteacher_comment||'',conduct:comments.conduct||'',interest:comments.interest||'',nextTermBegins:comments.next_term_begins?String(comments.next_term_begins).slice(0,10):''},function(v){return raw('/api/report-comments/'+sid,{method:'PUT',body:JSON.stringify({termId:tid,classTeacherComment:v.classTeacherComment||null,headteacherComment:v.headteacherComment||null,conduct:v.conduct||null,interest:v.interest||null,nextTermBegins:v.nextTermBegins||null})})})}
   };
   if(remembered&&E('reportStudent').value){setTimeout(function(){E('loadReport').click()},0)}
 }
 else if(p==='announcements'){
   var rr=await Promise.all([raw('/api/announcements'),raw('/api/classes')]);var notes=rr[0],classes=rr[1];
   E('content').innerHTML='<div class="section"><h1>Announcements</h1><button id="addAnnouncement" class="primary">New announcement</button></div><div class="panel">'+table(notes,[{key:'title'},{key:'audience'},{key:'classroom_name',label:'Class'},{key:'status',render:function(r){return badge(r.status)}},{key:'published_at',label:'Published',render:function(r){return esc(r.published_at?new Date(r.published_at).toLocaleString():'')}}],function(r){return'<button class="mini" data-edit-note="'+r.id+'">Edit</button><button class="mini danger" data-delete-note="'+r.id+'">Delete</button>'})+'</div>';
   E('addAnnouncement').onclick=function(){form('New announcement',[{key:'audience',label:'Audience',type:'select',options:['all','staff','parents','students','class']},{key:'classroomId',label:'Class (if class audience)',type:'select',options:[{value:'',label:'None'}].concat(classes.map(function(c){return{value:c.id,label:c.name}}))},{key:'title',label:'Title'},{key:'body',label:'Message',type:'textarea'},{key:'status',label:'Status',type:'select',options:['draft','published']}],{audience:'all',status:'draft'},function(v){return raw('/api/announcements',{method:'POST',body:JSON.stringify({audience:v.audience,classroomId:v.classroomId||null,title:v.title,body:v.body,status:v.status})})})};
   E('content').onclick=function(e){var id=e.target.dataset.editNote;if(id){var n=notes.find(function(x){return x.id===id});return form('Edit announcement',[{key:'audience',label:'Audience',type:'select',options:['all','staff','parents','students','class']},{key:'classroomId',label:'Class',type:'select',options:[{value:'',label:'None'}].concat(classes.map(function(c){return{value:c.id,label:c.name}}))},{key:'title',label:'Title'},{key:'body',label:'Message',type:'textarea'},{key:'status',label:'Status',type:'select',options:['draft','published','archived']}],{audience:n.audience,classroomId:n.classroom_id||'',title:n.title,body:n.body,status:n.status},function(v){return raw('/api/announcements/'+id,{method:'PATCH',body:JSON.stringify({audience:v.audience,classroomId:v.classroomId||null,title:v.title,body:v.body,status:v.status})})})}id=e.target.dataset.deleteNote;if(id){return confirmDo('Delete this announcement?',function(){return raw('/api/announcements/'+id,{method:'DELETE'})})}}
 }
 else if(p==='parentportal'){
   E('content').innerHTML='<h1>Parent Portal</h1><div class="two"><div class="panel"><h3>Guardian access</h3><p class="muted">Open a student record, then use <b>Portal PIN</b> beside a guardian to generate or reset secure access.</p><button id="openParentPortal" class="primary">Open Parent Portal</button></div><div class="panel"><h3>What parents can see</h3><p>Linked children, class information, attendance summary, homework, announcements, fee statements, payments and the latest report card.</p></div></div>';E('openParentPortal').onclick=function(){window.open('/parent','_blank')}
 }
 else if(p==='portals'){
   E('content').innerHTML='<h1>Portals & Interfaces</h1><div class="grid"><div class="panel"><h3>School Administration</h3><p class="muted">Full operational management for administrators, headteachers, registrars and bursars.</p><button class="ghost" disabled>Current interface</button></div><div class="panel"><h3>Teacher Portal</h3><p class="muted">Focused workspace for assigned classes, attendance, homework, assessments, timetable and reports.</p><button class="primary" data-open-portal="/teacher">Open Teacher Portal</button></div><div class="panel"><h3>Parent Portal</h3><p class="muted">Guardians can view children, attendance, fees, homework, announcements and report cards.</p><button class="primary" data-open-portal="/parent">Open Parent Portal</button></div><div class="panel"><h3>Student Portal</h3><p class="muted">Students can view homework, results, timetable and school announcements.</p><button class="primary" data-open-portal="/student">Open Student Portal</button></div><div class="panel"><h3>Public Admissions</h3><p class="muted">Prospective families can apply online and check application status.</p><button class="primary" data-open-portal="/admissions">Open Admissions</button></div></div><div class="notice" style="margin-top:12px">Parent and Student portal PINs are generated from the relevant student record. Production deployment will replace development preview access for staff with the Core OS sign-in flow.</div>';
   E('content').onclick=function(e){var p=e.target.dataset.openPortal;if(p)window.open(p,'_blank')}
 }
 else if(p==='staff'){
   var rr=await Promise.all([raw('/api/staff/core-users'),raw('/api/staff/module-memberships'),raw('/api/teacher-assignments')]);var users=rr[0],memberships=rr[1],assignments=rr[2];
   function schoolRole(uid){var m=memberships.find(function(x){return x.os_user_id===uid});return m?m.role:'Not assigned'}
   function userName(id){var u=users.find(function(x){return x.id===id});return u?u.first_name+' '+u.last_name:id}
   var teachers=users.filter(function(u){var m=memberships.find(function(x){return x.os_user_id===u.id});return m&&m.role==='teacher'&&m.status==='active'});
   E('content').innerHTML='<div class="section"><div><h1>Staff & Teachers</h1><p class="muted">Create staff identities here. Class, subject and teacher assignments are managed centrally in Academic Manager.</p></div><div class="actions"><button id="addTeacher" class="primary">Add teacher</button><button id="assignStaff" class="ghost">Assign school role</button></div></div>'+
   '<div class="grid staff-stats"><div class="panel stat"><span class="muted">Core OS staff</span><b>'+esc(users.length)+'</b></div><div class="panel stat"><span class="muted">Teachers</span><b>'+esc(teachers.length)+'</b></div><div class="panel stat"><span class="muted">Active teaching assignments</span><b>'+esc(assignments.filter(function(a){return a.is_active}).length)+'</b></div><div class="panel stat"><span class="muted">School roles</span><b>'+esc(memberships.filter(function(m){return m.status==='active'}).length)+'</b></div></div>'+
   '<div class="section"><h2>Staff Directory</h2></div><div class="panel">'+table(users,[{key:'first_name',label:'Staff Member',render:function(u){return '<b>'+esc(u.first_name+' '+u.last_name)+'</b><br><span class="muted">'+esc(u.email)+'</span>'}},{key:'job_title',label:'Job Title'},{key:'employee_number',label:'Staff No.'},{key:'id',label:'School Role',render:function(u){return badge(schoolRole(u.id))}},{key:'membership_status',label:'Core Status',render:function(u){return badge(u.membership_status)}}])+'</div>'+
   '<div class="section"><div><h2>Teaching Assignment Summary</h2><p class="muted">Assignments are shown here for visibility only.</p></div><button id="openAcademicManager" class="primary">Open Academic Manager</button></div><div class="panel">'+table(assignments.filter(function(a){return a.is_active}),[{key:'teacher_os_user_id',label:'Teacher',render:function(a){return '<b>'+esc(userName(a.teacher_os_user_id))+'</b>'}},{key:'classroom_name',label:'Class'},{key:'subject_name',label:'Subject',render:function(a){return esc(a.subject_name||'Class teacher / all subjects')}}])+'</div>'+
   '<div class="section"><h2>School Access Roles</h2></div><div class="panel">'+table(memberships,[{key:'os_user_id',label:'Staff',render:function(x){return esc(userName(x.os_user_id))}},{key:'role',render:function(x){return badge(x.role)}},{key:'status',render:function(x){return badge(x.status)}}],function(r){return '<button class="mini" data-edit-staff="'+r.id+'">Edit</button><button class="mini danger" data-remove-staff="'+r.id+'">Remove</button>'})+'</div>';
   E('addTeacher').onclick=function(){form('Create teacher',[{key:'firstName',label:'First name'},{key:'lastName',label:'Last name'},{key:'email',label:'Email',type:'email'},{key:'jobTitle',label:'Job title'},{key:'employeeNumber',label:'Staff number'}],{jobTitle:'Teacher'},function(v){return raw('/api/staff/teachers',{method:'POST',body:JSON.stringify({firstName:v.firstName,lastName:v.lastName,email:v.email,jobTitle:v.jobTitle||'Teacher',employeeNumber:v.employeeNumber||undefined})})})};
   E('assignStaff').onclick=function(){form('Assign school role',[{key:'osUserId',label:'Core OS user',type:'select',options:users.map(function(u){return{value:u.id,label:u.first_name+' '+u.last_name+' ('+u.email+')'}})},{key:'role',label:'School role',type:'select',options:['school_admin','headteacher','teacher','bursar','registrar']},{key:'status',label:'Status',type:'select',options:['active','suspended']}],{role:'teacher',status:'active'},function(v){return raw('/api/staff/module-memberships',{method:'POST',body:JSON.stringify(v)})})};
   E('openAcademicManager').onclick=function(){page('classes')};
   E('content').onclick=function(e){
     var id=e.target.dataset.editStaff;if(id){var x=memberships.find(function(r){return r.id===id});return form('Edit school access',[{key:'role',label:'School role',type:'select',options:['school_admin','headteacher','teacher','bursar','registrar']},{key:'status',label:'Status',type:'select',options:['active','suspended']}],{role:x.role,status:x.status},function(v){return raw('/api/staff/module-memberships/'+id,{method:'PATCH',body:JSON.stringify(v)})})}
     id=e.target.dataset.removeStaff;if(id){return confirmDo('Remove this user from the School application?',function(){return raw('/api/staff/module-memberships/'+id,{method:'DELETE'})})}
   }
 }
 }catch(e){E('content').innerHTML='<div class="panel"><h3>Could not load this area</h3><p class="muted">'+esc(e.message)+'</p><button class="ghost" id="retry">Retry</button></div>';E('retry').onclick=function(){page(p)}}
}
boot();
})();
</script>
</body></html>`;
