import Fastify from 'fastify'; import cors from '@fastify/cors'; import helmet from '@fastify/helmet'; import rateLimit from '@fastify/rate-limit'; import { ZodError } from 'zod';
import type { Config } from './config.js'; import type { Db } from './db/index.js'; import { AppError } from './core/errors.js'; import { verifyAccessToken } from './auth/service.js'; import { authRoutes } from './auth/routes.js'; import { organisationRoutes } from './routes/organisation.js'; import { userRoutes } from './routes/users.js'; import { operationRoutes } from './routes/operations.js'; import { workflowRoutes } from './routes/workflows.js'; import { platformRoutes } from './routes/platform.js';

export async function buildApp({db,config}:{db:Db;config:Config}){
 const app=Fastify({logger:config.NODE_ENV!=='test',trustProxy:true,requestIdHeader:'x-request-id'});
 await app.register(helmet,{contentSecurityPolicy:false});await app.register(cors,{origin:config.CORS_ORIGINS==='*'?true:config.CORS_ORIGINS.split(',').map(v=>v.trim()),credentials:true});await app.register(rateLimit,{max:200,timeWindow:'1 minute'});
 app.decorateRequest('auth',null);app.addHook('onRequest',async request=>{const header=request.headers.authorization;if(!header)return;const [scheme,token]=header.split(' ');if(scheme!=='Bearer'||!token)throw new AppError(401,'UNAUTHORIZED','Malformed authorization header');request.auth=await verifyAccessToken(config,token);const active=await db.query(`SELECT 1 FROM sessions s JOIN organisation_memberships m ON m.user_id=s.user_id AND m.organisation_id=s.organisation_id WHERE s.id=$1 AND s.user_id=$2 AND s.organisation_id=$3 AND s.revoked_at IS NULL AND s.expires_at>now() AND m.status='active'`,[request.auth.sessionId,request.auth.userId,request.auth.organisationId]);if(!active.rowCount)throw new AppError(401,'UNAUTHORIZED','Session is no longer active');});
 app.get('/',async(_r,reply)=>reply.type('text/html').send(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Revolt-X OS</title><style>body{margin:0;background:#07111f;color:#eaf2ff;font-family:Arial,sans-serif}#app{min-height:100vh}</style></head><body><div id="app"></div><script type="module" src="/ui/app.js"></script></body></html>`));
 app.get('/ui/app.js',async(_r,reply)=>reply.type('application/javascript').send((await import('./ui.js')).uiScript));
 app.get('/health/live',async()=>({status:'ok'}));app.get('/health/ready',async(_r,reply)=>{try{await db.query('SELECT 1');return{status:'ready'};}catch{return reply.code(503).send({status:'unavailable'});}});
 await app.register(authRoutes,{db,config});await app.register(organisationRoutes,{db});await app.register(userRoutes,{db});await app.register(operationRoutes,{db});await app.register(workflowRoutes,{db});await app.register(platformRoutes,{db,config});
 app.setNotFoundHandler((request,reply)=>reply.code(404).send({error:{code:'NOT_FOUND',message:`Route ${request.method} ${request.url} not found`,requestId:request.id}}));
 app.setErrorHandler((error,request,reply)=>{if(error instanceof ZodError)return reply.code(400).send({error:{code:'VALIDATION_ERROR',message:'Request validation failed',details:error.issues,requestId:request.id}});if(error instanceof AppError)return reply.code(error.statusCode).send({error:{code:error.code,message:error.message,details:error.details,requestId:request.id}});request.log.error(error);return reply.code(500).send({error:{code:'INTERNAL_ERROR',message:'An unexpected error occurred',requestId:request.id}});});return app;
}
