import Fastify from 'fastify';import cors from '@fastify/cors';import helmet from '@fastify/helmet';import rateLimit from '@fastify/rate-limit';import{ZodError}from'zod';import type{Config}from'./config.js';import type{Db}from'./db/index.js';import{AppError}from'./core/errors.js';import{verifyAccessToken}from'./auth/service.js';import{authRoutes}from'./auth/routes.js';import{previewRoutes}from'./auth/preview.js';import{organisationRoutes}from'./routes/organisation.js';import{userRoutes}from'./routes/users.js';import{operationRoutes}from'./routes/operations.js';import{workflowRoutes}from'./routes/workflows.js';import{platformRoutes}from'./routes/platform.js';import{commercialRoutes}from'./routes/commercial.js';import{internalSchoolRoutes}from'./routes/internal-school.js';import{osFrontend}from'./ui.js';
export async function buildApp({db,config}:{db:Db;config:Config}){const app=Fastify({logger:config.NODE_ENV!=='test',trustProxy:true,requestIdHeader:'x-request-id'});await app.register(helmet,{contentSecurityPolicy:false});await app.register(cors,{origin:config.CORS_ORIGINS==='*'?true:config.CORS_ORIGINS.split(',').map(v=>v.trim()),credentials:true});await app.register(rateLimit,{
    max:200,
    timeWindow:'1 minute',
    allowList:request=>{
      if(request.url.startsWith('/health/'))return true;
      const trustedSchool=Boolean(config.SCHOOL_SERVICE_KEY)
        && request.headers['x-revolt-service-key']===config.SCHOOL_SERVICE_KEY;
      return Boolean(trustedSchool&&request.url.startsWith('/v1/internal/school/'));
    }
  });app.decorateRequest('auth',null);app.addHook('onRequest',async request=>{const h=request.headers.authorization;if(!h)return;const[s,t]=h.split(' ');if(s!=='Bearer'||!t)throw new AppError(401,'UNAUTHORIZED','Malformed authorization header');request.auth=await verifyAccessToken(config,t);const a=await db.query(request.auth.preview?`SELECT 1 FROM sessions s JOIN organisation_memberships m ON m.user_id=s.user_id AND m.organisation_id=s.organisation_id WHERE s.id=$1 AND s.user_id=$2 AND s.organisation_id=$3 AND s.revoked_at IS NULL AND s.expires_at>now()`:`SELECT 1 FROM sessions s JOIN organisation_memberships m ON m.user_id=s.user_id AND m.organisation_id=s.organisation_id WHERE s.id=$1 AND s.user_id=$2 AND s.organisation_id=$3 AND s.revoked_at IS NULL AND s.expires_at>now() AND m.status='active'`,[request.auth.sessionId,request.auth.userId,request.auth.organisationId]);if(!a.rowCount)throw new AppError(401,'UNAUTHORIZED','Session is no longer active')});app.get('/',async(_r,p)=>p.type('text/html; charset=utf-8').send(osFrontend));app.get('/health/live',async()=>({status:'ok'}));app.get('/health/ready',async(_r,p)=>{try{await db.query('SELECT 1');return{status:'ready'}}catch{return p.code(503).send({status:'unavailable'})}});await app.register(authRoutes,{db,config});await app.register(previewRoutes,{db,config});await app.register(organisationRoutes,{db});await app.register(userRoutes,{db});await app.register(operationRoutes,{db});await app.register(workflowRoutes,{db});await app.register(platformRoutes,{db,config});await app.register(commercialRoutes,{db});await app.register(internalSchoolRoutes,{db,config});app.setNotFoundHandler((r,p)=>p.code(404).send({error:{code:'NOT_FOUND',message:`Route ${r.method} ${r.url} not found`,requestId:r.id}}));app.setErrorHandler((e,r,p)=>{if(e instanceof ZodError)return p.code(400).send({error:{code:'VALIDATION_ERROR',message:e.issues[0]?.message||'Request validation failed',details:e.issues,requestId:r.id}});if(e instanceof AppError)return p.code(e.statusCode).send({error:{code:e.code,message:e.message,details:e.details,requestId:r.id}});r.log.error(e);return p.code(500).send({error:{code:'INTERNAL_ERROR',message:'An unexpected error occurred',requestId:r.id}})});return app}