export const commercialControlFrontend=String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Revolt-X OS | Customers & Licensing</title>
<style>
:root{--navy:#081c33;--navy2:#0c2949;--blue:#1d62d6;--gold:#f2b742;--green:#20a36a;--red:#d94f5c;--bg:#f4f7fb;--card:#fff;--ink:#172536;--muted:#718096;--line:#dce5ef}
*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;background:var(--bg);color:var(--ink)}button,input,select,textarea{font:inherit}
.layout{display:grid;grid-template-columns:250px 1fr;min-height:100vh}.side{background:linear-gradient(180deg,var(--navy),#102e50);color:white;padding:24px 16px;position:sticky;top:0;height:100vh}.brand{font-weight:900;font-size:20px;letter-spacing:.3px;margin-bottom:28px}.brand span{display:inline-grid;place-items:center;width:36px;height:36px;border-radius:10px;background:var(--gold);color:var(--navy);margin-right:8px}.side small{color:#9fb3c9}.nav{display:grid;gap:8px;margin-top:24px}.nav button{border:0;background:transparent;color:#dce9f6;text-align:left;padding:12px 14px;border-radius:10px;cursor:pointer}.nav button.active,.nav button:hover{background:#ffffff16;color:white}.back{position:absolute;bottom:24px;left:16px;right:16px;border:1px solid #ffffff33;background:#ffffff0d;color:white;padding:11px;border-radius:10px;cursor:pointer}
.main{padding:24px 28px 60px;min-width:0}.top{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:24px}.top h1{margin:0;font-size:25px}.sub{color:var(--muted);font-size:13px}.actions{display:flex;gap:8px;flex-wrap:wrap}.btn{border:0;border-radius:10px;padding:10px 14px;font-weight:700;cursor:pointer}.primary{background:var(--blue);color:white}.gold{background:var(--gold);color:var(--navy)}.ghost{background:white;border:1px solid var(--line);color:var(--ink)}.danger{background:#fff0f1;color:#a62834;border:1px solid #f6cbd0}
.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.kpi{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:18px;box-shadow:0 8px 24px #2038540b}.kpi span{display:block;color:var(--muted);font-size:12px}.kpi b{display:block;font-size:28px;margin-top:7px}.kpi em{font-style:normal;font-size:11px;color:var(--green)}
.panel{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:18px;box-shadow:0 8px 24px #2038540b;margin-top:14px}.panel h2,.panel h3{margin:0 0 12px}.split{display:grid;grid-template-columns:1.35fr .65fr;gap:14px}.toolbar{display:flex;gap:8px;align-items:center;justify-content:space-between;margin:14px 0}.toolbar input,.toolbar select{border:1px solid var(--line);padding:10px 12px;border-radius:10px;background:#fff;min-width:180px}
.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:11px 10px;border-bottom:1px solid #edf1f5;white-space:nowrap}th{font-size:11px;color:#66788d;text-transform:uppercase;letter-spacing:.04em}.badge{display:inline-flex;padding:5px 9px;border-radius:999px;font-size:11px;font-weight:800;background:#e9f7f0;color:#147a4d}.badge.trial,.badge.grace{background:#fff5da;color:#9b6b00}.badge.suspended,.badge.expired,.badge.cancelled{background:#fdebec;color:#a72934}.badge.unlicensed{background:#eef1f5;color:#627083}.mini{border:1px solid var(--line);background:white;border-radius:8px;padding:6px 9px;cursor:pointer}.mini:hover{border-color:#9fb8d3}
.cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.plan{border:1px solid var(--line);border-radius:16px;padding:16px;background:white;position:relative}.plan.professional{border:2px solid var(--blue)}.plan .price{font-size:26px;font-weight:900;color:var(--navy)}.plan ul{padding-left:18px;color:#52667b;font-size:12px;line-height:1.7}.modulegrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.module{border:1px solid var(--line);padding:12px;border-radius:12px;background:#fbfdff}.module b{display:block}.module small{color:var(--muted)}
.modal{position:fixed;inset:0;background:#07111fa8;display:grid;place-items:center;padding:20px;z-index:50}.modal.hidden,.hidden{display:none!important}.dialog{background:white;width:min(760px,96vw);max-height:90vh;overflow:auto;border-radius:18px;padding:22px;box-shadow:0 30px 80px #0005}.dialog h2{margin-top:0}.fields{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field{display:grid;gap:6px}.field.full{grid-column:1/-1}.field label{font-size:12px;font-weight:700;color:#4a5f76}.field input,.field select,.field textarea{border:1px solid var(--line);padding:11px;border-radius:10px}.modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}
.drawer{position:fixed;top:0;right:0;height:100vh;width:min(620px,96vw);background:white;z-index:40;box-shadow:-20px 0 60px #07111f30;padding:22px;overflow:auto}.drawer.hidden{display:none}.drawer-head{display:flex;justify-content:space-between;align-items:flex-start}.drawer .metric{display:grid;grid-template-columns:1fr 1fr;gap:10px}.drawer .metric div{background:#f7f9fc;border-radius:12px;padding:12px}.toggle{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #edf1f5;padding:10px 0}.toast{position:fixed;right:22px;bottom:22px;background:#102e50;color:white;padding:12px 16px;border-radius:10px;box-shadow:0 16px 50px #0003;z-index:100}.notice{background:#eef5ff;border:1px solid #cfe0fb;border-radius:12px;padding:12px;color:#315b88}.empty{padding:30px;text-align:center;color:var(--muted)}
@media(max-width:1050px){.grid,.cards{grid-template-columns:repeat(2,1fr)}.modulegrid{grid-template-columns:repeat(2,1fr)}.split{grid-template-columns:1fr}}
@media(max-width:760px){.layout{grid-template-columns:78px 1fr}.side{padding:20px 8px}.brand{font-size:0}.brand span{margin:0}.side small{display:none}.nav button{font-size:0;text-align:center}.nav button:before{content:attr(data-icon);font-size:18px}.back{font-size:0}.back:before{content:"←";font-size:20px}.main{padding:18px 12px}.grid,.cards,.modulegrid,.fields{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}.field.full{grid-column:auto}}
</style>
</head>
<body>
<div class="layout">
<aside class="side">
 <div class="brand"><span>RX</span>REVOLT-X OS</div><small>Commercial Control Centre</small>
 <div class="nav">
  <button class="active" data-page="overview" data-icon="⌂">Overview</button>
  <button data-page="schools" data-icon="S">Schools & Customers</button>
  <button data-page="plans" data-icon="P">Plans & Modules</button>
  <button data-page="billing" data-icon="₵">Billing & Invoices</button>
 </div>
 <button class="back" id="backOs">← Back to Core OS</button>
</aside>
<main class="main">
 <div class="top"><div><h1 id="pageTitle">Commercial Overview</h1><div class="sub">Manage school tenants, pricing, licences, entitlements and subscription billing.</div></div>
 <div class="actions"><button class="btn ghost" id="refresh">Refresh</button><button class="btn gold" id="newSchool">+ Add School</button></div></div>
 <div id="content"></div>
</main>
</div>
<div class="modal hidden" id="modal"><div class="dialog"><div id="modalBody"></div></div></div>
<div class="drawer hidden" id="drawer"><div id="drawerBody"></div></div>
<div class="toast hidden" id="toast"></div>
<script>
(function(){
var token=sessionStorage.getItem("rx_access")||"",refreshToken=sessionStorage.getItem("rx_refresh")||"",catalog=null,schools=[],current="overview";
var E=function(id){return document.getElementById(id)};
var esc=function(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]})};
var money=function(v,c){return (c||"GHS")+" "+Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})};
var badge=function(v){var x=String(v||"unlicensed");return '<span class="badge '+esc(x)+'">'+esc(x.replaceAll("_"," "))+'</span>'};
var fmt=function(v){if(!v)return"—";try{return new Date(v).toLocaleDateString()}catch(e){return v}};
function toast(msg,bad){var t=E("toast");t.textContent=msg;t.style.background=bad?"#8f2731":"#102e50";t.classList.remove("hidden");setTimeout(function(){t.classList.add("hidden")},3200)}
async function raw(path,opt){opt=opt||{};opt.headers=Object.assign({"content-type":"application/json"},opt.headers||{},token?{authorization:"Bearer "+token}:{});
 var r=await fetch(path,opt),j=null;try{j=await r.json()}catch(e){}
 if(r.status===401&&refreshToken){var rr=await fetch("/v1/auth/refresh",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({refreshToken:refreshToken})});if(rr.ok){var n=await rr.json();token=n.accessToken;refreshToken=n.refreshToken;sessionStorage.setItem("rx_access",token);sessionStorage.setItem("rx_refresh",refreshToken);return raw(path,opt)}}
 if(!r.ok)throw Error(j&&j.error&&j.error.message?j.error.message:"Request failed ("+r.status+")");return j}
function closeModal(){E("modal").classList.add("hidden");E("modalBody").innerHTML=""}
function showModal(html){E("modalBody").innerHTML=html;E("modal").classList.remove("hidden")}
function closeDrawer(){E("drawer").classList.add("hidden");E("drawerBody").innerHTML=""}
function table(rows,cols,action){if(!rows||!rows.length)return '<div class="empty">No records yet.</div>';return '<div class="tablewrap"><table><thead><tr>'+cols.map(function(c){return"<th>"+esc(c.label||c.key)+"</th>"}).join("")+(action?"<th>Action</th>":"")+'</tr></thead><tbody>'+rows.map(function(r){return"<tr>"+cols.map(function(c){var v=c.render?c.render(r):r[c.key];return"<td>"+(v==null?"":v)+"</td>"}).join("")+(action?"<td>"+action(r)+"</td>":"")+"</tr>"}).join("")+"</tbody></table></div>"}
async function loadBase(){if(!token){location.href="/demo-login";return false}catalog=await raw("/v1/commercial-control/catalog");schools=await raw("/v1/commercial-control/schools");var q=new URLSearchParams(location.search);if(q.get("demo")==="1"&&schools.length===0){await raw("/v1/commercial-control/demo-seed",{method:"POST",body:"{}"});schools=await raw("/v1/commercial-control/schools")}return true}
function planById(id){return (catalog.plans||[]).find(function(p){return p.id===id})}
function openNewSchool(){
 var opts=catalog.plans.map(function(p){return '<option value="'+p.id+'">'+esc(p.name)+" · "+money(p.monthly_price,p.currency)+"/month</option>"}).join("");
 showModal('<h2>Create a School Tenant</h2><div class="notice">This creates a real organisation in Revolt-X OS, attaches a School subscription and prepares a tenant domain record.</div><div class="fields" style="margin-top:14px">'+
 '<div class="field full"><label>School name</label><input id="fName" placeholder="e.g. Grace Preparatory School"></div>'+
 '<div class="field"><label>School type</label><input id="fType" placeholder="Basic & JHS"></div>'+
 '<div class="field"><label>Contact person</label><input id="fContact" placeholder="School administrator"></div>'+
 '<div class="field"><label>Contact email</label><input id="fEmail" type="email"></div>'+
 '<div class="field"><label>Contact phone</label><input id="fPhone"></div>'+
 '<div class="field"><label>Plan</label><select id="fPlan">'+opts+'</select></div>'+
 '<div class="field"><label>Billing</label><select id="fBilling"><option value="monthly">Monthly</option><option value="termly">Termly</option><option value="annual">Annual</option></select></div>'+
 '<div class="field"><label>Licence</label><select id="fStatus"><option value="trial">14-day Trial</option><option value="active">Active</option></select></div>'+
 '<div class="field full"><label>Address</label><textarea id="fAddress" rows="2"></textarea></div></div>'+
 '<div class="modal-actions"><button class="btn ghost" id="mCancel">Cancel</button><button class="btn primary" id="mSave">Create School</button></div>');
 E("mCancel").onclick=closeModal;E("mSave").onclick=async function(){var b=E("mSave");b.disabled=true;try{await raw("/v1/commercial-control/schools",{method:"POST",body:JSON.stringify({name:E("fName").value,schoolType:E("fType").value||undefined,contactName:E("fContact").value||undefined,contactEmail:E("fEmail").value||undefined,contactPhone:E("fPhone").value||undefined,address:E("fAddress").value||undefined,planId:E("fPlan").value,billingFrequency:E("fBilling").value,licenceStatus:E("fStatus").value})});closeModal();toast("School tenant created");await loadBase();page("schools")}catch(e){toast(e.message,true);b.disabled=false}}
}
async function openSchool(id){
 var d=await raw("/v1/commercial-control/schools/"+id),lic=d.license,u={};(d.usage||[]).forEach(function(x){u[x.metric_key]=Number(x.metric_value)});
 var moduleHtml=(catalog.modules||[]).map(function(m){var on=(lic.modules||[]).includes(m.module_key);return '<div class="toggle"><div><b>'+esc(m.name)+'</b><div class="sub">'+esc(m.module_key)+'</div></div><label><input type="checkbox" data-module="'+esc(m.module_key)+'" '+(on?"checked":"")+'> '+(on?"On":"Off")+'</label></div>'}).join("");
 E("drawerBody").innerHTML='<div class="drawer-head"><div><h2>'+esc(d.customer.name)+'</h2><div class="sub">'+esc(d.customer.slug)+'</div></div><button class="btn ghost" id="closeDrawer">Close</button></div>'+
 '<div class="metric" style="margin-top:16px"><div><small>Licence</small><b>'+badge(lic.status)+'</b></div><div><small>Plan</small><b>'+esc(lic.planName||"—")+'</b></div><div><small>Recurring</small><b>'+money(lic.recurringAmount,lic.currency)+'</b></div><div><small>Renews</small><b>'+fmt(lic.periodEnd)+'</b></div><div><small>Students</small><b>'+esc(u.students||0)+' / '+esc((lic.limits||{}).students||"∞")+'</b></div><div><small>Staff</small><b>'+esc(u.staff||0)+' / '+esc((lic.limits||{}).staff||"∞")+'</b></div></div>'+
 '<div class="panel"><h3>Licence Control</h3><div class="actions"><button class="mini" data-license="active">Activate</button><button class="mini" data-license="grace">Grace</button><button class="mini" data-license="suspended">Suspend</button><button class="mini" data-license="expired">Expire</button></div></div>'+
 '<div class="panel"><h3>Module Entitlements</h3>'+moduleHtml+'</div>'+
 '<div class="panel"><h3>Billing</h3><div class="actions"><button class="btn primary" id="issueInvoice">Issue '+esc(lic.billingFrequency||"monthly")+' Invoice</button></div>'+table(d.invoices,[{key:"invoice_no",label:"Invoice"},{key:"status",render:function(r){return badge(r.status)}},{key:"total",render:function(r){return money(r.total,r.currency)}},{key:"amount_paid",label:"Paid",render:function(r){return money(r.amount_paid,r.currency)}}],function(r){return r.status!=="paid"&&r.status!=="void"?'<button class="mini" data-pay-invoice="'+r.id+'" data-balance="'+(Number(r.total)-Number(r.amount_paid))+'">Record payment</button>':""})+'</div>'+
 '<div class="panel"><h3>Tenant Domains</h3>'+table(d.domains,[{key:"domain"},{key:"domain_type",label:"Type"},{key:"status",render:function(r){return badge(r.status)}}])+'</div>';
 E("drawer").classList.remove("hidden");E("closeDrawer").onclick=closeDrawer;
 E("drawerBody").querySelectorAll("[data-license]").forEach(function(b){b.onclick=async function(){try{await raw("/v1/commercial-control/schools/"+id+"/license",{method:"PATCH",body:JSON.stringify({status:b.dataset.license})});toast("Licence updated");await loadBase();openSchool(id)}catch(e){toast(e.message,true)}}});
 E("drawerBody").querySelectorAll("[data-module]").forEach(function(c){c.onchange=async function(){try{await raw("/v1/commercial-control/schools/"+id+"/modules",{method:"PUT",body:JSON.stringify({moduleKey:c.dataset.module,enabled:c.checked})});toast("Module entitlement updated")}catch(e){c.checked=!c.checked;toast(e.message,true)}}});
 E("issueInvoice").onclick=async function(){try{await raw("/v1/commercial-control/schools/"+id+"/invoices",{method:"POST",body:JSON.stringify({dueDays:14})});toast("Invoice issued");await openSchool(id)}catch(e){toast(e.message,true)}};
 E("drawerBody").querySelectorAll("[data-pay-invoice]").forEach(function(b){b.onclick=function(){showModal('<h2>Record Subscription Payment</h2><div class="fields"><div class="field"><label>Amount</label><input id="payAmount" type="number" step="0.01" value="'+b.dataset.balance+'"></div><div class="field"><label>Method</label><select id="payMethod"><option value="bank_transfer">Bank Transfer</option><option value="mobile_money">Mobile Money</option><option value="card">Card</option><option value="cash">Cash</option></select></div><div class="field full"><label>Reference</label><input id="payRef"></div></div><div class="modal-actions"><button class="btn ghost" id="mCancel">Cancel</button><button class="btn primary" id="mSave">Post Payment</button></div>');E("mCancel").onclick=closeModal;E("mSave").onclick=async function(){try{await raw("/v1/commercial-control/invoices/"+b.dataset.payInvoice+"/payments",{method:"POST",body:JSON.stringify({amount:Number(E("payAmount").value),paymentMethod:E("payMethod").value,providerReference:E("payRef").value||undefined})});closeModal();toast("Payment recorded and licence renewed where fully paid");await loadBase();openSchool(id)}catch(e){toast(e.message,true)}}}})}
}
async function overview(){
 var o=await raw("/v1/commercial-control/overview");E("pageTitle").textContent="Commercial Overview";
 var renew=o.renewals||[];
 E("content").innerHTML='<div class="grid"><div class="kpi"><span>Managed Schools</span><b>'+esc(o.schools)+'</b><em>Customer organisations</em></div><div class="kpi"><span>Active Licences</span><b>'+esc(o.active_licences)+'</b><em>Currently enabled</em></div><div class="kpi"><span>Trials</span><b>'+esc(o.trials)+'</b><em>Conversion pipeline</em></div><div class="kpi"><span>Needs Attention</span><b>'+esc(o.attention)+'</b><em>Grace / suspended / expired</em></div><div class="kpi"><span>Estimated MRR</span><b>'+money(o.monthly_recurring_revenue)+'</b><em>Normalised recurring revenue</em></div><div class="kpi"><span>Outstanding Invoices</span><b>'+money(o.outstanding_invoices)+'</b><em>Issued and unpaid</em></div></div>'+
 '<div class="split"><div class="panel"><h3>Renewals Due in 60 Days</h3>'+table(renew,[{key:"name",label:"School"},{key:"plan_name",label:"Plan"},{key:"status",render:function(r){return badge(r.status)}},{key:"current_period_end",label:"Renewal",render:function(r){return fmt(r.current_period_end)}},{key:"recurring_amount",label:"Value",render:function(r){return money(r.recurring_amount,r.currency)}}])+'</div>'+
 '<div class="panel"><h3>Licence Status</h3>'+(o.subscriptionStatus||[]).map(function(x){return '<div class="toggle"><span>'+badge(x.status)+'</span><b>'+esc(x.count)+'</b></div>'}).join("")+'<div class="notice" style="margin-top:12px"><b>How this works</b><br>Revolt-X OS is the source of truth. Each School organisation receives a plan, module entitlements, usage limits and a licence status.</div></div></div>';
}
function schoolsPage(){
 E("pageTitle").textContent="Schools & Customers";
 var q='<div class="toolbar"><input id="schoolSearch" placeholder="Search school or plan"><div class="actions"><button class="btn ghost" id="seedDemo">Load 10 Demo Schools</button><button class="btn primary" id="addSchool2">+ Add School</button></div></div>';
 E("content").innerHTML=q+'<div class="panel">'+table(schools,[{key:"name",label:"School"},{key:"school_type",label:"Type"},{key:"plan_name",label:"Plan"},{key:"licence_status",label:"Licence",render:function(r){return badge(r.licence_status)}},{key:"recurring_amount",label:"Price",render:function(r){return money(r.recurring_amount,r.currency)+" / "+esc(r.billing_frequency||"—")}},{key:"current_period_end",label:"Renewal",render:function(r){return fmt(r.current_period_end)}},{key:"primary_contact_phone",label:"Contact"}],function(r){return '<button class="mini" data-open-school="'+r.id+'">Open</button>'})+'</div>';
 E("addSchool2").onclick=openNewSchool;E("seedDemo").onclick=async function(){var b=E("seedDemo");b.disabled=true;try{var x=await raw("/v1/commercial-control/demo-seed",{method:"POST",body:"{}"});toast("Demo portfolio ready: "+x.total+" schools");await loadBase();schoolsPage()}catch(e){toast(e.message,true);b.disabled=false}};
 E("content").onclick=function(e){var b=e.target.closest("[data-open-school]");if(b)openSchool(b.dataset.openSchool)};
 E("schoolSearch").oninput=function(){var term=this.value.toLowerCase(),rows=schools.filter(function(x){return (x.name+" "+(x.plan_name||"")+" "+(x.licence_status||"")).toLowerCase().includes(term)});E("content").querySelector(".panel").innerHTML=table(rows,[{key:"name",label:"School"},{key:"school_type",label:"Type"},{key:"plan_name",label:"Plan"},{key:"licence_status",label:"Licence",render:function(r){return badge(r.licence_status)}},{key:"recurring_amount",label:"Price",render:function(r){return money(r.recurring_amount,r.currency)+" / "+esc(r.billing_frequency||"—")}},{key:"current_period_end",label:"Renewal",render:function(r){return fmt(r.current_period_end)}},{key:"primary_contact_phone",label:"Contact"}],function(r){return '<button class="mini" data-open-school="'+r.id+'">Open</button>'})}
}
function plansPage(){
 E("pageTitle").textContent="Plans & Modules";
 E("content").innerHTML='<div class="notice">Pricing is controlled centrally here. Schools inherit plan modules and limits, while individual subscriptions can receive module overrides.</div><div class="cards" style="margin-top:14px">'+catalog.plans.map(function(p){return '<div class="plan '+esc(p.plan_key)+'"><h3>'+esc(p.name)+'</h3><div class="price">'+money(p.monthly_price,p.currency)+'</div><div class="sub">per month · '+money(p.termly_price,p.currency)+' termly · '+money(p.annual_price,p.currency)+' annually</div><p class="sub">'+esc(p.description||"")+'</p><div class="sub"><b>'+esc(p.student_limit||"∞")+'</b> students · <b>'+esc(p.staff_limit||"∞")+'</b> staff · <b>'+esc(p.campus_limit||"∞")+'</b> campuses</div><ul>'+p.modules.slice(0,7).map(function(k){var m=catalog.modules.find(function(x){return x.module_key===k});return"<li>"+esc(m?m.name:k)+"</li>"}).join("")+(p.modules.length>7?"<li>+"+(p.modules.length-7)+" more</li>":"")+'</ul><button class="btn ghost" data-edit-plan="'+p.id+'">Edit Pricing</button></div>'}).join("")+'</div>'+
 '<div class="panel"><h3>Module Catalogue</h3><div class="modulegrid">'+catalog.modules.map(function(m){return '<div class="module"><b>'+esc(m.name)+'</b><small>'+esc(m.module_key)+'</small><p class="sub">'+esc(m.description||"")+'</p><b>'+money(m.base_monthly_price,"GHS")+' base</b></div>'}).join("")+'</div></div>';
 E("content").querySelectorAll("[data-edit-plan]").forEach(function(b){b.onclick=function(){var p=planById(b.dataset.editPlan);showModal('<h2>Edit '+esc(p.name)+' Pricing</h2><div class="fields"><div class="field"><label>Monthly Price (GHS)</label><input id="pMonthly" type="number" value="'+p.monthly_price+'"></div><div class="field"><label>Termly Price (GHS)</label><input id="pTermly" type="number" value="'+p.termly_price+'"></div><div class="field"><label>Annual Price (GHS)</label><input id="pAnnual" type="number" value="'+p.annual_price+'"></div><div class="field"><label>Student Limit</label><input id="pStudents" type="number" value="'+(p.student_limit||"")+'"></div><div class="field"><label>Staff Limit</label><input id="pStaff" type="number" value="'+(p.staff_limit||"")+'"></div><div class="field"><label>Campus Limit</label><input id="pCampus" type="number" value="'+(p.campus_limit||"")+'"></div></div><div class="modal-actions"><button class="btn ghost" id="mCancel">Cancel</button><button class="btn primary" id="mSave">Save Pricing</button></div>');E("mCancel").onclick=closeModal;E("mSave").onclick=async function(){try{await raw("/v1/commercial-control/plans/"+p.id,{method:"PATCH",body:JSON.stringify({monthlyPrice:Number(E("pMonthly").value),termlyPrice:Number(E("pTermly").value),annualPrice:Number(E("pAnnual").value),studentLimit:Number(E("pStudents").value)||null,staffLimit:Number(E("pStaff").value)||null,campusLimit:Number(E("pCampus").value)||null})});closeModal();toast("Pricing updated");await loadBase();plansPage()}catch(e){toast(e.message,true)}}}}
 )}
async function billingPage(){
 E("pageTitle").textContent="Billing & Invoices";var inv=await raw("/v1/commercial-control/invoices");
 E("content").innerHTML='<div class="grid"><div class="kpi"><span>Total Invoices</span><b>'+inv.length+'</b></div><div class="kpi"><span>Paid</span><b>'+inv.filter(function(x){return x.status==="paid"}).length+'</b></div><div class="kpi"><span>Outstanding</span><b>'+money(inv.filter(function(x){return ["issued","part_paid","overdue"].includes(x.status)}).reduce(function(a,x){return a+Number(x.total)-Number(x.amount_paid)},0))+'</b></div><div class="kpi"><span>Collected</span><b>'+money(inv.reduce(function(a,x){return a+Number(x.amount_paid)},0))+'</b></div></div><div class="panel">'+table(inv,[{key:"invoice_no",label:"Invoice"},{key:"customer_name",label:"School"},{key:"status",render:function(r){return badge(r.status)}},{key:"total",render:function(r){return money(r.total,r.currency)}},{key:"amount_paid",label:"Paid",render:function(r){return money(r.amount_paid,r.currency)}},{key:"due_at",label:"Due",render:function(r){return fmt(r.due_at)}}])+'</div>';
}
async function page(p){current=p;document.querySelectorAll(".nav button").forEach(function(b){b.classList.toggle("active",b.dataset.page===p)});E("content").innerHTML='<div class="empty">Loading...</div>';try{if(p==="overview")await overview();else if(p==="schools")schoolsPage();else if(p==="plans")plansPage();else if(p==="billing")await billingPage()}catch(e){E("content").innerHTML='<div class="panel"><h3>Could not load Commercial Control</h3><p class="sub">'+esc(e.message)+'</p></div>'}}
document.querySelector(".nav").onclick=function(e){var b=e.target.closest("[data-page]");if(b)page(b.dataset.page)};
E("backOs").onclick=function(){location.href="/"};E("refresh").onclick=function(){page(current)};E("newSchool").onclick=openNewSchool;E("modal").onclick=function(e){if(e.target===E("modal"))closeModal()};
(async function(){try{if(!await loadBase())return;await page("overview")}catch(e){if(String(e.message).includes("Permission")||String(e.message).includes("Authentication"))location.href="/demo-login";else E("content").innerHTML='<div class="panel"><h3>Commercial Control unavailable</h3><p>'+esc(e.message)+'</p></div>'}})();
})();
</script>
</body></html>`;
